### ISSUE TITLE
Nemo hangs suddenly

### ISSUE THREAD

**Issue by Mygod** [linuxmint/nemo#1090]
I'm running the latest version. `killall` then restart doesn't help.

```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nemo...Reading symbols from /usr/lib/debug//usr/bin/nemo...done.
done.
(gdb) run
Starting program: /usr/bin/nemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
[New Thread 0x7fffed67f700 (LWP 14825)]
[New Thread 0x7fffece7e700 (LWP 14826)]
[New Thread 0x7fffe7fff700 (LWP 14827)]
Initializing folder-color-switcher extension...
[New Thread 0x7fffe4e34700 (LWP 14828)]
[New Thread 0x7fffd4f45700 (LWP 14830)]
[New Thread 0x7fffcffff700 (LWP 14831)]
[New Thread 0x7fffcf7fe700 (LWP 14832)]
[Thread 0x7fffcf7fe700 (LWP 14832) exited]
[Thread 0x7fffd4f45700 (LWP 14830) exited]
[Thread 0x7fffcffff700 (LWP 14831) exited]
[Thread 0x7fffece7e700 (LWP 14826) exited]
^C
Program received signal SIGINT, Interrupt.
0x00007ffff428212d in poll () at ../sysdeps/unix/syscall-template.S:81
81  ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) thread apply all bt

Thread 5 (Thread 0x7fffe4e34700 (LWP 14828)):
#0  0x00007ffff428212d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff503afe4 in g_main_context_poll (priority=2147483647, n_fds=2, 
    fds=0x7fffd00008c0, timeout=3996, context=0xc4a9e0)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:4028
#2  g_main_context_iterate (context=context@entry=0xc4a9e0, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3729
#3  0x00007ffff503b0ec in g_main_context_iteration (context=0xc4a9e0, 
    may_block=may_block@entry=1)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3795
#4  0x00007ffff503b129 in glib_worker_main (data=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:5541
#5  0x00007ffff505ff05 in g_thread_proxy (data=0xc1e0f0)
    at /build/buildd/glib2.0-2.40.2/./glib/gthread.c:764
#6  0x00007ffff4562182 in start_thread (arg=0x7fffe4e34700)
    at pthread_create.c:312
#7  0x00007ffff428f47d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 4 (Thread 0x7fffe7fff700 (LWP 14827)):
#0  0x00007ffff428212d in poll () at ../sysdeps/unix/syscall-template.S:81
---Type <return> to continue, or q <return> to quit---
#1  0x00007ffff503afe4 in g_main_context_poll (priority=2147483647, n_fds=1, 
    fds=0x7fffdc0010c0, timeout=-1, context=0x96f520)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:4028
#2  g_main_context_iterate (context=context@entry=0x96f520, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3729
#3  0x00007ffff503b0ec in g_main_context_iteration (context=0x96f520, 
    may_block=1) at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3795
#4  0x00007fffed6871ad in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007ffff505ff05 in g_thread_proxy (data=0x7fffe8004630)
    at /build/buildd/glib2.0-2.40.2/./glib/gthread.c:764
#6  0x00007ffff4562182 in start_thread (arg=0x7fffe7fff700)
    at pthread_create.c:312
#7  0x00007ffff428f47d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7fffed67f700 (LWP 14825)):
#0  0x00007ffff428212d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff503afe4 in g_main_context_poll (priority=2147483647, n_fds=7, 
    fds=0x7fffe8011320, timeout=-1, context=0x8562d0)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:4028
#2  g_main_context_iterate (context=0x8562d0, block=block@entry=1, 
---Type <return> to continue, or q <return> to quit---
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3729
#3  0x00007ffff503b30a in g_main_loop_run (loop=0x856260)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
#4  0x00007ffff5622336 in gdbus_shared_thread_func (user_data=0x8562a0)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusprivate.c:273
#5  0x00007ffff505ff05 in g_thread_proxy (data=0x800a30)
    at /build/buildd/glib2.0-2.40.2/./glib/gthread.c:764
#6  0x00007ffff4562182 in start_thread (arg=0x7fffed67f700)
    at pthread_create.c:312
#7  0x00007ffff428f47d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7ffff7fb99c0 (LWP 14821)):
#0  0x00007ffff428212d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff503afe4 in g_main_context_poll (priority=2147483647, n_fds=1, 
    fds=0xf15790, timeout=-1, context=0xf15400)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:4028
#2  g_main_context_iterate (context=0xf15400, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3729
#3  0x00007ffff503b30a in g_main_loop_run (loop=0xf15510)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3928
---Type <return> to continue, or q <return> to quit---
#4  0x00007ffff5614b83 in g_dbus_connection_send_message_with_reply_sync (
    connection=connection@entry=0xe78070, message=message@entry=0xfc3a80, 
    flags=flags@entry=G_DBUS_SEND_MESSAGE_FLAGS_NONE, 
    timeout_msec=timeout_msec@entry=2147483647, 
    out_serial=out_serial@entry=0x0, cancellable=cancellable@entry=0x0, 
    error=error@entry=0x7fffffffd288)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusconnection.c:2252
#5  0x00007ffff5614faf in g_dbus_connection_call_sync_internal (
    connection=0xe78070, bus_name=bus_name@entry=0xf13ab0 ":1.60", 
    object_path=0xf139f0 "/org/gtk/vfs/mount/1", 
    interface_name=interface_name@entry=0xf13930 "org.gtk.vfs.Mount", 
    method_name=method_name@entry=0x7fffee321b78 "QueryFilesystemInfo", 
    parameters=parameters@entry=0xed26c0, reply_type=0xfc5fe0, 
    flags=G_DBUS_CALL_FLAGS_NONE, timeout_msec=2147483647, fd_list=0x0, 
    out_fd_list=0x0, cancellable=0x0, error=0x7fffffffd408)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusconnection.c:5723
#6  0x00007ffff5617245 in g_dbus_connection_call_with_unix_fd_list_sync (
    connection=<optimized out>, bus_name=bus_name@entry=0xf13ab0 ":1.60", 
    object_path=<optimized out>, 
    interface_name=interface_name@entry=0xf13930 "org.gtk.vfs.Mount", 
    method_name=method_name@entry=0x7fffee321b78 "QueryFilesystemInfo", 
    parameters=parameters@entry=0xed26c0, 
    reply_type=reply_type@entry=0xfc5fe0, 
---Type <return> to continue, or q <return> to quit---
    flags=flags@entry=G_DBUS_CALL_FLAGS_NONE, timeout_msec=2147483647, 
    fd_list=fd_list@entry=0x0, out_fd_list=out_fd_list@entry=0x0, 
    cancellable=cancellable@entry=0x0, error=error@entry=0x7fffffffd408)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusconnection.c:6069
#7  0x00007ffff5620ac3 in g_dbus_proxy_call_sync_internal (proxy=0xf7a0b0, 
    method_name=<optimized out>, parameters=0xed26c0, 
    flags=G_DBUS_CALL_FLAGS_NONE, timeout_msec=-1, fd_list=fd_list@entry=0x0, 
    out_fd_list=out_fd_list@entry=0x0, cancellable=0x0, 
    error=error@entry=0x7fffffffd408)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusproxy.c:2901
#8  0x00007ffff5621ee3 in g_dbus_proxy_call_sync (proxy=<optimized out>, 
    method_name=<optimized out>, parameters=<optimized out>, 
    flags=<optimized out>, timeout_msec=<optimized out>, 
    cancellable=<optimized out>, error=0x7fffffffd408)
    at /build/buildd/glib2.0-2.40.2/./gio/gdbusproxy.c:3093
#9  0x00007fffee3191ba in gvfs_dbus_mount_call_query_filesystem_info_sync ()
   from /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
#10 0x00007fffee545506 in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
#11 0x000000000046ad79 in get_disk_full (file=<optimized out>, 
    tooltip_info=tooltip_info@entry=0x7fffffffd608)
    at nemo-places-sidebar.c:607
#12 0x000000000047302f in update_places (sidebar=sidebar@entry=0xfae1e0)
---Type <return> to continue, or q <return> to quit---
    at nemo-places-sidebar.c:1077
#13 0x00000000004747b2 in nemo_places_sidebar_set_parent_window (
    window=0xdce3b0, sidebar=0xfae1e0) at nemo-places-sidebar.c:4399
#14 nemo_places_sidebar_new (window=window@entry=0xdce3b0)
    at nemo-places-sidebar.c:4418
#15 0x00000000004bad28 in nemo_window_set_up_sidebar (window=0xdce3b0)
    at nemo-window.c:437
#16 0x00000000004bb0db in nemo_window_show_sidebar (window=0xdce3b0)
    at nemo-window.c:490
#17 nemo_window_show (widget=0xdce3b0) at nemo-window.c:1739
#18 0x00007ffff530a3b8 in g_closure_invoke (closure=0x7e4490, 
    return_value=0x0, n_param_values=1, param_values=0x7fffffffd930, 
    invocation_hint=0x7fffffffd8d0)
    at /build/buildd/glib2.0-2.40.2/./gobject/gclosure.c:768
#19 0x00007ffff531b557 in signal_emit_unlocked_R (node=node@entry=0x7ee170, 
    detail=detail@entry=0, instance=instance@entry=0xdce3b0, 
    emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fffffffd930)
    at /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:3481
#20 0x00007ffff5323a29 in g_signal_emit_valist (instance=<optimized out>, 
    signal_id=<optimized out>, detail=<optimized out>, 
    var_args=var_args@entry=0x7fffffffdab8)
    at /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:3307
---Type <return> to continue, or q <return> to quit---
#21 0x00007ffff5323ce2 in g_signal_emit (instance=instance@entry=0xdce3b0, 
    signal_id=<optimized out>, detail=detail@entry=0)
    at /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:3363
#22 0x00007ffff6df200c in gtk_widget_show (widget=0xdce3b0)
    at /tmp/buildd/gtk+3.0-3.10.8~8+qiana/./gtk/gtkwidget.c:4336
#23 0x00000000004bbb95 in nemo_window_view_visible (window=<optimized out>, 
    view=<optimized out>) at nemo-window.c:858
#24 0x000000000049c2d9 in finish_loading (view=0xeb23f0) at nemo-view.c:10451
#25 0x00000000004d90a9 in ready_callback_call (callback=0xecaf60, 
    directory=0x7fffe800f730) at nemo-directory-async.c:1287
#26 call_ready_callbacks_at_idle (callback_data=<optimized out>)
    at nemo-directory-async.c:1857
#27 0x00007ffff503ace5 in g_main_dispatch (context=0x80d900)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3064
#28 g_main_context_dispatch (context=context@entry=0x80d900)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3663
#29 0x00007ffff503b048 in g_main_context_iterate (
    context=context@entry=0x80d900, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3734
#30 0x00007ffff503b0ec in g_main_context_iteration (context=0x80d900, 
    context@entry=0x0, may_block=may_block@entry=1)
    at /build/buildd/glib2.0-2.40.2/./glib/gmain.c:3795
---Type <return> to continue, or q <return> to quit---
#31 0x00007ffff55edb9c in g_application_run (application=0x7e3130, 
    argc=argc@entry=1, argv=argv@entry=0x7fffffffde58)
    at /build/buildd/glib2.0-2.40.2/./gio/gapplication.c:2115
#32 0x0000000000430dc6 in main (argc=1, argv=0x7fffffffde58) at nemo-main.c:106

```

**Comment by rpgdev** [comment]
I can confirm this happening to me. Not even killing the process works to make it start up again.

**Comment by rpgdev** [comment]
I've found that if you disconnect your devices from USB nemo responds again. In my case my phone.

**Comment by kentanilsson** [comment]
After laptop (Ubuntu 16.04) coming back from suspend state nemo (3.0.6) is always hanging IF there is a connection active to remote server. Force quit program , restart and unmount "server", then it works OK again.

**Comment by icarter09** [comment]
@kentanilsson are you still experiencing this issue on the latest version of nemo?
