### ISSUE TITLE
nemo-3.0.1 fails to build

### ISSUE THREAD

**Issue by leigh123linux** [linuxmint/nemo#1172]
I adjusted the build dependencies in my specfile to match the recent python3 changes

```
BuildRequires:  python3-polib
BuildRequires:  python3-gobject-base
```

I get this error when building

```
cd ../data && ./merge_action_strings && cd ../files && find -mindepth 1 -maxdepth 1 -type d -exec cp -R {} /home/leigh/development/rpmbuild/BUILDROOT/nemo-3.0.1-1.fc24.x86_64/ \;
merge_action_strings - Failed to load .mo file: /usr/share/locale/ar/LC_MESSAGES/nemo.mo
Traceback (most recent call last):
  File "./merge_action_strings", line 74, in <module>
    Main()
  File "./merge_action_strings", line 48, in __init__
    outfile.write(outstring)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe8' in position 331: ordinal not in range(128)
```

**Comment by mtwebster** [comment]
Does this fix it? 

```
diff --git a/data/merge_action_strings b/data/merge_action_strings
index fe17f9e..61c5ab3 100755
--- a/data/merge_action_strings
+++ b/data/merge_action_strings
@@ -3,6 +3,7 @@
 import os
 import glob
 import polib
+import codecs
 from gi.repository import GLib
 
 GROUP = "Nemo Action"
@@ -44,7 +45,7 @@ class Main:
             outstring, length = self.in_keyfiles[fn].to_data()
             if os.path.exists(action_path):
                 os.remove(action_path)
-            outfile = open(action_path, 'w')
+            outfile = codecs.open(action_path, 'w', 'utf-8')
             outfile.write(outstring)
             outfile.close()
```

**Comment by leigh123linux** [comment]
@mtwebster Yes it does , thank you for the fix.

**Comment by leigh123linux** [comment]
Fix in master

https://github.com/linuxmint/nemo/commit/3e8512d05205d69336527f8a72d20608b2566fee
