### ISSUE TITLE
 SIGSEGV in g_type_check_instance_is_fundamentally_a in glib2.0-2.48.1/./gobject/gtype.c:4034

### ISSUE THREAD

**Issue by fhimpe** [linuxmint/nemo#1182]
While I'm browsing my pictures directory's containing JPEG and NEF RAW images,
nemo 3.0.1 on Debian testing/sid will always crash after some time browsing around. This is a stack trace:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff50f480c in g_type_check_instance_is_fundamentally_a
(type_instance=type_instance@entry=0x7fffd4002b60,
fundamental_type=fundamental_type@entry=80) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gtype.c:4034
4034    /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gtype.c: No such file or
directory.
(gdb) thread apply all bt

Thread 26 (Thread 0x7fffe7fff700 (LWP 15058)):
#0  0x00007ffff4056ae9 in syscall () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4e3dd4a in g_cond_wait_until (cond=cond@entry=0x894c38,
mutex=mutex@entry=0x894c30, end_time=end_time@entry=1891790839) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthread-posix.c:1441
#2  0x00007ffff4dcd999 in g_async_queue_pop_intern_unlocked (queue=0x894c30,
wait=wait@entry=1, end_time=1891790839) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gasyncqueue.c:422
#3  0x00007ffff4dcdff8 in g_async_queue_timeout_pop_unlocked (queue=<optimized
out>, timeout=timeout@entry=500000) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gasyncqueue.c:570
#4  0x00007ffff4e20536 in g_thread_pool_thread_proxy (pool=0x896560) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthreadpool.c:262
#5  0x00007ffff4e20536 in g_thread_pool_thread_proxy (data=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthreadpool.c:296
#6  0x00007ffff4e1fbc5 in g_thread_proxy (data=0x7fffdc0154f0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthread.c:780
#7  0x00007ffff431d454 in start_thread () at /lib/x86_64-linux-
gnu/libpthread.so.0
#8  0x00007ffff405aeed in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffe77fe700 (LWP 15036)):
#0  0x00007ffff4051e5d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4df939c in g_main_context_iterate (priority=2147483647, n_fds=1,
fds=0x7fffd40010c0, timeout=<optimized out>, context=0x93ea80) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:4135
#2  0x00007ffff4df939c in g_main_context_iterate
(context=context@entry=0x93ea80, block=block@entry=1,
dispatch=dispatch@entry=1, self=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3835
#3  0x00007ffff4df94ac in g_main_context_iteration (context=0x93ea80,
may_block=1) at /build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3901
#4  0x00007fffec03a41d in  () at /usr/lib/x86_64-linux-
gnu/gio/modules/libdconfsettings.so
#5  0x00007ffff4e1fbc5 in g_thread_proxy (data=0x999800) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthread.c:780
#6  0x00007ffff431d454 in start_thread () at /lib/x86_64-linux-
gnu/libpthread.so.0
#7  0x00007ffff405aeed in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffeca40700 (LWP 15034)):
#0  0x00007ffff4051e5d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4df939c in g_main_context_iterate (priority=2147483647, n_fds=4,
fds=0x7fffe0004380, timeout=<optimized out>, context=0x895550) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:4135
#2  0x00007ffff4df939c in g_main_context_iterate (context=0x895550,
block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3835
#3  0x00007ffff4df9722 in g_main_loop_run (loop=0x8954e0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:4034
#4  0x00007ffff53f7916 in gdbus_shared_thread_func (user_data=0x895520) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gio/gdbusprivate.c:246
#5  0x00007ffff4e1fbc5 in g_thread_proxy (data=0x8324a0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthread.c:780
#6  0x00007ffff431d454 in start_thread () at /lib/x86_64-linux-
gnu/libpthread.so.0
#7  0x00007ffff405aeed in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7fffed241700 (LWP 15033)):
#0  0x00007ffff4051e5d in poll () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff4df939c in g_main_context_iterate (priority=2147483647, n_fds=2,
fds=0x7fffe80008c0, timeout=<optimized out>, context=0x894d40) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:4135
#2  0x00007ffff4df939c in g_main_context_iterate
(context=context@entry=0x894d40, block=block@entry=1,
dispatch=dispatch@entry=1, self=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3835
#3  0x00007ffff4df94ac in g_main_context_iteration (context=0x894d40,
may_block=may_block@entry=1) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3901
#4  0x00007ffff4df94e9 in glib_worker_main (data=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:5672
#5  0x00007ffff4e1fbc5 in g_thread_proxy (data=0x832450) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gthread.c:780
#6  0x00007ffff431d454 in start_thread () at /lib/x86_64-linux-
gnu/libpthread.so.0
#7  0x00007ffff405aeed in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff7f2aa40 (LWP 15029)):
#0  0x00007ffff50f480c in g_type_check_instance_is_fundamentally_a
(type_instance=type_instance@entry=0x7fffd4002b60,
fundamental_type=fundamental_type@entry=80) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gtype.c:4034
#1  0x00007ffff50d4c17 in g_object_unref (_object=0x7fffd4002b60) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gobject.c:3080
#2  0x00007ffff6a5f219 in gtk_button_destroy (widget=0x11d4340
[GtkToggleButton]) at /build/gtk+3.0-3.20.4/./gtk/gtkbutton.c:764
#6  0x00007ffff50eb08f in <emit signal ??? on instance 0x11d4340
[GtkToggleButton]> (instance=instance@entry=0x11d4340, signal_id=<optimized
out>, detail=detail@entry=0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:3441
    #3  0x00007ffff50cffa5 in g_closure_invoke (closure=closure@entry=0x843820,
return_value=return_value@entry=0x0, n_param_values=1,
param_values=param_values@entry=0x7fffffffdbe0,
invocation_hint=invocation_hint@entry=0x7fffffffdb60)
    at /build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gclosure.c:804
    #4  0x00007ffff50e24de in signal_emit_unlocked_R (node=node@entry=0x825a20,
detail=detail@entry=0, instance=instance@entry=0x11d4340,
emission_return=emission_return@entry=0x0,
instance_and_params=instance_and_params@entry=0x7fffffffdbe0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:3745
    #5  0x00007ffff50ead5c in g_signal_emit_valist (instance=<optimized out>,
signal_id=<optimized out>, detail=<optimized out>,
var_args=var_args@entry=0x7fffffffdd90) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gsignal.c:3385
#7  0x00007ffff6ca713a in gtk_widget_dispose (object=0x11d4340
[GtkToggleButton]) at /build/gtk+3.0-3.20.4/./gtk/gtkwidget.c:12030
#8  0x00007ffff50d4d25 in g_object_unref (_object=0x11d4340) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gobject/gobject.c:3146
#9  0x00007ffff6a991d8 in gtk_container_remove (container=0xb664c0
[NemoPathBar], widget=0x11d4340 [GtkToggleButton]) at
/build/gtk+3.0-3.20.4/./gtk/gtkcontainer.c:1909
#10 0x0000000000469efc in nemo_path_bar_update_path (path_bar=<optimized out>)
at nemo-pathbar.c:1410
#11 0x0000000000469efc in nemo_path_bar_update_path (path_bar=<optimized out>,
file_path=0x9f74c0, file_path@entry=0x557a78, emit_signal=1) at nemo-
pathbar.c:2080
#12 0x000000000046bd6b in nemo_path_bar_set_path (path_bar=<optimized out>,
file_path=0x557a78, file_path@entry=0x9f74c0) at nemo-pathbar.c:2127
#13 0x00000000004b5106 in nemo_window_pane_sync_location_widgets (pane=0xc7b9e0
[NemoWindowPane]) at nemo-window-pane.c:1063
#14 0x00000000004af964 in nemo_window_report_load_underway (slot=0xbfc3b0
[NemoWindowSlot]) at nemo-window-manage-views.c:1491
#15 0x00000000004af964 in nemo_window_report_load_underway (slot=0xbfc3b0
[NemoWindowSlot]) at nemo-window-manage-views.c:1231
#16 0x00000000004af964 in nemo_window_report_load_underway (window=<optimized
out>, view=<optimized out>) at nemo-window-manage-views.c:1091
#17 0x000000000049e4e8 in finish_loading (view=0x12b8e70 [NemoIconView]) at
nemo-view.c:10331
#18 0x00000000004d9235 in call_ready_callbacks_at_idle (callback=0x1374680,
directory=0xe42ed0 [NemoVFSDirectory]) at nemo-directory-async.c:1288
#19 0x00000000004d9235 in call_ready_callbacks_at_idle
(callback_data=<optimized out>) at nemo-directory-async.c:1858
#20 0x00007ffff4df905a in g_main_context_dispatch (context=0x7f42e0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3154
#21 0x00007ffff4df905a in g_main_context_dispatch
(context=context@entry=0x7f42e0) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3769
#22 0x00007ffff4df9400 in g_main_context_iterate
(context=context@entry=0x7f42e0, block=block@entry=1,
dispatch=dispatch@entry=1, self=<optimized out>) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3840
#23 0x00007ffff4df94ac in g_main_context_iteration
(context=context@entry=0x7f42e0, may_block=may_block@entry=1) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./glib/gmain.c:3901
#24 0x00007ffff53c0cdd in g_application_run (application=0x7fa130
[NemoApplication], argc=argc@entry=1, argv=argv@entry=0x7fffffffe2f8) at
/build/glib2.0-wnDt2X/glib2.0-2.48.1/./gio/gapplication.c:2381
#25 0x0000000000430134 in main (argc=1, argv=0x7fffffffe2f8) at nemo-main.c:106
```

Downstream Debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824881

**Comment by icarter09** [comment]
@fhimpe are you still experiencing this issue on the latest version of nemo?
