### ISSUE TITLE
Crash in gtk_widget_get_settings

### ISSUE THREAD

**Issue by pmts** [linuxmint/nemo#1239]
Nemo often crashes when simply browsing files. It brings down the whole cinnamon desktop (ie desktop icons disappear).

Gentoo Linux, Nemo 3.0.6, GTK+ 3.20.6

```
#0  0x00007fc236315e2e in gtk_widget_get_settings (widget=0x1abcbebcd8bcbebc) at /usr/src/debug/x11-libs/gtk+-3.20.6/gtk+-3.20.6/gtk/gtkwidget.c:11613
#1  0x00007fc236251a1b in indicator_start_fade (indicator=indicator@entry=0x142f688, target=target@entry=0) at /usr/src/debug/x11-libs/gtk+-3.20.6/gtk+-3.20.6/gtk/gtkscrolledwindow.c:4058
#2  0x00007fc236251b9c in indicator_start_fade (target=0, indicator=0x142f688) at /usr/src/debug/x11-libs/gtk+-3.20.6/gtk+-3.20.6/gtk/gtkscrolledwindow.c:4110
#3  maybe_hide_indicator (data=0x142f688, data@entry=<error reading variable: value has been optimized out>) at /usr/src/debug/x11-libs/gtk+-3.20.6/gtk+-3.20.6/gtk/gtkscrolledwindow.c:4107
#4  0x00007fc234403129 in g_timeout_dispatch (source=0x132de80, callback=<optimized out>, user_data=<optimized out>) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/glib/gmain.c:4577
#5  0x00007fc23440258a in g_main_dispatch (context=0xb16930) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/glib/gmain.c:3154
#6  g_main_context_dispatch (context=context@entry=0xb16930) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/glib/gmain.c:3769
#7  0x00007fc234402950 in g_main_context_iterate (context=context@entry=0xb16930, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/glib/gmain.c:3840
#8  0x00007fc2344029fc in g_main_context_iteration (context=context@entry=0xb16930, may_block=may_block@entry=1) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/glib/gmain.c:3901
#9  0x00007fc2349e668d in g_application_run (application=0xb1c130, argc=argc@entry=2, argv=argv@entry=0x7fff57312ec8) at /usr/src/debug/dev-libs/glib-2.48.1/glib-2.48.1/gio/gapplication.c:2381
#10 0x000000000043004f in main (argc=2, argv=0x7fff57312ec8) at nemo-main.c:106
```

**Comment by mtwebster** [comment]
Duplicate and workaround (disabling overlay scrollbars): https://github.com/linuxmint/nemo/issues/1227
