### ISSUE TITLE
Opening pdfs from desktop crashes nemo (with backtrace)

### ISSUE THREAD

**Issue by norbusan** [linuxmint/nemo#1290]
Dear all, 

I am running Debian/sid with nemo 3.0.6, and I can 100% reproduce a crashing nemo by trying to open a pdf from the Desktop by double clicking.

I get a core dump and the following backtrace:
`````
(gdb) bt
#0  0x00007fb19a26405c in g_slice_alloc ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fb19a28213e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fb19a27b4a5 in g_variant_new_variant ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fb19a2805a4 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fb19a28048b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fb19a280922 in g_variant_new_va ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fb19a280e4d in g_variant_builder_add ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fb19a8252cb in g_dbus_message_to_blob ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007fb19a819b6c in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x00007fb19a81afe6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#10 0x00007fb19a81dff3 in g_dbus_connection_send_message_with_reply ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#11 0x00007fb19a81e39a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#12 0x00007fb19a820b25 in g_dbus_connection_call ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#13 0x00007fb19a8288be in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#14 0x00007fb19a829718 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#15 0x00007fb19a7eb4f3 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#16 0x00007fb19a7ebba6 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#17 0x00007fb19a81e69a in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#18 0x00007fb19a7eb4f3 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#19 0x00007fb19a7eb529 in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x00007fb19a24654a in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007fb19a246900 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007fb19a246c22 in g_main_loop_run ()
---Type <return> to continue, or q <return> to quit---
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007fb19a829d9b in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#24 0x00007fb19a7c1b77 in g_initable_new_valist ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x00007fb19a7c1c26 in g_initable_new ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#26 0x00007fb191fd925e in gvfs_dbus_mount_tracker_proxy_new_for_bus_sync ()
   from /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so
#27 0x00007fb192202e61 in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
#28 0x00007fb192203f17 in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
#29 0x00007fb192208f6b in ?? ()
   from /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
#30 0x00000000004c958e in nemo_bookmark_uri_get_exists (
    bookmark=bookmark@entry=0x7fb1880019c0) at nemo-bookmark.c:769
#31 0x00000000004c99ae in nemo_bookmark_connect_file (bookmark=0x7fb1880019c0)
    at nemo-bookmark.c:341
#32 0x00000000004c9c0d in nemo_bookmark_connect_file (bookmark=0x7fb1880019c0)
    at nemo-bookmark.c:659
#33 nemo_bookmark_get_icon (bookmark=0x7fb1880019c0) at nemo-bookmark.c:656
#34 0x00000000004ad611 in nemo_menus_append_bookmark_to_menu (
    window=0x2203780, bookmark=bookmark@entry=0x7fb1880019c0, 
    parent_path=parent_path@entry=0x563aa8 "/MenuBar/Other Menus/Bookmarks/Bookmarks Placeholder", parent_id=parent_id@entry=0x563ba5 "dynamic", 
    index_in_parent=index_in_parent@entry=1, 
    action_group=action_group@entry=0x194d4a0, merge_id=13, 
    refresh_callback=0x4ad770 <refresh_bookmarks_menu>, 
    failed_callback=0x4ad0f0 <show_bogus_bookmark_window>)
    at nemo-window-bookmarks.c:304
#35 0x00000000004ad96f in update_bookmarks (window=0x2203780)
---Type <return> to continue, or q <return> to quit---
    at nemo-window-bookmarks.c:381
#36 refresh_bookmarks_menu (window=0x2203780) at nemo-window-bookmarks.c:400
#37 0x00000000004ada48 in nemo_window_initialize_bookmarks_menu (
    window=0x2203780) at nemo-window-bookmarks.c:414
#38 0x00000000004bf938 in nemo_window_constructed (self=<optimized out>)
    at nemo-window.c:672
#39 0x000000000044093b in nemo_desktop_window_constructed (obj=0x2203780)
    at nemo-desktop-window.c:82
#40 0x00007fb19a523787 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x00007fb19a52511e in g_object_new_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007fb19a5253c1 in g_object_new ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x0000000000440bdb in nemo_desktop_window_new (monitor=monitor@entry=0)
    at nemo-desktop-window.c:200
#44 0x000000000043f54f in create_new_desktop_window (
    manager=manager@entry=0x19002e0, monitor=monitor@entry=0, 
    primary=primary@entry=1, show_desktop=show_desktop@entry=1)
    at nemo-desktop-manager.c:62
#45 0x000000000043faab in layout_changed (manager=0x19002e0)
    at nemo-desktop-manager.c:125
#46 0x000000000043fdc5 in layout_changed (manager=0x19002e0)
    at nemo-desktop-manager.c:93
#47 gdk_filter_func (gdk_xevent=<optimized out>, event=<optimized out>, 
    data=<optimized out>) at nemo-desktop-manager.c:151
#48 0x00007fb19bb28111 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#49 0x00007fb19bb28449 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#50 0x00007fb19baef6d9 in gdk_display_get_event ()
   from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#51 0x00007fb19bb28182 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
---Type <return> to continue, or q <return> to quit---
#52 0x00007fb19a246697 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007fb19a246900 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007fb19a2469ac in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007fb19a80071d in g_application_run ()
   from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#56 0x0000000000430164 in main (argc=1, argv=0x7ffd81c8c9b8) at nemo-main.c:106
(gdb) quit
`````

It seems to be related to the bookmark code.

Is there anything known about this?

Thanks

Norbert

**Comment by mtwebster** [comment]
Is the pdf an actual pdf or is it a link to a file somewhere else (like a network location maybe?)

I can't reproduce this with a normal pdf file on my desktop.

**Comment by norbusan** [comment]
Hi,
thanks for coming back. Yes, that is an actual pdf that I copied to the desktop. But it is not only PDFs, it seems many programs that use Gtk3 on start make nemo crash. I regularly use IntelliJ, and starting it via a link from Desktop ends with a dead nemo.

I can rebuild the current Debian source, or use the current git again with debug symbols for further backtraces.

**Comment by norbusan** [comment]
Removing nitroshare-nemo finally fixed this problem for me, I am closing this issue.
