### ISSUE TITLE
Crash in gtk_widget_hide()/gtk_widget_show()

### ISSUE THREAD

**Issue by theHaeryOne** [linuxmint/nemo#1379]
When running Nemo 3.2.2-1 on Fedora 25 (Cinnamon) Nemo often crashes when moving files from one directory to another. This mainly happens when moving a large quantity of files, but also occasionally occurs when moving a single .jpg image.

Not sure what logs would be useful here, please let me know and I will upload them for the time of a crash. This fault is definitely intermittent and only occurs on about 1 in 20 move operations so is quite difficult to reproduce. As far as I can tell this never happens with a straight copy operation.

**Comment by blutch112** [comment]
Hello, I have the same problem on Archlinux and Nemo 3.2.2. The crash is very random, with a simple drag / drop between two Nemo windows on a network drive.
Here is the log of journalctl:

```
kernel: nemo[817]: segfault at bc10030054 ip 00007fca70c281fb sp 00007ffe9a76a840 error 4 in libgtk-3.so.0
janv. 05 16:22:59 xps13-archlinux systemd[1]: Created slice system-systemd\x2dcoredump.slice.
janv. 05 16:22:59 xps13-archlinux systemd[1]: Started Process Core Dump (PID 3432/UID 0).
janv. 05 16:23:00 xps13-archlinux systemd-coredump[3433]: Process 817 (nemo) of user 1000 dumped core.
                                                          
Stack trace of thread 817:
#0  0x00007fca70c281fb gtk_widget_hide (libgtk-3.so.0)
#1  0x00000000004b0e09 n/a (nemo)
#2  0x000000000049fa58 n/a (nemo)
#3  0x00000000004da096 n/a (nemo)
#4  0x00007fca6ed1943a g_main_context_dispatch (libglib-2.0.so.0)
#5  0x00007fca6ed197f0 n/a (libglib-2.0.so.0)
#6  0x00007fca6ed1989c g_main_context_iteration (libglib-2.0.so.0)
#7  0x00007fca6f2d354d g_application_run (libgio-2.0.so.0)
#8  0x00000000004306e9 n/a (nemo)
#9  0x00007fca6deb5291 __libc_start_main (libc.so.6)
#10 0x000000000043074a n/a (nemo)
                                                          
Stack trace of thread 834:
#0  0x00007fca6df7448d poll (libc.so.6)
#1  0x00007fca6ed19786 n/a (libglib-2.0.so.0)
#2  0x00007fca6ed1989c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fca620b04bd n/a (libdconfsettings.so)
#4  0x00007fca6ed410d5 n/a (libglib-2.0.so.0)
#5  0x00007fca6e23a454 start_thread (libpthread.so.0)
#6  0x00007fca6df7d7df __clone (libc.so.6)
                                                          
Stack trace of thread 828:
#0  0x00007fca6df7448d poll (libc.so.6)
#1  0x00007fca6ed19786 n/a (libglib-2.0.so.0)
#2  0x00007fca6ed1989c g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fca6ed198e1 n/a (libglib-2.0.so.0)
#4  0x00007fca6ed410d5 n/a (libglib-2.0.so.0)
#5  0x00007fca6e23a454 start_thread (libpthread.so.0)
#6  0x00007fca6df7d7df __clone (libc.so.6)
                                                          
Stack trace of thread 3425:
#0  0x00007fca6df78f19 syscall (libc.so.6)
#1  0x00007fca6ed5f03a g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fca6ecede89 n/a (libglib-2.0.so.0)
#3  0x00007fca6ecee4ac g_async_queue_timeout_pop (libglib-2.0.so.0)
#4  0x00007fca6ed41b9d n/a (libglib-2.0.so.0)
#5  0x00007fca6ed410d5 n/a (libglib-2.0.so.0)
#6  0x00007fca6e23a454 start_thread (libpthread.so.0)
#7  0x00007fca6df7d7df __clone (libc.so.6)
                                                          
Stack trace of thread 829:
#0  0x00007fca6df7448d poll (libc.so.6)
#1  0x00007fca6ed19786 n/a (libglib-2.0.so.0)
#2  0x00007fca6ed19b12 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fca6f2ff316 n/a (libgio-2.0.so.0)
#4  0x00007fca6ed410d5 n/a (libglib-2.0.so.0)
#5  0x00007fca6e23a454 start_thread (libpthread.so.0)
#6  0x00007fca6df7d7df __clone (libc.so.6)
```

**Comment by pierre-guillot** [comment]
Same problem with Cinnamon 3.2.7 and nemo 3.2.2 on Archlinx, i have only tasks bar and wallpapre. Juste need to click on namo shortcut :

janv. 05 15:48:06 Claire-Arch systemd-coredump[10357]: Process 2427 (nemo) of user 1000 dumped core.
                                                       
                                                       Stack trace of thread 2427:
                                                       #0  0x00007fd19e98818b gtk_widget_hide (libgtk-3.so.0)
                                                       #1  0x00000000004b0e09 n/a (nemo)
                                                       #2  0x000000000049fa58 n/a (nemo)
                                                       #3  0x00000000004da0c5 n/a (nemo)
                                                       #4  0x00007fd19ca7943a g_main_context_dispatch (libglib-2.0.
                                                       #5  0x00007fd19ca797f0 n/a (libglib-2.0.so.0)
                                                       #6  0x00007fd19ca7989c g_main_context_iteration (libglib-2.0
                                                       #7  0x00007fd19d03354d g_application_run (libgio-2.0.so.0)
                                                       #8  0x00000000004306e9 n/a (nemo)
                                                       #9  0x00007fd19bc15291 __libc_start_main (libc.so.6)
                                                       #10 0x000000000043074a n/a (nemo)
                                                       
                                                       Stack trace of thread 2433:
                                                       #0  0x00007fd19bcd448d poll (libc.so.6)
                                                       #1  0x00007fd19ca79786 n/a (libglib-2.0.so.0)
                                                       #2  0x00007fd19ca7989c g_main_context_iteration (libglib-2.0
                                                       #3  0x00007fd183dfa4bd n/a (libdconfsettings.so)
                                                       #4  0x00007fd19caa10d5 n/a (libglib-2.0.so.0)
                                                       #5  0x00007fd19bf9a454 start_thread (libpthread.so.0)
                                                       #6  0x00007fd19bcdd7df __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 2430:
                                                       #0  0x00007fd19bcd448d poll (libc.so.6)
                                                       #1  0x00007fd19ca79786 n/a (libglib-2.0.so.0)
                                                       #2  0x00007fd19ca7989c g_main_context_iteration (libglib-2.0
                                                       #3  0x00007fd19ca798e1 n/a (libglib-2.0.so.0)
                                                       #4  0x00007fd19caa10d5 n/a (libglib-2.0.so.0)
                                                       #5  0x00007fd19bf9a454 start_thread (libpthread.so.0)
                                                       #6  0x00007fd19bcdd7df __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 2431:
                                                       #0  0x00007fd19bcd448d poll (libc.so.6)
                                                       #1  0x00007fd19ca79786 n/a (libglib-2.0.so.0)
                                                       #2  0x00007fd19ca79b12 g_main_loop_run (libglib-2.0.so.0)
                                                       #3  0x00007fd19d05f316 n/a (libgio-2.0.so.0)
                                                       #4  0x00007fd19caa10d5 n/a (libglib-2.0.so.0)
                                                       #5  0x00007fd19bf9a454 start_thread (libpthread.so.0)
                                                       #6  0x00007fd19bcdd7df __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 10347:
                                                       #0  0x00007fd19bcd8f19 syscall (libc.so.6)
                                                       #1  0x00007fd19cabf03a g_cond_wait_until (libglib-2.0.so.0)
                                                       #2  0x00007fd19ca4de89 n/a (libglib-2.0.so.0)
                                                       #3  0x00007fd19caa1aa6 n/a (libglib-2.0.so.0)
                                                       #4  0x00007fd19caa10d5 n/a (libglib-2.0.so.0)
                                                       #5  0x00007fd19bf9a454 start_thread (libpthread.so.0)
                                                       #6  0x00007fd19bcdd7df __clone (libc.so.6)

**Comment by leigh123linux** [comment]
Edit: removed pointless backtraces, they are totally useless with the required debugging symbols.

**Comment by leigh123linux** [comment]
And https://bugzilla.redhat.com/show_bug.cgi?id=1405803

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5e88e39e7b in gtk_widget_hide (widget=0x55c2a6a434f0) at gtkwidget.c:4867
4867	  g_return_if_fail (GTK_IS_WIDGET (widget));
[Current thread is 1 (Thread 0x7f5e8a638ac0 (LWP 1529))]

Thread 5 (Thread 0x7f5e75342700 (LWP 1540)):
#0  0x00007f5e85f5c00d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007f5e86f39156 in g_main_context_poll (priority=<optimized out>, n_fds=4, fds=0x7f5e68006660, timeout=<optimized out>, context=0x55c2a5cae790) at gmain.c:4228
        poll_func = 0x7f5e86f49000 <g_poll>
#2  g_main_context_iterate (context=0x55c2a5cae790, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3924
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 4
        allocated_nfds = 4
        fds = 0x7f5e68006660
#3  0x00007f5e86f394e2 in g_main_loop_run (loop=0x55c2a5cacf50) at gmain.c:4125
        __func__ = "g_main_loop_run"
#4  0x00007f5e8751d946 in gdbus_shared_thread_func (user_data=0x55c2a5cad460) at gdbusprivate.c:247
        data = 0x55c2a5cad460
#5  0x00007f5e86f60b03 in g_thread_proxy (data=0x55c2a5c54d90) at gthread.c:784
        thread = 0x55c2a5c54d90
        __func__ = "g_thread_proxy"
#6  0x00007f5e8622d6ca in start_thread (arg=0x7f5e75342700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f5e75342700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140043670005504, 1599121263346065702, 0, 140737091590943, 140043670006208, 140043670005504, -1689463142104162010, -1689918496787521242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f5e85f67f6f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.

Thread 4 (Thread 0x7f5e75b43700 (LWP 1539)):
#0  0x00007f5e85f5c00d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007f5e86f39156 in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7f5e700008c0, timeout=<optimized out>, context=0x55c2a5ca33d0) at gmain.c:4228
        poll_func = 0x7f5e86f49000 <g_poll>
#2  g_main_context_iterate (context=context@entry=0x55c2a5ca33d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3924
        max_priority = 2147483647
        timeout = 3998
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = 2
        fds = 0x7f5e700008c0
#3  0x00007f5e86f3926c in g_main_context_iteration (context=0x55c2a5ca33d0, may_block=may_block@entry=1) at gmain.c:3990
        retval = <optimized out>
#4  0x00007f5e86f392b1 in glib_worker_main (data=<optimized out>) at gmain.c:5783
No locals.
#5  0x00007f5e86f60b03 in g_thread_proxy (data=0x55c2a5c54d40) at gthread.c:784
        thread = 0x55c2a5c54d40
        __func__ = "g_thread_proxy"
#6  0x00007f5e8622d6ca in start_thread (arg=0x7f5e75b43700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f5e75b43700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140043678398208, 1599121263346065702, 0, 140737091590591, 140043678398912, 140043678398208, -1689462042055663322, -1689918496787521242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f5e85f67f6f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.

Thread 3 (Thread 0x7f5e55c4a700 (LWP 5432)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f5e86f7ea7a in g_cond_wait_until (cond=cond@entry=0x55c2a5ca32e8, mutex=mutex@entry=0x55c2a5ca32e0, end_time=end_time@entry=3854379058) at gthread-posix.c:1442
        now = {tv_sec = 3839, tv_nsec = 379058525}
        span = {tv_sec = 14, tv_nsec = 999999475}
        sampled = 497
        res = <optimized out>
#2  0x00007f5e86f0d8c9 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0x55c2a5ca32e0, wait=wait@entry=1, end_time=end_time@entry=3854379058) at gasyncqueue.c:422
        retval = <optimized out>
        __func__ = "g_async_queue_pop_intern_unlocked"
#3  0x00007f5e86f0deec in g_async_queue_timeout_pop (queue=0x55c2a5ca32e0, timeout=timeout@entry=15000000) at gasyncqueue.c:543
        end_time = 3854379058
        retval = <optimized out>
#4  0x00007f5e86f615cd in g_thread_pool_wait_for_new_pool () at gthreadpool.c:167
        pool = <optimized out>
        local_wakeup_thread_serial = <optimized out>
        last_wakeup_thread_serial = <optimized out>
        have_relayed_thread_marker = <optimized out>
#5  g_thread_pool_thread_proxy (data=<optimized out>) at gthreadpool.c:364
        free_pool = <optimized out>
        pool = <optimized out>
#6  0x00007f5e86f60b03 in g_thread_proxy (data=0x7f5e58000c50) at gthread.c:784
        thread = 0x7f5e58000c50
        __func__ = "g_thread_proxy"
#7  0x00007f5e8622d6ca in start_thread (arg=0x7f5e55c4a700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f5e55c4a700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140043142604544, 1599121263346065702, 0, 140737091595711, 140043142605248, 140043142604544, -1689531728436911834, -1689918496787521242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#8  0x00007f5e85f67f6f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.

Thread 2 (Thread 0x7f5e67fff700 (LWP 1593)):
#0  0x00007f5e85f5c00d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007f5e86f39156 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7f5e600010c0, timeout=<optimized out>, context=0x55c2a5ccae10) at gmain.c:4228
        poll_func = 0x7f5e86f49000 <g_poll>
#2  g_main_context_iterate (context=context@entry=0x55c2a5ccae10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3924
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = 1
        fds = 0x7f5e600010c0
#3  0x00007f5e86f3926c in g_main_context_iteration (context=context@entry=0x55c2a5ccae10, may_block=may_block@entry=1) at gmain.c:3990
        retval = <optimized out>
#4  0x00007f5e7413afad in dconf_gdbus_worker_thread (user_data=0x55c2a5ccae10) at dconf-gdbus-thread.c:82
        context = 0x55c2a5ccae10
#5  0x00007f5e86f60b03 in g_thread_proxy (data=0x55c2a5cc6b70) at gthread.c:784
        thread = 0x55c2a5cc6b70
        __func__ = "g_thread_proxy"
#6  0x00007f5e8622d6ca in start_thread (arg=0x7f5e67fff700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7f5e67fff700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140043448481536, 1599121263346065702, 0, 140737091593263, 140043448482240, 140043448481536, -1689421954978406106, -1689918496787521242}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x00007f5e85f67f6f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.

Thread 1 (Thread 0x7f5e8a638ac0 (LWP 1529)):
#0  0x00007f5e88e39e7b in gtk_widget_hide (widget=0x55c2a6a434f0) at gtkwidget.c:4867
        __inst = 0x55c2a6a434f0
        __t = 94294493069680
        __r = <optimized out>
#1  0x000055c2a4b25569 in update_for_new_location (slot=0x55c2a63aaaf0) at nemo-window-manage-views.c:1462
        window = 0x55c2a5e48bb0
        new_location = <optimized out>
        file = <optimized out>
        directory = 0x55c2a69e94b0
        data = <optimized out>
        location_really_changed = <optimized out>
#2  location_has_really_changed (slot=0x55c2a63aaaf0) at nemo-window-manage-views.c:1231
        window = 0x55c2a5e48bb0
        widget = <optimized out>
        location_copy = <optimized out>
#3  nemo_window_report_load_underway (window=<optimized out>, view=<optimized out>) at nemo-window-manage-views.c:1091
        slot = 0x55c2a63aaaf0
        __func__ = "nemo_window_report_load_underway"
#4  0x000055c2a4b16db8 in finish_loading (view=0x55c2a695d240) at nemo-view.c:10339
        attributes = <optimized out>
#5  0x000055c2a4b41013 in ready_callback_call (directory=0x55c2a69e94b0, callback=<optimized out>) at nemo-directory-async.c:1253
        file_list = 0x0
        callback = <optimized out>
        directory = 0x55c2a69e94b0
#6  0x000055c2a4b46733 in call_ready_callbacks_at_idle (callback_data=callback_data@entry=0x55c2a69e94b0) at nemo-directory-async.c:1790
        directory = 0x55c2a69e94b0
        node = <optimized out>
        next = <optimized out>
        callback = 0x55c2a65d0fc0
#7  0x00007f5e86f358e7 in g_idle_dispatch (source=0x55c2a6b8e2a0, callback=0x55c2a4b46690 <call_ready_callbacks_at_idle>, user_data=0x55c2a69e94b0) at gmain.c:5545
        again = <optimized out>
#8  0x00007f5e86f38e42 in g_main_dispatch (context=0x55c2a5c33ca0) at gmain.c:3203
        dispatch = 0x7f5e86f358d0 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x55c2a69e94b0
        callback = 0x55c2a4b46690 <call_ready_callbacks_at_idle>
        cb_funcs = 0x7f5e87200280 <g_source_callback_funcs>
        cb_data = 0x55c2a68ddd70
        need_destroy = <optimized out>
        source = 0x55c2a6b8e2a0
        current = 0x55c2a5c7fb70
        i = 1
#9  g_main_context_dispatch (context=context@entry=0x55c2a5c33ca0) at gmain.c:3856
No locals.
#10 0x00007f5e86f391c0 in g_main_context_iterate (context=context@entry=0x55c2a5c33ca0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3929
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = 3
        allocated_nfds = 3
        fds = <optimized out>
#11 0x00007f5e86f3926c in g_main_context_iteration (context=context@entry=0x55c2a5c33ca0, may_block=may_block@entry=1) at gmain.c:3990
        retval = <optimized out>
#12 0x00007f5e874f1bbd in g_application_run (application=0x55c2a5c3a130, argc=2, argv=0x7fffe859f2d8) at gapplication.c:2381
        arguments = 0x55c2a5c144c0
        status = 0
        context = 0x55c2a5c33ca0
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#13 0x000055c2a4abedcb in main (argc=2, argv=0x7fffe859f2d8) at nemo-main.c:104
        retval = <optimized out>
        application = 0x55c2a5c3a130
```

**Comment by theHaeryOne** [comment]
Update to say that this is now sometimes happening when simply opening a folder to view the files within. Doing any kind of file management is now almost unusable with Nemo.

**Comment by theHaeryOne** [comment]
Crash still present on Nemo 3.2.2-4. Nemo sometimes fails on opening folders and all icons disappear from the desktop (nemo can be manually restarted).

**Comment by pols12** [comment]
It seems to displays the message when cutting from a tab then pasting in an other tab.
Then, if you keep only one tab, it will not crash, but if you browse folders in both tabs, it will crash.

**Comment by icarter09** [comment]
Nemo 4.6.5
Mint 20 64bit

I haven't experienced this issue, but I'm not using the OS's listed on some of the comments. Can anyone on this ticket provide an update if they are still experiencing this issue? Thanks.

**Comment by NicolasGoeddel** [comment]
I have actually stopped using nemo because of this issue. I don't know if the issue still exists on Ubuntu 20.04. But if nobody changed anything then I guess the issue is still there.
