### ISSUE TITLE
Desktop hotkey bug

### ISSUE THREAD

**Issue by nerox8664** [linuxmint/nemo#1532]
The desktop icons disappear after multiple `Ctrl + n` hotkey pressing.

Software versions:
 * Cinnamon 3.4.2
 * Nemo 3.4.4

**Comment by leigh123linux** [comment]
Backtrace for issue

```
ERROR:nemo-window.c:1842:nemo_window_get_active_slot: assertion failed: (NEMO_IS_WINDOW (window))

Thread 1 "nemo-desktop" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	}
(gdb) bt
#0  0x00007ffff36ef64b in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff36f1450 in __GI_abort () at abort.c:89
#2  0x00007ffff463470d in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x555555691638 "nemo-window.c", line=line@entry=1842, func=func@entry=0x555555691a80 <__func__.61613> "nemo_window_get_active_slot", message=message@entry=0x5555568514b0 "assertion failed: (NEMO_IS_WINDOW (window))") at gtestutils.c:2433
#3  0x00007ffff463479a in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x555555691638 "nemo-window.c", line=line@entry=1842, func=func@entry=0x555555691a80 <__func__.61613> "nemo_window_get_active_slot", expr=expr@entry=0x55555568ee76 "NEMO_IS_WINDOW (window)") at gtestutils.c:2456
#4  0x0000555555600af1 in nemo_window_get_active_slot (window=0x0) at nemo-window.c:1842
#5  0x00005555555f8681 in action_new_window_callback (action=<optimized out>, user_data=<optimized out>) at nemo-window-menus.c:772
#9  0x00007ffff4901b0f in <emit signal ??? on instance 0x5555559c8880 [GtkAction]> (instance=instance@entry=0x5555559c8880, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
    #6  0x00007ffff48e630d in g_closure_invoke (closure=0x55555621a970, return_value=0x0, n_param_values=1, param_values=0x7fffffffce50, invocation_hint=0x7fffffffcdd0) at gclosure.c:804
    #7  0x00007ffff48f898e in signal_emit_unlocked_R (node=node@entry=0x5555559c0ae0, detail=detail@entry=0, instance=instance@entry=0x5555559c8880, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffce50) at gsignal.c:3635
    #8  0x00007ffff49011a5 in g_signal_emit_valist (instance=0x5555559c8880, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd020)
    at gsignal.c:3391
#10 0x00007ffff623af00 in _gtk_action_emit_activate (action=0x5555559c8880 [GtkAction]) at deprecated/gtkaction.c:909
#11 0x00007ffff623b489 in closure_accel_activate (closure=0x55555621a780, return_value=0x7fffffffd2a0, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=<optimized out>) at deprecated/gtkaction.c:1865
#15 0x00007ffff4901b0f in <emit signal accel-activate:<Primary>n on instance 0x5555562015e0 [GtkAccelGroup]> (instance=instance@entry=0x5555562015e0, signal_id=<optimized out>, detail=detail@entry=2198) at gsignal.c:3447
    #12 0x00007ffff48e630d in g_closure_invoke (closure=0x55555621a780, return_value=0x7fffffffd2a0, n_param_values=4, param_values=0x7fffffffd300, invocation_hint=0x7fffffffd280) at gclosure.c:804
---Type <return> to continue, or q <return> to quit---
    #13 0x00007ffff48f898e in signal_emit_unlocked_R (node=node@entry=0x5555562008c0, detail=detail@entry=2198, instance=instance@entry=0x5555562015e0, emission_return=emission_return@entry=0x7fffffffd460, instance_and_params=instance_and_params@entry=0x7fffffffd300) at gsignal.c:3635
    #14 0x00007ffff4900b3f in g_signal_emit_valist (instance=0x5555562015e0, signal_id=<optimized out>, detail=2198, var_args=var_args@entry=0x7fffffffd510)
    at gsignal.c:3401
#16 0x00007ffff62925a8 in gtk_accel_group_activate (accel_group=0x5555562015e0 [GtkAccelGroup], accel_quark=accel_quark@entry=2198, acceleratable=acceleratable@entry=0x5555561f1240 [NemoDesktopWindow], accel_key=accel_key@entry=110, accel_mods=accel_mods@entry=GDK_CONTROL_MASK) at gtkaccelgroup.c:910
#17 0x00007ffff6293e0d in gtk_accel_groups_activate (object=object@entry=0x5555561f1240 [NemoDesktopWindow], accel_key=110, accel_mods=GDK_CONTROL_MASK)
    at gtkaccelgroup.c:948
#18 0x00007ffff6531ce9 in gtk_window_activate_key (window=window@entry=0x5555561f1240 [NemoDesktopWindow], event=event@entry=0x5555561c7670) at gtkwindow.c:11784
#19 0x00007ffff6531f11 in gtk_window_key_press_event (widget=0x5555561f1240 [NemoDesktopWindow], event=0x5555561c7670) at gtkwindow.c:8008
#20 0x00007ffff63c2f77 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x555555962200, return_value=0x7fffffffd8c0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555962230) at gtkmarshalers.c:143
#21 0x00007ffff48e6546 in _g_closure_invoke_va (closure=0x555555962200, return_value=0x7fffffffd8c0, instance=0x5555561f1240, args=0x7fffffffd990, n_params=1, param_types=0x555555962230) at gclosure.c:867
#22 0x00007ffff4900e69 in g_signal_emit_valist (instance=0x5555561f1240, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd990)
    at gsignal.c:3300
#23 0x00007ffff4901b0f in g_signal_emit (instance=instance@entry=0x5555561f1240, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
#24 0x00007ffff650ddc4 in gtk_widget_event_internal (widget=0x5555561f1240 [NemoDesktopWindow], event=0x5555561c7670) at gtkwidget.c:7723
#25 0x00007ffff63bff5f in propagate_event (widget=0x5555561f1240 [NemoDesktopWindow], event=0x5555561c7670, captured=<optimized out>, topmost=0x0) at gtkmain.c:2661
#26 0x00007ffff63c1f80 in gtk_main_do_event (event=<optimized out>) at gtkmain.c:1901
#27 0x00007ffff5ed6465 in _gdk_event_emit (event=event@entry=0x5555561c7670) at gdkevents.c:73
#28 0x00007ffff5f07772 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
#29 0x00007ffff460e247 in g_main_dispatch (context=0x55555592c2f0) at gmain.c:3234
#30 0x00007ffff460e247 in g_main_context_dispatch (context=context@entry=0x55555592c2f0) at gmain.c:3899
#31 0x00007ffff460e5e8 in g_main_context_iterate (context=context@entry=0x55555592c2f0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at gmain.c:3972
#32 0x00007ffff460e67c in g_main_context_iteration (context=context@entry=0x55555592c2f0, may_block=may_block@entry=1) at gmain.c:4033
#33 0x00007ffff4bc7ebd in g_application_run (application=0x5555559321c0 [NemoDesktopApplication], argc=<optimized out>, argv=<optimized out>) at gapplication.c:2381
#34 0x0000555555586f5e in main (argc=1, argv=0x7fffffffde08) at nemo-desktop-main.c:101
```
