### ISSUE TITLE
Segfault in nemo after high CPU load while initializing

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/nemo#1605]
```
 * 3.4.6
 * Desktop
 * Ubuntu 17.04 (glebihan's nightlies)
 * Quadro K620M - Nouveau
 * 64 bit
 ```

**Issue**
For some days now, nemo-desktop has failed to load, seeming to start up, peg a full core, and then dying (and having apport peg a full core for quite a while).

Tried running from a terminal today, and got the following:

```
smo@dell-smo:~$ nemo-desktop 

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:115:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:116:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:145:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:146:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:166:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(nemo-desktop:15190): Gtk-WARNING **: Theme parsing error: gtk.css:187:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
Initializing nemo-pastebin extension...
2017-09-20 12:17:25,907 [DEBUG] nemo-pastebin(56): Initializing nemo-pastebin extension...
Initializing nemo-dropbox 3.4.0
Segmentation fault (core dumped)
```

**Steps to reproduce**
Run `nemo-desktop`, whether automatically at login, or manually from a terminal.

**Expected behaviour**
Desktop with icons and such handled by `nemo`

**Other information**
Seen across one workstation and 3 laptops.

Do note that there is a long delay between `Initializing nemo-dropbox 3.4.0` and the segfault, but whether it is nemo-dropbox that fails, or whatever it would attempt to load next, I cannot say.

More than willing to try out patches and such to get this resolved.

**Comment by Fjodor42** [comment]
I just realised that this happens *only* when using the SDDM Display Manager, not with e.g. LightDM.

Whether a fault of Nemo or SDDM, I cannot really say, but I would appreciate if we can keep this open here, from where I can link to it at the SDDM GitHub Issue tracker.

**Comment by mtwebster** [comment]
I did just make a bunch of changes to nemo and cinnamon regarding how they interact at startup.  However, nemo should run fine no matter what, so thanks for reporting this.

Is this a cinnamon session?  Or other desktop?

Can you run:
`env | grep -rni cinnamon` and post the result please.

Then if you can, get me a trace:
```
sudo apt-get install cinnamon-dbg       ### or gnome-dbg and nemo-dbg if you prefer
sudo apt-get install gdb                ### if this isn't already installed

gdb nemo-desktop
...
> run
# starts up... then segfaults...
> thread apply all bt                   ### paste the output of this
> q
```

I'll try out sddm when I get a chance.

**Comment by Fjodor42** [comment]
grep -rni didn't terminate, but here it is, without the -r:

```
smo@dell-smo:~$ env | grep -ni cinnamon
29:MANDATORY_PATH=/usr/share/gconf//usr/share/xsessions/cinnamon.mandatory.path
34:DESKTOP_SESSION=/usr/share/xsessions/cinnamon
37:DEFAULTS_PATH=/usr/share/gconf//usr/share/xsessions/cinnamon.default.path
47:XDG_DATA_DIRS=/usr/share//usr/share/xsessions/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
64:XDG_CURRENT_DESKTOP=X-Cinnamon
80:XDG_CONFIG_DIRS=/etc/xdg/xdg-/usr/share/xsessions/cinnamon:/etc/xdg
83:CINNAMON_VERSION=3.4.6
```
Trace coming later

**Comment by Fjodor42** [comment]
```
smo@dell-smo:~$ gdb nemo-desktop 
GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1.1) 7.12.50.20170314-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from nemo-desktop...Reading symbols from /usr/lib/debug//usr/bin/nemo-desktop...done.
done.
(gdb) run
Starting program: /usr/bin/nemo-desktop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe807c700 (LWP 21769)]
[New Thread 0x7fffe787b700 (LWP 21770)]
[New Thread 0x7fffe707a700 (LWP 21771)]
[New Thread 0x7fffe6879700 (LWP 21772)]
Initializing nemo-pastebin extension...
2017-09-27 11:48:59,785 [DEBUG] nemo-pastebin(56): Initializing nemo-pastebin extension...
Initializing nemo-dropbox 3.4.0
[New Thread 0x7fffcb07f700 (LWP 21774)]
[New Thread 0x7fffca067700 (LWP 21776)]
[Thread 0x7fffca067700 (LWP 21776) exited]
[Thread 0x7fffe6879700 (LWP 21772) exited]

Thread 1 "nemo-desktop" received signal SIGSEGV, Segmentation fault.
0x00007ffff4ba3ea8 in g_slice_alloc ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) thread apply all bt

Thread 6 (Thread 0x7fffcb07f700 (LWP 21774)):
#0  0x00007ffff3d549f9 in syscall ()
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007ffff4bcc15a in g_cond_wait_until ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b5a8d9 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4b5af99 in g_async_queue_timed_pop ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fffcb0867e3 in  ()
    at /usr/lib/nemo/extensions-3.0/libnemo-dropbox.so
#5  0x00007ffff4badf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff40206da in start_thread (arg=0x7fffcb07f700)
    at pthread_create.c:456
#7  0x00007ffff3d5ad7f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 4 (Thread 0x7fffe707a700 (LWP 21771)):
#0  0x00007ffff3d4ed8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4b86576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b8668c in g_main_context_iteration ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fffe82a146d in  ()
---Type <return> to continue, or q <return> to quit---
   ettings.so
#4  0x00007ffff4badf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff40206da in start_thread (arg=0x7fffe707a700) at pthread_create.c:456
#6  0x00007ffff3d5ad7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 3 (Thread 0x7fffe787b700 (LWP 21770)):
#0  0x00007ffff3d4ed8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4b86576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b86902 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff516d476 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007ffff4badf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff40206da in start_thread (arg=0x7fffe787b700) at pthread_create.c:456
#6  0x00007ffff3d5ad7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 2 (Thread 0x7fffe807c700 (LWP 21769)):
#0  0x00007ffff3d4ed8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff4b86576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4b8668c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff4b866d1 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff4badf65 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff40206da in start_thread (arg=0x7fffe807c700) at pthread_create.c:456
#6  0x00007ffff3d5ad7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105

Thread 1 (Thread 0x7ffff7f03f80 (LWP 21764)):
#0  0x00007ffff4ba3ea8 in g_slice_alloc () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff4ba44fe in g_slice_alloc0 () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff4e63a47 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007ffff4e63b04 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff4e82fdf in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff6890311 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff69e79ce in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff69e7ec5 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff6a95d49 in gtk_widget_get_style_context () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6a340ea in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff6a35666 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#24 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00005555555da328 in nemo_toolbar_constructed (obj=<optimized out>) at nemo-toolbar.c:294
#27 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#28 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00005555555db02e in nemo_toolbar_new (action_group=<optimized out>) at nemo-toolbar.c:576
#31 0x00005555555fcec8 in nemo_window_pane_constructed (obj=<optimized out>) at nemo-window-pane.c:850
#32 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00005555555fd380 in nemo_window_pane_new (window=<optimized out>) at nemo-window-pane.c:996
#36 0x00005555556038bd in nemo_window_constructed (self=<optimized out>) at nemo-window.c:630
#37 0x0000555555598874 in nemo_desktop_window_constructed (obj=0x555615fac000) at nemo-desktop-window.c:99
#38 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#41 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#42 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615ee9c70, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#43 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615ee9c70) at nemo-desktop-manager.c:365
#44 0x000055555559743c in on_run_state_changed (manager=0x555615ee9c70) at nemo-desktop-manager.c:446
#45 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#48 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#49 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#50 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615edd200) at nemo-desktop-window.c:351
#51 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#52 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#53 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#54 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#55 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#56 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615e15ce0, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#57 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615e15ce0) at nemo-desktop-manager.c:365
#58 0x000055555559743c in on_run_state_changed (manager=0x555615e15ce0) at nemo-desktop-manager.c:446
#59 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#60 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#61 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#62 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#63 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#64 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615e08150) at nemo-desktop-window.c:351
#65 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#66 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#67 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#68 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#69 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
---Type <return> to continue, or q <return> to quit---
#70 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615d3eda0, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#71 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615d3eda0) at nemo-desktop-manager.c:365
#72 0x000055555559743c in on_run_state_changed (manager=0x555615d3eda0) at nemo-desktop-manager.c:446
#73 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#74 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#75 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#76 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#77 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#78 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615d31d80) at nemo-desktop-window.c:351
#79 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#80 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#81 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#82 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#83 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#84 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615c6ae60, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#85 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615c6ae60) at nemo-desktop-manager.c:365
#86 0x000055555559743c in on_run_state_changed (manager=0x555615c6ae60) at nemo-desktop-manager.c:446
#87 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#88 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#89 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#90 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#91 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#92 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615c5ede0) at nemo-desktop-window.c:351
#93 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#94 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#95 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#96 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#97 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#98 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615b9e680, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#99 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615b9e680) at nemo-desktop-manager.c:365
#100 0x000055555559743c in on_run_state_changed (manager=0x555615b9e680) at nemo-desktop-manager.c:446
#101 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#102 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#103 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#104 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#105 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#106 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615b8f090) at nemo-desktop-window.c:351
#107 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#108 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#109 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#110 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#111 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#112 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615ac7780, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#113 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615ac7780) at nemo-desktop-manager.c:365
---Type <return> to continue, or q <return> to quit---
#114 0x000055555559743c in on_run_state_changed (manager=0x555615ac7780) at nemo-desktop-manager.c:446
#115 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#116 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#117 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#118 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#119 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#120 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615aba440) at nemo-desktop-window.c:351
#121 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#122 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#123 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#124 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#125 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#126 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x555615a8f860, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#127 0x00005555555971e7 in layout_changed (manager=manager@entry=0x555615a8f860) at nemo-desktop-manager.c:365
#128 0x000055555559743c in on_run_state_changed (manager=0x555615a8f860) at nemo-desktop-manager.c:446
#129 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#130 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#131 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#132 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#133 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#134 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x5556159e4800) at nemo-desktop-window.c:351
#135 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#136 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#137 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#138 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#139 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#140 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x5556159ba940, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#141 0x00005555555971e7 in layout_changed (manager=manager@entry=0x5556159ba940) at nemo-desktop-manager.c:365
#142 0x000055555559743c in on_run_state_changed (manager=0x5556159ba940) at nemo-desktop-manager.c:446
#143 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#144 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#145 0x00007ffff4e668bd in g_object_newv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#146 0x00007ffff4e67074 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#147 0x0000555555597a95 in nemo_desktop_manager_get () at nemo-desktop-manager.c:697
#148 0x0000555555598766 in nemo_desktop_window_update_geometry (window=window@entry=0x555615911c00) at nemo-desktop-window.c:351
#149 0x0000555555598939 in nemo_desktop_window_constructed (obj=<optimized out>) at nemo-desktop-window.c:126
#150 0x00007ffff4e65427 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#151 0x00007ffff4e66dbe in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#152 0x00007ffff4e67061 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#153 0x0000555555598690 in nemo_desktop_window_new (monitor=monitor@entry=0) at nemo-desktop-window.c:193
#154 0x0000555555596f40 in create_new_desktop_window (manager=manager@entry=0x5556158df9b0, monitor=monitor@entry=0, primary=primary@entry=1, show_desktop=show_desktop@entry=1) at nemo-desktop-manager.c:300
#155 0x00005555555971e7 in layout_changed (manager=manager@entry=0x5556158df9b0) at nemo-desktop-manager.c:365
#156 0x000055555559743c in on_run_state_changed (manager=0x5556158df9b0) at nemo-desktop-manager.c:446
#157 0x00007ffff4e8301b in g_type_create_instance () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#158 0x00007ffff4e64eab in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) 
```

**Comment by Fjodor42** [comment]
Oh, and thank you for looking into this, @mtwebster :-)

**Comment by Fjodor42** [comment]
FYI, @mtwebster, I just build 0.15.0 debs from https://packages.debian.org/buster/sddm - problem persists

**Comment by mtwebster** [comment]
btw, I just triggered a build of nemo on the nightly ppa so you won't have to wait a full daily cycle ot try it if you want.

Fixed a couple of bugs here - we weren't trying hard enough to detect you were running a cinnamon session (there are multiple available environment variables... this is a "too many standards" problem), but when we went to a 'fallback' mode, you got the crash due to a recursion bug.

**Comment by Fjodor42** [comment]
Hi @mtwebster,

That sounds really great - thank you. Will report back :-)

**Comment by Fjodor42** [comment]
Hi again,

It seems to work - thank you very much :-)

Fonts are rather blocky, but I did have some font problems in other contexts on this machine, so I will have to investigate this separately, and I don't believe it to be Nemo-specific, so thank you again :-)
