### ISSUE TITLE
Nemo crashes when copy/pasting text from a filename (100% reproducible)

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1689]
```
 * Nemo version (nemo --version)
nemo 3.6.5
 * Is issue with desktop or windowed nemo?
windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia 387.34
 * 32 or 64 bit
64bit
 ```

**Issue**
Nemo crashes when I copy text out of a filename.

**Steps to reproduce**
1) Select List View
2) Select a file and go into edit filename mode
3) Right click and select some text from the filename
4) Click on another filename
Nemo will now crash.

Here is the video of the crash: https://my.mixtape.moe/ghlxkr.webm

**Expected behaviour**
After you've clicked on another filename, Nemo should exit out of the edit filename mode. It shouldn't crash.

````
traps: nemo[7421] general protection ip:7f927915b31f sp:7ffec99dd758 error:0 in libgobject-2.0.so.0.5400.3[7f9279124000+54000]

Process 7421 (nemo) of user 1000 dumped core.

Stack trace of thread 7421:
#0  0x00007f927915b31f g_type_check_instance_is_fundamentally_a (libgobject-2.0.so.0)
#1  0x00007f9279138de6 g_object_unref (libgobject-2.0.so.0)
#2  0x00007f927ad580ff n/a (libgtk-3.so.0)
#3  0x00007f927ad6b60c n/a (libgtk-3.so.0)
#4  0x00007f92735e81c8 ffi_call_unix64 (libffi.so.6)
#5  0x00007f92735e7c2a ffi_call (libffi.so.6)
#6  0x00007f927913486f g_cclosure_marshal_generic_va (libgobject-2.0.so.0)
#7  0x00007f9279133ea6 n/a (libgobject-2.0.so.0)
#8  0x00007f9279150af9 g_signal_emit_valist (libgobject-2.0.so.0)
#9  0x00007f9279151240 g_signal_emit (libgobject-2.0.so.0)
#10 0x00007f927abe03c6 n/a (libgtk-3.so.0)
#11 0x00007f9279136c68 g_cclosure_marshal_VOID__BOXEDv (libgobject-2.0.so.0)
#12 0x00007f9279133ea6 n/a (libgobject-2.0.so.0)
#13 0x00007f9279150af9 g_signal_emit_valist (libgobject-2.0.so.0)
#14 0x00007f9279151240 g_signal_emit (libgobject-2.0.so.0)
#15 0x00007f927abdd20f n/a (libgtk-3.so.0)
#16 0x00007f927abde7e3 n/a (libgtk-3.so.0)
#17 0x00007f927abe15c7 n/a (libgtk-3.so.0)
#18 0x00007f927abace34 gtk_event_controller_handle_event (libgtk-3.so.0)
#19 0x00007f927ad7c654 n/a (libgtk-3.so.0)
#20 0x000056378e22ff38 n/a (nemo)
#21 0x00007f927ac2b38c n/a (libgtk-3.so.0)
#22 0x00007f9279133c5d g_closure_invoke (libgobject-2.0.so.0)
#23 0x00007f9279147b50 n/a (libgobject-2.0.so.0)
#24 0x00007f9279150191 g_signal_emit_valist (libgobject-2.0.so.0)
#25 0x00007f9279151240 g_signal_emit (libgobject-2.0.so.0)
#26 0x00007f927ad7e9e5 n/a (libgtk-3.so.0)
#27 0x00007f927ac281eb n/a (libgtk-3.so.0)
#28 0x00007f927ac2a443 gtk_main_do_event (libgtk-3.so.0)
#29 0x00007f927a7329f6 n/a (libgdk-3.so.0)
#30 0x00007f927a765375 n/a (libgdk-3.so.0)
#31 0x00007f9278e59e68 g_main_context_dispatch (libglib-2.0.so.0)
#32 0x00007f9278e5a0b1 n/a (libglib-2.0.so.0)
#33 0x00007f9278e5a13e g_main_context_iteration (libglib-2.0.so.0)
#34 0x00007f927941f96e g_application_run (libgio-2.0.so.0)
#35 0x000056378e204c12 n/a (nemo)
#36 0x00007f9277f00f4a __libc_start_main (libc.so.6)
#37 0x000056378e204c6a n/a (nemo)

Stack trace of thread 7455:
#0  0x00007f9277fcb91b __poll (libc.so.6)
#1  0x00007f9278e5a023 n/a (libglib-2.0.so.0)
#2  0x00007f9278e5a13e g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f9267df9b0e n/a (libdconfsettings.so)
#4  0x00007f9278e8229a n/a (libglib-2.0.so.0)
#5  0x00007f927829e08c start_thread (libpthread.so.0)
#6  0x00007f9277fd5e1f __clone (libc.so.6)

Stack trace of thread 7451:
#0  0x00007f9277fcb91b __poll (libc.so.6)
#1  0x00007f9278e5a023 n/a (libglib-2.0.so.0)
#2  0x00007f9278e5a13e g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007f9278e5a192 n/a (libglib-2.0.so.0)
#4  0x00007f9278e8229a n/a (libglib-2.0.so.0)
#5  0x00007f927829e08c start_thread (libpthread.so.0)
#6  0x00007f9277fd5e1f __clone (libc.so.6)

Stack trace of thread 7452:
#0  0x00007f9277fcb91b __poll (libc.so.6)
#1  0x00007f9278e5a023 n/a (libglib-2.0.so.0)
#2  0x00007f9278e5a3e2 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007f927944e6d8 n/a (libgio-2.0.so.0)
#4  0x00007f9278e8229a n/a (libglib-2.0.so.0)
#5  0x00007f927829e08c start_thread (libpthread.so.0)
#6  0x00007f9277fd5e1f __clone (libc.so.6)

Stack trace of thread 28329:
#0  0x00007f9277fd0819 syscall (libc.so.6)
#1  0x00007f9278ea0dfd g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007f9278e2d753 n/a (libglib-2.0.so.0)
#3  0x00007f9278e2dd3e g_async_queue_timeout_pop (libglib-2.0.so.0)
#4  0x00007f9278e82db1 n/a (libglib-2.0.so.0)
#5  0x00007f9278e8229a n/a (libglib-2.0.so.0)
#6  0x00007f927829e08c start_thread (libpthread.so.0)
#7  0x00007f9277fd5e1f __clone (libc.so.6)

````

**Comment by leigh123linux** [comment]
@nick-s-b  your backtrace is useless, lucky it reproduces here

```
Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
g_type_check_instance_is_fundamentally_a (type_instance=type_instance@entry=0x555556540490, fundamental_type=fundamental_type@entry=80)
    at gtype.c:4025
4025	gtype.c: No such file or directory.
(gdb) bt full
#0  0x00007ffff46e147f in g_type_check_instance_is_fundamentally_a (type_instance=type_instance@entry=0x555556540490, fundamental_type=fundamental_type@entry=80) at gtype.c:4025
        node = <optimized out>
#1  0x00007ffff46bf8e5 in g_object_unref (_object=0x555556540490) at gobject.c:3235
        _g_boolean_var_ = <optimized out>
        object = 0x555556540490
#2  0x00007ffff60b3ae8 in gtk_cell_area_stop_editing (area=<optimized out>, canceled=<optimized out>) at gtkcellarea.c:3523
        edit_widget = <optimized out>
        edit_cell = <optimized out>
        priv = <optimized out>
        __func__ = "gtk_cell_area_stop_editing"
#3  0x00007ffff62d246d in gtk_tree_view_stop_editing (tree_view=tree_view@entry=0x5555560de3d0 [GtkTreeView], cancel_editing=cancel_editing@entry=0) at gtktreeview.c:15728
        column = <optimized out>
#4  0x00007ffff62e53bb in gtk_tree_view_multipress_gesture_pressed (gesture=0x5555560786a0 [GtkGestureMultiPress], n_press=1, x=114, y=451, tree_view=0x5555560de3d0 [GtkTreeView]) at gtktreeview.c:3150
        vertical_separator = -290851185
        horizontal_separator = 32767
        widget = 0x5555560de3d0 [GtkTreeView]
        background_area = {x = 0, y = 0, width = 2089194752, height = -1528464034}
        cell_area = {x = 0, y = 1079803904, width = 1446168240, height = 21845}
        column = 0x0
        sequence = <optimized out>
        modifiers = 1443333792
        event = <optimized out>
        new_y = <optimized out>
        y_offset = <optimized out>
        bin_x = 21845
        bin_y = 1
        path = <optimized out>
        node = 0x5555560de3d0
        tree = 0x0
        depth = <optimized out>
        button = <optimized out>
        list = <optimized out>
        rtl = <optimized out>
#5  0x00007fffeea9fd1e in ffi_call_unix64 () at ../src/x86/unix64.S:76
#6  0x00007fffeea9f68f in ffi_call (cif=cif@entry=0x7fffffffce30, fn=fn@entry=0x7ffff62e5370 <gtk_tree_view_multipress_gesture_pressed>, rvalue=<optimized out>, avalue=avalue@entry=0x7fffffffcd00) at ../src/x86/ffi64.c:525
        classes = {X86_64_INTEGER_CLASS, 21845, 4294954544, 32767}
        stack = <optimized out>
        argp = <optimized out>
        arg_types = <optimized out>
        gprcount = 3
        ssecount = <optimized out>
        ngpr = 1
        nsse = 0
        i = <optimized out>
        avn = <optimized out>
        ret_in_memory = <optimized out>
        reg_args = <optimized out>
#7  0x00007ffff46bb56d in g_cclosure_marshal_generic_va (closure=0x5555560ddfd0, return_value=0x0, instance=<optimized out>, args_list=<optimized out>, marshal_data=<optimized out>, n_params=3, param_types=0x555555c65f80) at gclosure.c:1604
        rtype = 0x7fffeeaa0110 <ffi_type_void>
        rvalue = 0x7fffffffcd80
        n_args = 5
        atypes = 0x7fffffffcd40
        args = 0x7fffffffcd00
        storage = 0x7fffffffccd0
        i = <optimized out>
        cif = {abi = FFI_UNIX64, nargs = 5, arg_types = 0x7fffffffcd40, rtype = 0x7fffeeaa0110 <ffi_type_void>, bytes = 0, flags = 2048}
        cc = 0x5555560ddfd0
        enum_tmpval = <optimized out>
        tmpval_used = 0
        args_copy = {{gp_offset = 32, fp_offset = 80, overflow_arg_area = 0x7fffffffd1c0, reg_save_area = 0x7fffffffd100}}
#8  0x00007ffff46babc6 in _g_closure_invoke_va (closure=0x5555560ddfd0, return_value=0x0, instance=0x5555560786a0, args=0x7fffffffd0e0, n_params=3, param_types=0x555555c65f80) at gclosure.c:867
        marshal = 0x7ffff46bb2e0 <g_cclosure_marshal_generic_va>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x5555560ddfb0
        __func__ = "_g_closure_invoke_va"
#9  0x00007ffff46d6f14 in g_signal_emit_valist (instance=0x5555560786a0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd0e0) at gsignal.c:3300
        return_accu = 0x0
        accu = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = 
          {next = 0x7fffffffd3b0, instance = 0x5555560786a0, ihint = {signal_id = 286, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 93824998245920}
        signal_id = 286
        instance_type = 93824998245920
        emission_return = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#10 0x00007ffff46d759f in g_signal_emit (instance=instance@entry=0x5555560786a0, signal_id=<optimized out>, detail=detail@entry=0)
    at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffd1c0, reg_save_area = 0x7fffffffd100}}

#11 0x00007ffff616385c in gtk_gesture_multi_press_begin (gesture=0x5555560786a0 [GtkGestureMultiPress], sequence=<optimized out>)
    at gtkgesturemultipress.c:241
        multi_press = 0x5555560786a0 [GtkGestureMultiPress]
        priv = <optimized out>
        n_presses = <optimized out>
        button = <optimized out>
        current = 0x0
        event = <optimized out>
        device = <optimized out>
        x = 114
        y = 451
#12 0x00007ffff46bd888 in g_cclosure_marshal_VOID__BOXEDv (closure=0x555555df96b0, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x555555df9720) at gmarshal.c:1950
        cc = 0x555555df96b0
        data1 = <optimized out>
        data2 = <optimized out>
        callback = <optimized out>
        arg0 = 0x0
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffd590, reg_save_area = 0x7fffffffd4d0}}
#13 0x00007ffff46babc6 in _g_closure_invoke_va (closure=0x555555df96b0, return_value=0x0, instance=0x5555560786a0, args=0x7fffffffd4b0, n_params=1, param_types=0x555555df9720) at gclosure.c:867
        marshal = 0x7ffff46b8dd0 <g_type_class_meta_marshalv>
        marshal_data = 0xf8
        in_marshal = 0
        real_closure = 0x555555df9690
        __func__ = "_g_closure_invoke_va"
#14 0x00007ffff46d6f14 in g_signal_emit_valist (instance=0x5555560786a0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffd4b0) at gsignal.c:3300
        return_accu = 0x0
        accu = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = 
          {next = 0x7fffffffd8b0, instance = 0x5555560786a0, ihint = {signal_id = 281, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 93824998245920}
        signal_id = 281
        instance_type = 93824998245920
        emission_return = 
              {g_type = 0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 4
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#15 0x00007ffff46d759f in g_signal_emit (instance=instance@entry=0x5555560786a0, signal_id=<optimized out>, detail=detail@entry=0)
    at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7fffffffd590, reg_save_area = 0x7fffffffd4d0}}
#16 0x00007ffff616077e in _gtk_gesture_set_recognized (sequence=0x0, recognized=1, gesture=0x5555560786a0 [GtkGestureMultiPress])
    at gtkgesture.c:343
        sequence = 0x0
        gesture = 0x5555560786a0 [GtkGestureMultiPress]
        priv = <optimized out>
        priv = 0x555556078650
        has_matching_touchpoints = <optimized out>
#17 0x00007ffff616077e in _gtk_gesture_check_recognized (gesture=gesture@entry=0x5555560786a0 [GtkGestureMultiPress], sequence=sequence@entry=0x0) at gtkgesture.c:389
        priv = 0x555556078650
        has_matching_touchpoints = <optimized out>
#18 0x00007ffff6161cdb in gtk_gesture_handle_event (controller=0x5555560786a0 [GtkGestureMultiPress], event=0x7fffcc028c70)
    at gtkgesture.c:747
        triggered_recognition = 1
        gesture = 0x5555560786a0 [GtkGestureMultiPress]
        was_recognized = 0
        sequence = 0x0
        priv = 0x555556078650
        source_device = <optimized out>
        controller = 0x5555560786a0 [GtkGestureMultiPress]
        event = 0x7fffcc028c70
        gesture = 0x5555560786a0 [GtkGestureMultiPress]
        source_device = <optimized out>
#19 0x00007ffff6164a3e in gtk_gesture_single_handle_event (controller=0x5555560786a0 [GtkGestureMultiPress], event=0x7fffcc028c70)
    at gtkgesturesingle.c:222
        sequence = <optimized out>
        priv = 0x555556078630
        source_device = <optimized out>
        source = GDK_SOURCE_MOUSE
        button = <optimized out>
        i = <optimized out>
        retval = <optimized out>
        test_touchscreen = <optimized out>
#20 0x00007ffff6131c01 in gtk_event_controller_handle_event (controller=0x5555560786a0 [GtkGestureMultiPress], event=event@entry=0x7fffcc028c70) at gtkeventcontroller.c:230
        controller_class = 0x555555c937a0
        retval = 0
        __func__ = "gtk_event_controller_handle_event"
#21 0x00007ffff62f5e2b in _gtk_widget_run_controllers (widget=0x5555560de3d0 [GtkTreeView], event=0x7fffcc028c70, phase=GTK_PHASE_BUBBLE)
    at gtkwidget.c:7367
        controller_phase = <optimized out>
        next = 0x0
        data = 0x5555560dde80
        handled = 0
        priv = 0x5555560de2e0
        l = <optimized out>
#22 0x00005555555b541e in button_press_callback (widget=widget@entry=0x5555560de3d0 [GtkTreeView], event=0x7fffcc028c70, callback_data=<optimized out>) at nemo-list-view.c:1122
        view = 0x555555fb44d0 [NemoListView]
        tree_view = 0x5555560de3d0 [GtkTreeView]
        path = 0x555555f47b60
        call_parent = <optimized out>
        selection = 0x5555560dbcd0 [GtkTreeSelection]
        tree_view_class = 0x5555560d52c0
        expander_size = 20
        horizontal_separator = 4
        on_expander = <optimized out>
        blank_click = <optimized out>
#27 0x00007ffff46d759f in <emit signal ??? on instance 0x5555560de3d0 [GtkTreeView]> (instance=instance@entry=0x5555560de3d0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
        var_args = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fffffffdc00, reg_save_area = 0x7fffffffdb40}}
    #23 0x00007ffff61ace7b in _gtk_marshal_BOOLEAN__BOXED (closure=0x5555560e2710, return_value=0x7fffffffd8e0, n_param_values=<optimized out>, param_values=0x7fffffffd940, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtkmarshalers.c:82
                cc = 0x5555560e2710
                data1 = 0x5555560de3d0
                data2 = <optimized out>
                callback = 0x5555555b5260 <button_press_callback>
                v_return = <optimized out>
                __func__ = "_gtk_marshal_BOOLEAN__BOXED"
    #24 0x00007ffff46ba98d in g_closure_invoke (closure=0x5555560e2710, return_value=0x7fffffffd8e0, n_param_values=2, param_values=0x7fffffffd940, invocation_hint=0x7fffffffd8c0) at gclosure.c:804
                marshal = 0x7ffff61ace10 <_gtk_marshal_BOOLEAN__BOXED>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x5555560e26f0
                __func__ = "g_closure_invoke"
    #25 0x00007ffff46ce23e in signal_emit_unlocked_R (node=node@entry=0x555555987420, detail=detail@entry=0, instance=instance@entry=0x5555560de3d0, emission_return=emission_return@entry=0x7fffffffda70, instance_and_params=instance_and_params@entry=0x7fffffffd940)
    at gsignal.c:3635
                tmp = <optimized out>
                handler = 0x5555560e2800
                accumulator = 0x555555987700
                emission = 
                  {next = 0x0, instance = 0x5555560de3d0, ihint = {signal_id = 75, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 4}
                class_closure = 0x5555559873d0
                handler_list = 0x5555560e2800
                return_accu = 0x7fffffffd8e0
                accu = 
                      {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 75
                max_sequential_handler_number = 15413
                return_value_altered = 0
    #26 0x00007ffff46d65bf in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffdb20) at gsignal.c:3401
                return_value = 
                      {g_type = 20, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                error = 0x0
                rtype = 20
                static_scope = 0
                instance_and_params = 0x7fffffffd940
                signal_return_type = <optimized out>
                param_values = 0x7fffffffd958
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#28 0x00007ffff62f80d4 in gtk_widget_event_internal (widget=widget@entry=0x5555560de3d0 [GtkTreeView], event=event@entry=0x7fffcc028c70)
    at gtkwidget.c:7732
        signal_num = <optimized out>
        return_val = <optimized out>
        handled = 0
        __func__ = "gtk_widget_event_internal"
#29 0x00007ffff62fa20a in gtk_widget_event (widget=widget@entry=0x5555560de3d0 [GtkTreeView], event=event@entry=0x7fffcc028c70)
    at gtkwidget.c:7302
        __func__ = "gtk_widget_event"
#30 0x00007ffff61a9e4e in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0x5555560de3d0 [GtkTreeView])
    at gtkmain.c:2578
        tmp = <optimized out>
        handled_event = <optimized out>
        handled_event = 0
#31 0x00007ffff61a9e4e in propagate_event (widget=<optimized out>, event=0x7fffcc028c70, captured=<optimized out>, topmost=0x0)
    at gtkmain.c:2680
        handled_event = 0
#32 0x00007ffff61abf70 in gtk_main_do_event (event=<optimized out>) at gtkmain.c:1911
        window_group = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        event_widget = <optimized out>
        event = 0x7fffcc028c70
#33 0x00007ffff5cb93f5 in _gdk_event_emit (event=event@entry=0x7fffcc028c70) at gdkevents.c:73
#34 0x00007ffff5ceac12 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>)
    at gdkeventsource.c:367
        display = <optimized out>
        event = 0x7fffcc028c70
#35 0x00007ffff43e1b07 in g_main_dispatch (context=0x555555943520) at gmain.c:3200
        dispatch = 0x7ffff5ceabf0 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x555555907880
        current = 0x5555559c9c00
        i = 0
#36 0x00007ffff43e1b07 in g_main_context_dispatch (context=context@entry=0x555555943520) at gmain.c:3853
#37 0x00007ffff43e1eb0 in g_main_context_iterate (context=context@entry=0x555555943520, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3926
        max_priority = 2147483647
        timeout = 445
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x555555947ec0
#38 0x00007ffff43e1f3c in g_main_context_iteration (context=context@entry=0x555555943520, may_block=may_block@entry=1) at gmain.c:3987
        retval = <optimized out>
#39 0x00007ffff49a756d in g_application_run (application=0x555555940130 [NemoMainApplication], argc=<optimized out>, argv=<optimized out>) at gapplication.c:2482
        arguments = 0x55555593edf0
        status = 0
        context = 0x555555943520
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#40 0x000055555558bc3b in main (argc=1, argv=0x7fffffffe018) at nemo-main.c:104
        retval = <optimized out>
        application = 0x555555940130 [NemoMainApplication]

```

**Comment by nick-s-b** [comment]
@leigh123linux could you please teach me how to produce a useful backtrace after a crash. Thank you!

**Comment by leigh123linux** [comment]
@nick-s-b  You need to recompile, see https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces#Building_and_installing_the_package

**Comment by Zedruide** [comment]
Me too, same bug. (Arch).
