### ISSUE TITLE
Crash when drag-n-dropping files to desktop

### ISSUE THREAD

**Issue by gkatev** [linuxmint/nemo#1775]
```
nemo 3.6.5
Antergos
 ```
nemo-desktop crashes when trying to move a file to the desktop by drag-and-drop.

**Steps to reproduce**
Open a directory using nemo, create a file, drag and drop the file to the desktop.

[coredump](https://github.com/linuxmint/nemo/files/1704651/core.nemo-desktop.1000.09bde3b0cfad4fa9b42352a286758b18.2122.1518035348000000.zip)

Output of gdb backtrace(bt):

```
Core was generated by `nemo-desktop'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ba4a93f502 in prep_selection (container=0x55ba4be00470, world_x=1023, world_y=139)
    at ../libnemo-private/nemo-icon-dnd.c:1196
1196	                    if (icon->item) {
[Current thread is 1 (Thread 0x7f0bf7e63240 (LWP 2122))]
(gdb) bt
#0  0x000055ba4a93f502 in prep_selection (container=0x55ba4be00470, world_x=1023, world_y=139)
    at ../libnemo-private/nemo-icon-dnd.c:1196
#1  0x000055ba4a93fcdf in nemo_icon_container_receive_dropped_icons (container=0x55ba4be00470, context=0x55ba4bdb1330, x=1023, y=139) at ../libnemo-private/nemo-icon-dnd.c:1423
#2  0x000055ba4a940f36 in drag_data_received_callback (widget=0x55ba4be00470, context=0x55ba4bdb1330, x=1023, y=139, data=0x7fffd7a93df0, info=0, time=198028220, user_data=0x0) at ../libnemo-private/nemo-icon-dnd.c:1927
#3  0x00007f0bf7188495 in  () at /usr/lib/libgtk-3.so.0
#4  0x00007f0bf5a9fc5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#5  0x00007f0bf5ab3b50 in  () at /usr/lib/libgobject-2.0.so.0
#6  0x00007f0bf5abc806 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007f0bf5abd71c in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#8  0x00007f0bf7302757 in  () at /usr/lib/libgtk-3.so.0
#9  0x00007f0bf5a9fc5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#10 0x00007f0bf5ab3b50 in  () at /usr/lib/libgobject-2.0.so.0
#11 0x00007f0bf5abc806 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#12 0x00007f0bf5abd71c in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#13 0x00007f0bf7212915 in  () at /usr/lib/libgtk-3.so.0
#14 0x00007f0bf7216b80 in  () at /usr/lib/libgtk-3.so.0
#15 0x00007f0bf7181ca8 in  () at /usr/lib/libgtk-3.so.0
#16 0x00007f0bf5a9fea6 in  () at /usr/lib/libgobject-2.0.so.0
#17 0x00007f0bf5abc4b4 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x00007f0bf5abd240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#19 0x00007f0bf72d50e5 in  () at /usr/lib/libgtk-3.so.0
#20 0x00007f0bf7180be0 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#21 0x00007f0bf6c899f6 in  () at /usr/lib/libgdk-3.so.0
#22 0x00007f0bf6cbc1d5 in  () at /usr/lib/libgdk-3.so.0
#23 0x00007f0bf57c5e38 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#24 0x00007f0bf57c6081 in  () at /usr/lib/libglib-2.0.so.0
#25 0x00007f0bf57c610e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#26 0x00007f0bf5d8b96e in g_application_run () at /usr/lib/libgio-2.0.so.0
#27 0x000055ba4a8c6e13 in main (argc=1, argv=0x7fffd7a94558) at ../src/nemo-desktop-main.c:101
```

**Comment by brownsr** [comment]
d6348aa5ffb9eaabd255e53e8ca075ec60d808d2

**Comment by xenopeek** [comment]
I couldn't reproducible with Nemo 4.6.4. This looks fixed.
