### ISSUE TITLE
Bug -- Crash when deleting from sidebar

### ISSUE THREAD

**Issue by ryanmusante** [linuxmint/nemo#1783]
```
 * Nemo 3.6.5
 * windowed
 * Manjaro
 * nvidia 390.25
 * 64 bit
 ```

**Issue**
kernel: traps: nemo[11291] general protection ip:561e9566ac27 sp:7ffe5fc5f740 error:0 in nemo[561e9558b000+1a9000]

Crash when deleting files or folders from sidebar

**Steps to reproduce**
1. Show Sidebar
2. Enable Tree
3. Delete or move file trash

Crash

**Expected behaviour**

No Crash

**Other information**

**Comment by leigh123linux** [comment]
Backtrace for the crash.

```
#0  0x00005555556468ca in nemo_file_unref (file=0x5555563acfa0) at ../libnemo-private/nemo-file.c:887
        __inst = 0x5555563acfa0
        __t = 93825003944928
        __r = <optimized out>
        _g_boolean_var_ = <optimized out>
        __func__ = "nemo_file_unref"
#1  0x00007ffff58f4a35 in g_list_foreach () at /lib64/libglib-2.0.so.0
#2  0x000055555564ee22 in nemo_file_list_unref (list=<optimized out>) at ../libnemo-private/nemo-file.c:7874
#3  0x000055555564ee3d in nemo_file_list_free (list=0x555555ae9200 = {...}) at ../libnemo-private/nemo-file.c:7886
#4  0x00007ffff58e74d8 in g_hash_table_foreach () at /lib64/libglib-2.0.so.0
#5  0x0000555555630221 in nemo_directory_notify_files_removed (files=<optimized out>) at ../libnemo-private/nemo-directory.c:1100
#6  0x0000555555633615 in nemo_file_changes_consume_changes (consume_all=consume_all@entry=1)
    at ../libnemo-private/nemo-file-changes-queue.c:314
        change = <optimized out>
        additions = 0x0
        changes = 0x0
        deletions = 0x555555b19f60 = {0x555555b0a120, 0x555555afd8e0, 0x555555b16ba0}
        moves = 0x0
        position_set_requests = 0x0
        pair = <optimized out>
        position_set = <optimized out>
        chunk_count = 3
        queue = 0x7fffc0034ba0
        flush_needed = <optimized out>
        __func__ = "nemo_file_changes_consume_changes"
#7  0x0000555555633a79 in delete_job_done (user_data=0x5555565e7d30) at ../libnemo-private/nemo-file-operations.c:2070
        job = 0x5555565e7d30
        debuting_uris = <optimized out>
#8  0x00007ffff5e82603 in mainloop_proxy_func () at /lib64/libgio-2.0.so.0
#9  0x00007ffff58f509b in g_idle_dispatch () at /lib64/libglib-2.0.so.0
#10 0x00007ffff58f877d in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#11 0x00007ffff58f8b48 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#12 0x00007ffff58f8be0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#13 0x00007ffff5ec4465 in g_application_run () at /lib64/libgio-2.0.so.0
#14 0x00005555555894bf in main (argc=1, argv=0x7fffffffdfe8) at ../src/nemo-main.c:104
        retval = <optimized out>
        application = 0x555555940130
```
