### ISSUE TITLE
Nemo randomly crashing

### ISSUE THREAD

**Issue by daddy33** [linuxmint/nemo#1784]
```
 * Nemo version 3.6.5
 * windowed nemo
 * Manjaro
 * nvidia GeForce GT 710B + proprietary drivers 390.25
 * 64 bit
 ```

Hello,

I have this bug for months, in Manjaro but also in Antergos. For information, I have made a complete new install of Manjaro Cinnamon on a brand new SSD three days ago. 
Well, nemo is randomly crashing (let's say 5/6 times per day). I can't connect this to any action in particular. I currently use a nvidia vga card + proprietary drivers, but this bug was also present with an amd card with open source drivers. The nemo window just closes suddenly. I have found this core dump info : 

```

       Message: Process 14205 (nemo) of user 1000 dumped core.
                
                Stack trace of thread 14205:
                #0  0x00007ff72cad5b9f gtk_widget_get_mapped (libgtk-3.so.0)
                #1  0x00007ff72ca0a77a n/a (libgtk-3.so.0)
                #2  0x00007ff72ca0a8a0 n/a (libgtk-3.so.0)
                #3  0x00007ff72ca0a984 n/a (libgtk-3.so.0)
                #4  0x00007ff72ab8b783 n/a (libglib-2.0.so.0)
                #5  0x00007ff72ab8aca6 g_main_context_dispatch (libglib-2.0.so.0)
                #6  0x00007ff72ab8b081 n/a (libglib-2.0.so.0)
                #7  0x00007ff72ab8b10e g_main_context_iteration (libglib-2.0.so.0)
                #8  0x00007ff72b15696e g_application_run (libgio-2.0.so.0)
                #9  0x000055ebd8837c12 n/a (nemo)
                #10 0x00007ff729c20f4a __libc_start_main (libc.so.6)
                #11 0x000055ebd8837c6a n/a (nemo)
                
                Stack trace of thread 14207:
                #0  0x00007ff729ceb97b __poll (libc.so.6)
                #1  0x00007ff72ab8aff3 n/a (libglib-2.0.so.0)
                #2  0x00007ff72ab8b10e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007ff72ab8b162 n/a (libglib-2.0.so.0)
                #4  0x00007ff72abb326a n/a (libglib-2.0.so.0)
                #5  0x00007ff729fbf08c start_thread (libpthread.so.0)
                #6  0x00007ff729cf5e7f __clone (libc.so.6)
                
                Stack trace of thread 14209:
                #0  0x00007ff729ceb97b __poll (libc.so.6)
                #1  0x00007ff72ab8aff3 n/a (libglib-2.0.so.0)
                #2  0x00007ff72ab8b10e g_main_context_iteration (libglib-2.0.so.0)
                #3  0x00007ff71d9aeb0e n/a (libdconfsettings.so)
                #4  0x00007ff72abb326a n/a (libglib-2.0.so.0)
                #5  0x00007ff729fbf08c start_thread (libpthread.so.0)
                #6  0x00007ff729cf5e7f __clone (libc.so.6)
                
                Stack trace of thread 14208:
                #0  0x00007ff729ceb97b __poll (libc.so.6)
                #1  0x00007ff72ab8aff3 n/a (libglib-2.0.so.0)
                #2  0x00007ff72ab8b3b2 g_main_loop_run (libglib-2.0.so.0)
                #3  0x00007ff72b1856d8 n/a (libgio-2.0.so.0)
                #4  0x00007ff72abb326a n/a (libglib-2.0.so.0)
                #5  0x00007ff729fbf08c start_thread (libpthread.so.0)
                #6  0x00007ff729cf5e7f __clone (libc.so.6)
                
                Stack trace of thread 15148:
                #0  0x00007ff729cf0879 syscall (libc.so.6)
                #1  0x00007ff72abd1dcd g_cond_wait_until (libglib-2.0.so.0)
                #2  0x00007ff72ab5e753 n/a (libglib-2.0.so.0)
                #3  0x00007ff72ab5ed3e g_async_queue_timeout_pop (libglib-2.0.so.0)
                #4  0x00007ff72abb3d81 n/a (libglib-2.0.so.0)
                #5  0x00007ff72abb326a n/a (libglib-2.0.so.0)
                #6  0x00007ff729fbf08c start_thread (libpthread.so.0)
                #7  0x00007ff729cf5e7f __clone (libc.so.6)
```
Any idea or suggestion?
Thanks for help.

**Comment by leigh123linux** [comment]
Can you can provide a backtrace complete with symbols, if not you might as well close the issue.

**Comment by daddy33** [comment]
OK. I will try to wait for a crash (because this is not reproducible on demand) and then provide the backtrace.

**Comment by gkatev** [comment]
I've been having the same issue and judging from the 'gtk_widget_get_mapped' in the above core dump, it may be the same problem. The coredump generated has debugging symbols, though it doesn't seem too descriptive...

The output of 'thread apply all bt' is:
```
Thread 5 (Thread 0x7f1b47e9e700 (LWP 2151)):
#0  0x00007f1b538fa97b in poll () at /usr/lib/libc.so.6
#1  0x00007f1b554f1ff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f1b554f23b2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007f1b55ae66d8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f1b5551a26a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f1b53bcd08c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f1b53904e7f in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f1b4869f700 (LWP 2150)):
#0  0x00007f1b538fa97b in poll () at /usr/lib/libc.so.6
#1  0x00007f1b554f1ff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f1b554f210e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f1b554f2162 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f1b5551a26a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f1b53bcd08c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f1b53904e7f in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f1b4740e700 (LWP 2152)):
#0  0x00007f1b538fa97b in poll () at /usr/lib/libc.so.6
#1  0x00007f1b554f1ff3 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f1b554f210e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f1b47415b0e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007f1b5551a26a in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f1b53bcd08c in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f1b53904e7f in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f1b1f7fe700 (LWP 15548)):
#0  0x00007f1b538ff879 in syscall () at /usr/lib/libc.so.6
#1  0x00007f1b55538dcd in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007f1b554c5753 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007f1b554c5d3e in g_async_queue_timeout_pop () at /usr/lib/libglib-2.0.so.0
#4  0x00007f1b5551ad81 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f1b5551a26a in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007f1b53bcd08c in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f1b53904e7f in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f1b57b95240 (LWP 2148)):
#0  0x00007f1b57004b9f in gtk_widget_get_mapped () at /usr/lib/libgtk-3.so.0
#1  0x00007f1b56f3977a in  () at /usr/lib/libgtk-3.so.0
#2  0x00007f1b56f398a0 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007f1b56f39984 in  () at /usr/lib/libgtk-3.so.0
#4  0x00007f1b554f2783 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f1b554f1ca6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#6  0x00007f1b554f2081 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007f1b554f210e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#8  0x00007f1b55ab796e in g_application_run () at /usr/lib/libgio-2.0.so.0
#9  0x000055be2f006504 in main (argc=2, argv=0x7ffcb766c338) at ../src/nemo-main.c:104
```

**Comment by leigh123linux** [comment]
The backtraces are useless without the debug symbols.
