### ISSUE TITLE
 [BUG] Nemo will randomly crash when creating folders

### ISSUE THREAD

**Issue by roadhazard** [linuxmint/nemo#1871]
```
 * Nemo 3.6.5
 * I'm a Linux newb so I don't understand the question. (Desktop or windowed nemo?) The problem happens when I launch Nemo on my desktop.
 * Distribution - Linux Mint 18.3 Cinnamon
 * Intel 5912 (default Kernel driver?)
 * 64 bit
 ```

When creating a folder on my MDADM array, Nemo will some times crash with a segfault error
3979.892060] nemo[18663]: segfault at 736569766f00 ip 00007fe8afc3ad99 sp 00007ffeeb96b900 error 4 in libgobject-2.0.so.0.4800.2[7fe8afc06000+52000]

Go to my Movies folder on my array and right click to create a new folder. It's like a 50/50 shot if the folder gets created with the name I type of if Nemo will crash and I end up with an "Untitled Folder".

Expected behaviour: be able to create folders without Nemo crashing.

**Other information**

[_usr_bin_nemo.1000.crash.tar.gz](https://github.com/linuxmint/nemo/files/2052132/_usr_bin_nemo.1000.crash.tar.gz)

My array is RAID6, MDADM and the file system is EXT4. Array appears to be in perfect health with no file system errors.

**Comment by roadhazard** [comment]
How do I put an official 'bug' icon by my problem? (Sorry, Linux/Github newb)

**Comment by mtwebster** [comment]
reconstructed trace:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nemo /home/gene/Downloads'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1aeaad6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f1aeece0a40 (LWP 11886))]
(gdb) bt
#0  0x00007f1aeaad6428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f1aeaad802a in __GI_abort () at abort.c:89
#2  0x00007f1aeb97fd65 in g_assertion_message (domain=domain@entry=0x0, file=file@entry=0x52cee3 "nemo-icon-view.c", line=line@entry=1989, func=func@entry=0x52d770 <__func__.57565> "icon_rename_ended_cb", message=message@entry=0x26605f0 "assertion failed: (NEMO_IS_FILE (file))") at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gtestutils.c:2429
#3  0x00007f1aeb97fdfa in g_assertion_message_expr (domain=domain@entry=0x0, file=file@entry=0x52cee3 "nemo-icon-view.c", line=line@entry=1989, func=func@entry=0x52d770 <__func__.57565> "icon_rename_ended_cb", expr=expr@entry=0x52ae9e "NEMO_IS_FILE (file)")
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gtestutils.c:2452
#4  0x000000000044370f in icon_rename_ended_cb (container=<optimized out>, file=0x242a2a0, new_name=0x2398e80 "In Darkness (2018)", icon_view=0x2297820 [NemoIconView]) at nemo-icon-view.c:1989
#5  0x00007f1ae6383e40 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#6  0x00007f1ae63838ab in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#11 0x00007f1aebc4c08f in <emit signal ??? on instance 0x22ac160 [NemoIconViewContainer]> (instance=instance@entry=0x22ac160, signal_id=<optimized out>, detail=detail@entry=0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3441
    #7  0x00007f1aebc317c9 in g_cclosure_marshal_generic (closure=0x22af730, return_gvalue=0x0, n_param_values=<optimized out>, param_values=0x7fff091040b0, invocation_hint=<optimized out>, marshal_data=0x0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gclosure.c:1490
    #8  0x00007f1aebc30fa5 in g_closure_invoke (closure=0x22af730, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fff091040b0, invocation_hint=invocation_hint@entry=0x7fff09104030)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gclosure.c:804
    #9  0x00007f1aebc42fc1 in signal_emit_unlocked_R (node=node@entry=0x22a30c0, detail=detail@entry=0, instance=instance@entry=0x22ac160, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fff091040b0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3629
---Type <return> to continue, or q <return> to quit---
    #10 0x00007f1aebc4bd5c in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fff09104290) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3385
#12 0x00000000004eedd3 in nemo_icon_container_end_renaming_mode (container=container@entry=0x22ac160 [NemoIconViewContainer], commit=commit@entry=1) at nemo-icon-container.c:6973
#13 0x00000000004f4805 in key_press_event (widget=0x22ac160 [NemoIconViewContainer], event=0x2d6f070)
    at nemo-icon-container.c:4129
#14 0x00007f1aed6af09a in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x1b92070, return_value=0x7fff09104620, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x1b920a0)
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmarshalers.c:131
#15 0x00007f1aebc31122 in _g_closure_invoke_va (closure=closure@entry=0x1b92070, return_value=return_value@entry=0x7fff09104620, instance=instance@entry=0x22ac160, args=args@entry=0x7fff091046f0, n_params=1, param_types=0x1b920a0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gclosure.c:867
#16 0x00007f1aebc4b4b8 in g_signal_emit_valist (instance=0x22ac160, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fff091046f0) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3294
#17 0x00007f1aebc4c08f in g_signal_emit (instance=instance@entry=0x22ac160, signal_id=<optimized out>, detail=detail@entry=0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3441
#18 0x00007f1aed7ecc3c in gtk_widget_event_internal (widget=0x22ac160 [NemoIconViewContainer], event=0x2d6f070)
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:7692
#19 0x00007f1aed80ccbb in gtk_window_propagate_key_event (window=0x1d56380 [NemoWindow], event=event@entry=0x2d6f070)
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwindow.c:7933
#20 0x00000000004a683b in nemo_window_key_press_event (widget=0x1d56380 [NemoWindow], event=0x2d6f070) at nemo-window.c:1069
#21 0x00007f1aed6af09a in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x1b92070, return_value=0x7fff09104a30, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x1b920a0)
---Type <return> to continue, or q <return> to quit---
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmarshalers.c:131
#22 0x00007f1aebc311d4 in _g_closure_invoke_va (closure=closure@entry=0x1b92070, return_value=return_value@entry=0x7fff09104a30, instance=instance@entry=0x1d56380, args=args@entry=0x7fff09104b00, n_params=<optimized out>, param_types=0x1b920a0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gclosure.c:867
#23 0x00007f1aebc4b4b8 in g_signal_emit_valist (instance=0x1d56380, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fff09104b00) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3294
#24 0x00007f1aebc4c08f in g_signal_emit (instance=instance@entry=0x1d56380, signal_id=<optimized out>, detail=detail@entry=0)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gobject/gsignal.c:3441
#25 0x00007f1aed7ecc3c in gtk_widget_event_internal (widget=0x1d56380 [NemoWindow], event=0x2d6f070)
    at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkwidget.c:7692
#26 0x00007f1aed6ac4c9 in propagate_event (widget=0x1d56380 [NemoWindow], event=0x2d6f070, captured=<optimized out>, topmost=0x0) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmain.c:2620
#27 0x00007f1aed6ae1bc in gtk_main_do_event (event=0x2d6f070) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gtk/gtkmain.c:1850
#28 0x00007f1aed21bd92 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at /build/gtk+3.0-2Ut_nl/gtk+3.0-3.18.9/./gdk/x11/gdkeventsource.c:369
#29 0x00007f1aeb95a197 in g_main_context_dispatch (context=0x1b56070)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3154
#30 0x00007f1aeb95a197 in g_main_context_dispatch (context=context@entry=0x1b56070)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3769
#31 0x00007f1aeb95a3f0 in g_main_context_iterate (context=context@entry=0x1b56070, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3840
#32 0x00007f1aeb95a49c in g_main_context_iteration (context=context@entry=0x1b56070, may_block=may_block@entry=1)
    at /build/glib2.0-prJhLS/glib2.0-2.48.2/./glib/gmain.c:3901
---Type <return> to continue, or q <return> to quit---
#33 0x00007f1aebf21d7d in g_application_run (application=0x1b5c130 [NemoMainApplication], argc=argc@entry=2, argv=argv@entry=0x7fff09104f78) at /build/glib2.0-prJhLS/glib2.0-2.48.2/./gio/gapplication.c:2381
#34 0x0000000000430cc1 in main (argc=2, argv=0x7fff09104f78) at nemo-main.c:104
(gdb) 
```

Do you have the nemo-media-columns extension installed/enabled? (edit->plugins, bottom view)

If so can you disable and restart nemo?

If this stops the crashes, then this bug has been fixed for the 3.8 release.

**Comment by roadhazard** [comment]
I only have these plug-ins in that bottom section:

EVPropertiesPlugin
Nemo Share
ChangeColorFolder+NemoPython
Nemo Emblems
Nemo Fileroller

**Comment by mtwebster** [comment]
Can you try disabling nemo emblems and the folder color plugin?

**Comment by roadhazard** [comment]
Ok, I disabled those plugins. Will test it out for a few days and let you know. Thanks!

**Comment by roadhazard** [comment]
I think your suggestion resolved my problem. Been creating a decent number of folders on my array the past few days and no more crashes. I'll go ahead and close this issue out, thanks!
