### ISSUE TITLE
Pressing F3 crashes nemo-desktop

### ISSUE THREAD

**Issue by parnikkapore** [linuxmint/nemo#1946]
```
 * Nemo version (nemo --version) | 3.8.6
 * Is issue with desktop or windowed nemo? | Only nemo-desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) | Mint 18 (No cinnamon-related PPAs)
 * Graphics hardware *and* driver used | Intel HD graphics, no driver
 * 32 or 64 bit | 64
 ```

**Issue**
Pressing F3 in nemo-desktop will crash it and make the desktop icons disappear

**Steps to reproduce**
1. Log into Cinnamon
2. Press F3
> The desktop icons will disappear.

**Expected behaviour**
Nothing happens

**Backtrace**
This crash is apparently triggered by a coded assertion error, which means we can simply replace it with a 'break'.
Specifically, 
nemo-window-manage-views.c:492 [nemo_window_slot_open_location_full]

**Comment by jaszhix** [comment]
Not reproducing this on master. F3 toggles the split pane view.

**Comment by leigh123linux** [comment]
@jaszhix  split pane on nemo-desktop?

**Comment by leigh123linux** [comment]
```
(gdb) bt full
#0  0x00007fa8a2a7853f in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 93908781757374, 93908781757548, 93908781757248, 93908781757548, 0, 0, 32, 2048, 127, 140362261728352, 140362260435032, 2048, 140359531233280, 0, 7}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007fa8a2a62895 in __GI_abort () at abort.c:79
        save_stage = 1
        act = 
          {__sigaction_handler = {sa_handler = 0xfe00, sa_sigaction = 0xfe00}, sa_mask = {__val = {1, 0, 122, 93908782008496, 6535263002650516480, 4, 140362268444094, 140362268251754, 93907614433280, 93908782008496, 6535263002650516480, 0, 93908782008496, 123, 140362268728864, 140729263080576}}, sa_flags = -721756224, sa_restorer = 0x7fa888023b30}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fa8a31abde3 in g_assertion_message
    (domain=<optimized out>, file=<optimized out>, line=<optimized out>, func=0x5568d4fadfc0 <__func__.65087> "nemo_window_slot_open_location_full", message=<optimized out>) at gtestutils.c:2596
        lstr = "492\000\376\177\000\000\000\234\274Z\023\353\261Z\240\306e\327\000\000\000\000\352\327\372\324hU\000"
        s = 0x5568d797c8b0 "@\345\202\327hU"
#3  0x00007fa8a32066be in g_assertion_message_expr
    (domain=domain@entry=0x0, file=file@entry=0x5568d4fad8f0 "../src/nemo-window-manage-views.c", line=line@entry=492, func=func@entry=0x5568d4fadfc0 <__func__.65087> "nemo_window_slot_open_location_full", expr=expr@entry=0x5568d4fad7ea "target_window != NULL") at gtestutils.c:2619
        s = 0x5568d7977490 "assertion failed: (target_window != NULL)"
#4  0x00005568d4f12b9c in nemo_window_slot_open_location_full (slot=0x5568d765c6a0 [NemoWindowSlot], location=0x7fa888023b30, flags=(unknown: 0), new_selection=0x0, callback=0x0, user_data=0x0)
    at ../src/nemo-window-manage-views.c:492
        window = 0x5568d747a0d0 [NemoDesktopWindow]
        target_window = 0x0
        pane = <optimized out>
        target_slot = 0x0
        slot_flags = <optimized out>
        old_location = 0x0
        old_uri = <optimized out>
        new_uri = <optimized out>
        new_slot_position = <optimized out>
        l = <optimized out>
        use_same = <optimized out>
        is_desktop = <optimized out>
        app = <optimized out>
        __func__ = "nemo_window_slot_open_location_full"
#5  0x00005568d4f1f405 in nemo_window_split_view_on (window=0x5568d747a0d0 [NemoDesktopWindow]) at ../src/nemo-window.c:1994
        slot = 0x5568d765c6a0 [NemoWindowSlot]
        old_active_slot = 0x5568d765c1a0 [NemoWindowSlot]
        location = 0x7fa888023b30
#6  0x00005568d4f159f5 in action_split_view_callback (action=<optimized out>, user_data=<optimized out>) at ../src/nemo-window-menus.c:567
        slot = <optimized out>
        window = 0x5568d747a0d0 [NemoDesktopWindow]
        is_active = 1
#10 0x00007fa8a32dd923 in <emit signal ??? on instance 0x7fa87c00b6e0 [GtkToggleAction]> (instance=instance@entry=0x7fa87c00b6e0, signal_id=<optimized out>, detail=detail@entry=0)
    at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe15bc4a30, reg_save_area = 0x7ffe15bc4970}}
    #7  0x00007fa8a32c0c9d in g_closure_invoke (closure=0x5568d750fa90, return_value=0x0, n_param_values=1, param_values=0x7ffe15bc4790, invocation_hint=0x7ffe15bc4710) at gclosure.c:810
                marshal = 0x7fa8a32c2f80 <g_cclosure_marshal_VOID__VOID>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x5568d750fa70
                __func__ = "g_closure_invoke"
    #8  0x00007fa8a32d4203 in signal_emit_unlocked_R
    (node=node@entry=0x5568d74a4af0, detail=detail@entry=0, instance=instance@entry=0x7fa87c00b6e0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe15bc4790) at gsignal.c:3635
                tmp = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
                handler = 0x5568d7534540
                accumulator = 0x0
                emission = {next = 0x7ffe15bc4ba0, instance = 0x7fa87c00b6e0, ihint = {signal_id = 356, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
                class_closure = 0x5568d74a4a80
                hlist = <optimized out>
                handler_list = 0x5568d7534540
                return_accu = 0x0
                accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 356
                max_sequential_handler_number = 6655
                return_value_altered = 1
    #9  0x00007fa8a32dd32a in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe15bc4950) at gsignal.c:3391
                instance_and_params = 0x7ffe15bc4790
                signal_return_type = <optimized out>
                param_values = 0x7ffe15bc47a8
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#11 0x00007fa8a384fdc4 in _gtk_action_emit_activate (action=0x7fa87c00b6e0 [GtkToggleAction]) at deprecated/gtkaction.c:909
        group = 0x5568d747f5c0 [GtkActionGroup]
#12 0x00007fa8a3850361 in closure_accel_activate (closure=0x5568d750f910, return_value=0x7ffe15bc4bd0, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=<optimized out>) at deprecated/gtkaction.c:1865
        param_values = <optimized out>
        return_value = 0x7ffe15bc4bd0
        closure = 0x5568d750f910
        n_param_values = <optimized out>
        invocation_hint = <optimized out>
        marshal_data = <optimized out>
#16 0x00007fa8a32dd923 in <emit signal accel-activate:F3 on instance 0x5568d7489320 [GtkAccelGroup]> (instance=instance@entry=0x5568d7489320, signal_id=<optimized out>, detail=detail@entry=2277) at gsignal.c:3447
        var_args = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffe15bc4f20, reg_save_area = 0x7ffe15bc4e60}}
    #13 0x00007fa8a32c0c9d in g_closure_invoke (closure=0x5568d750f910, return_value=0x7ffe15bc4bd0, n_param_values=4, param_values=0x7ffe15bc4c30, invocation_hint=0x7ffe15bc4bb0) at gclosure.c:810
                marshal = 0x7fa8a3850330 <closure_accel_activate>
                marshal_data = 0x0
                in_marshal = 0
                real_closure = 0x5568d750f8f0
                __func__ = "g_closure_invoke"
    #14 0x00007fa8a32d4203 in signal_emit_unlocked_R (node=node@entry=0x5568d7488860, detail=detail@entry=2277, instance=instance@entry=0x5568d7489320, emission_return=emission_return@entry=0x7ffe15bc4d90, instance_and_params=instance_and_params@entry=0x7ffe15bc4c30) at gsignal.c:3635
                tmp = <optimized out>
                handler = 0x5568d7572400
                accumulator = 0x5568d749ffc0
                emission = {next = 0x7ffe15bc51c0, instance = 0x5568d7489320, ihint = {signal_id = 350, detail = 2277, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x4 [void]}
                class_closure = 0x0
                hlist = <optimized out>
                handler_list = 0x5568d75040c0
                return_accu = 0x7ffe15bc4bd0
                accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                signal_id = 350
                max_sequential_handler_number = 6655
                return_value_altered = 0
    #15 0x00007fa8a32dc9a3 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe15bc4e40) at gsignal.c:3401
                return_value = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
                error = 0x0
                rtype = 0x14 [gboolean]
                static_scope = 0
                instance_and_params = 0x7ffe15bc4c30
                signal_return_type = <optimized out>
                param_values = 0x7ffe15bc4c48
                node = <optimized out>
                i = <optimized out>
                n_params = <optimized out>
                __func__ = "g_signal_emit_valist"
#17 0x00007fa8a38a85dc in gtk_accel_group_activate (accel_group=0x5568d7489320 [GtkAccelGroup], accel_quark=accel_quark@entry=2277, acceleratable=acceleratable@entry=0x5568d747a0d0 [NemoDesktopWindow], accel_key=accel_key@entry=65472, accel_mods=accel_mods@entry=0) at gtkaccelgroup.c:910
        was_handled = 0
        __func__ = "gtk_accel_group_activate"
#18 0x00007fa8a38a9f0d in gtk_accel_groups_activate (object=object@entry=0x5568d747a0d0 [NemoDesktopWindow], accel_key=65472, accel_mods=0) at gtkaccelgroup.c:948
        accel_name = <optimized out>
        accel_quark = 2277
        slist = 0x5568d702f760 = {0x5568d7489320}
        __func__ = "gtk_accel_groups_activate"
#19 0x00007fa8a3b4ad62 in gtk_window_activate_key (window=window@entry=0x5568d747a0d0 [NemoDesktopWindow], event=event@entry=0x7fa88400ab30) at gtkwindow.c:11990
        key_hash = <optimized out>
        found_entry = 0x5568d7511860
        enable_accels = 1
        enable_mnemonics = 1
        __func__ = "gtk_window_activate_key"
#20 0x00007fa8a3b4b045 in gtk_window_key_press_event (widget=0x5568d747a0d0 [NemoDesktopWindow], event=0x7fa88400ab30) at gtkwindow.c:8196
        window = 0x5568d747a0d0 [NemoDesktopWindow]
        handled = 0
#21 0x00007fa8a3b797e8 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x5568d6ea8d20, return_value=0x7ffe15bc51f0, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x5568d6ea8d50) at gtkmarshalers.c:129
        cc = 0x5568d6ea8d20
        data1 = 0x5568d747a0d0
        data2 = <optimized out>
        callback = <optimized out>
        v_return = <optimized out>
        arg0 = 0x7fa88400ab30
        args_copy = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7ffe15bc53a0, reg_save_area = 0x7ffe15bc52e0}}
        __func__ = "_gtk_marshal_BOOLEAN__BOXEDv"
#22 0x00007fa8a32c0ef6 in _g_closure_invoke_va (closure=0x5568d6ea8d20, return_value=0x7ffe15bc51f0, instance=0x5568d747a0d0, args=0x7ffe15bc52c0, n_params=1, param_types=0x5568d6ea8d50) at gclosure.c:873
        marshal = 0x7fa8a32bf0d0 <g_type_class_meta_marshalv>
        marshal_data = 0x1b0
        in_marshal = 0
        real_closure = 0x5568d6ea8d00
        __func__ = "_g_closure_invoke_va"
#23 0x00007fa8a32dcda4 in g_signal_emit_valist (instance=0x5568d747a0d0, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe15bc52c0) at gsignal.c:3300
        return_accu = 0x7ffe15bc51f0
        accu = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x5568d6ea9090
        emission = {next = 0x0, instance = 0x5568d747a0d0, ihint = {signal_id = 83, detail = 0, run_type = G_SIGNAL_RUN_LAST}, state = EMISSION_RUN, chain_type = 0x5568d7477240 [NemoDesktopWindow/NemoWindow/GtkApplicationWindow/GtkWindow/GtkBin/GtkContainer/GtkWidget/GInitiallyUnowned]}
        signal_id = 83
        instance_type = 0x5568d7477240 [NemoDesktopWindow/NemoWindow/GtkApplicationWindow/GtkWindow/GtkBin/GtkContainer/GtkWidget/GInitiallyUnowned]
        emission_return = {g_type = 0x14 [gboolean], data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x14 [gboolean]
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = 0x5568d6ea8d70
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#24 0x00007fa8a32dd923 in g_signal_emit (instance=instance@entry=0x5568d747a0d0, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe15bc53a0, reg_save_area = 0x7ffe15bc52e0}}
#25 0x00007fa8a3b26664 in gtk_widget_event_internal (widget=0x5568d747a0d0 [NemoDesktopWindow], event=0x7fa88400ab30) at gtkwidget.c:7744
        signal_num = <optimized out>
        return_val = <optimized out>
        handled = 0
        __func__ = "gtk_widget_event_internal"
#26 0x00007fa8a39e2a11 in propagate_event (widget=0x5568d747a0d0 [NemoDesktopWindow], event=0x7fa88400ab30, captured=<optimized out>, topmost=0x0) at gtkmain.c:2675
        window = 0x5568d747a0d0 [NemoDesktopWindow]
        handled_event = <optimized out>
#27 0x00007fa8a39e4af3 in gtk_main_do_event (event=<optimized out>) at gtkmain.c:1915
        grab_widget = <optimized out>
        window_group = <optimized out>
        rewritten_event = <optimized out>
        device = <optimized out>
        tmp_list = <optimized out>
        event_widget = <optimized out>
        topmost_widget = <optimized out>
        event = 0x7fa88400ab30
        __func__ = "gtk_main_do_event"
        __func__ = "gtk_main_do_event"
#28 0x00007fa8a36d4a39 in _gdk_event_emit (event=event@entry=0x7fa88400ab30) at gdkevents.c:73
#29 0x00007fa8a3706446 in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at gdkeventsource.c:367
        display = <optimized out>
        event = 0x7fa88400ab30
#30 0x00007fa8a31de26d in g_main_dispatch (context=0x5568d6e5fbb0) at gmain.c:3182
        dispatch = 0x7fa8a3706420 <gdk_event_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = 0x0
        need_destroy = <optimized out>
        source = 0x5568d6e95760
        current = 0x5568d6ee86b0
        i = 0
        __func__ = "g_main_dispatch"
#31 0x00007fa8a31de26d in g_main_context_dispatch (context=context@entry=0x5568d6e5fbb0) at gmain.c:3847
#32 0x00007fa8a31de638 in g_main_context_iterate (context=context@entry=0x5568d6e5fbb0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3920
        max_priority = 2147483647
        timeout = 4663
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x5568d6e61f60
#33 0x00007fa8a31de6d0 in g_main_context_iteration (context=context@entry=0x5568d6e5fbb0, may_block=may_block@entry=1) at gmain.c:3981
        retval = <optimized out>
#34 0x00007fa8a33ad415 in g_application_run (application=0x5568d6e591c0 [NemoDesktopApplication], argc=<optimized out>, argv=0x7ffe15bc5728) at gapplication.c:2470
        arguments = 0x5568d6e58800
        status = 0
        context = 0x5568d6e5fbb0
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#35 0x00005568d4e9e102 in main (argc=1, argv=0x7ffe15bc5728) at ../src/nemo-desktop-main.c:101
        retval = <optimized out>
        application = 0x5568d6e591c0 [NemoDesktopApplication]
(gdb)
```

**Comment by jaszhix** [comment]
Ah, my mistake, I was thinking of just nemo. Though after testing, nothing happens when I press F3 with all windows minimized.

**Comment by parnikkapore** [comment]
Bump!
