### ISSUE TITLE
Coredump when trying to rename or create a new folder in Icon View

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1978]
```
 * Nemo version (nemo --version)
nemo 4.0.0
 * Is issue with desktop or windowed nemo?
Windowed
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
 * Graphics hardware *and* driver used
Nvidia, 410.66
 * 32 or 64 bit
64-bit
 ```

**Issue**
When in Icon view, `nemo` crashes when trying to rename a folder. Crash also happens when I try to create a new folder and name it immediately.
This is not a new bug and has been present in previous versions too. I do not know what causes it but I think the crash happens when `nemo` is still generating previews for files in the folder.

**Steps to reproduce**

0) Make sure you're in Icon View
1) Enter a new folder that has lots of items in it and make sure the thumbnail cache is empty
2) Quickly Create a new folder (Shift+Ctrl+n)
3) Name it something and press Enter.

`nemo` will crash if `nemo` is still generating previews when you hit the enter key.
I am unable to provide a 100% reproducible crash because it doesn't happen every time. But given the above steps, it should crash often.

**Other information**

gdb trace:

````
$ gdb /usr/bin/nemo
GNU gdb (GDB) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/nemo...(no debugging symbols found)...done.
(gdb) run
Starting program: /usr/bin/nemo 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffef43b700 (LWP 20781)]
[New Thread 0x7fffeec3a700 (LWP 20782)]
[New Thread 0x7fffee375700 (LWP 20783)]
[New Thread 0x7fffedb74700 (LWP 20784)]
[Nemo Terminal] I: Initializing the Nemo extension
[New Thread 0x7fffdffff700 (LWP 20786)]
[New Thread 0x7fffdf7fe700 (LWP 20787)]
[New Thread 0x7fffdeffd700 (LWP 20788)]
[Detaching after fork from child process 20789]
[New Thread 0x7fffdcf35700 (LWP 20806)]
[New Thread 0x7fffdcd34700 (LWP 20807)]
[New Thread 0x7fffdcb33700 (LWP 20808)]
[New Thread 0x7fffdc932700 (LWP 20809)]
[New Thread 0x7fffdc731700 (LWP 20810)]
[New Thread 0x7fffdc530700 (LWP 20811)]
[New Thread 0x7fffdc32f700 (LWP 20812)]
[New Thread 0x7fffb3fff700 (LWP 20813)]
[Detaching after fork from child process 20814]
Nemo-Share-Message: 11:47:38.360: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: usershares are currently disabled

[Thread 0x7fffdeffd700 (LWP 20788) exited]
[Thread 0x7fffedb74700 (LWP 20784) exited]
[Thread 0x7fffdf7fe700 (LWP 20787) exited]
[New Thread 0x7fffdf7fe700 (LWP 20929)]
[Thread 0x7fffdf7fe700 (LWP 20929) exited]
[New Thread 0x7fffdf7fe700 (LWP 21051)]
[New Thread 0x7fffedb74700 (LWP 21057)]
[Detaching after fork from child process 21072]
[Detaching after fork from child process 21075]
[Detaching after fork from child process 21078]
[Detaching after fork from child process 21081]
[Detaching after fork from child process 21084]
[Detaching after fork from child process 21087]
[Detaching after fork from child process 21112]
[Detaching after fork from child process 21119]
[New Thread 0x7fffdeffd700 (LWP 21120)]
[Detaching after fork from child process 21143]
[Detaching after fork from child process 21146]
[Detaching after fork from child process 21149]
[Detaching after fork from child process 21172]
[Detaching after fork from child process 21195]
[Detaching after fork from child process 21198]
[Detaching after fork from child process 21205]
[Detaching after fork from child process 21208]
[Detaching after fork from child process 21211]
[Detaching after fork from child process 21214]
[Detaching after fork from child process 21217]

(gdk-pixbuf-thumbnailer:21217): GdkPixbuf-CRITICAL **: 11:47:49.154: gdk_pixbuf_save: assertion 'error == NULL || *error == NULL' failed

[Detaching after fork from child process 21220]
[Detaching after fork from child process 21223]
[Detaching after fork from child process 21226]
[Detaching after fork from child process 21229]
[Detaching after fork from child process 21232]
[Detaching after fork from child process 21236]
[Detaching after fork from child process 21239]
[Detaching after fork from child process 21242]
[Detaching after fork from child process 21245]
[Detaching after fork from child process 21249]
[Detaching after fork from child process 21252]
[Detaching after fork from child process 21255]
[Detaching after fork from child process 21262]
[Detaching after fork from child process 21265]
[Detaching after fork from child process 21268]
[Detaching after fork from child process 21271]
[Detaching after fork from child process 21274]
[Detaching after fork from child process 21277]
[Detaching after fork from child process 21280]
[Detaching after fork from child process 21283]
[Detaching after fork from child process 21286]
[Detaching after fork from child process 21289]
[Detaching after fork from child process 21292]
[Detaching after fork from child process 21295]
[Detaching after fork from child process 21298]
[Detaching after fork from child process 21301]
[Detaching after fork from child process 21486]
[Detaching after fork from child process 21509]
[Detaching after fork from child process 21512]
[Detaching after fork from child process 21515]
[Detaching after fork from child process 21518]
[Detaching after fork from child process 21521]
[Detaching after fork from child process 21552]
[Detaching after fork from child process 21577]
[Detaching after fork from child process 21602]
[Detaching after fork from child process 21627]
[Detaching after fork from child process 21652]
[Detaching after fork from child process 21691]
[Detaching after fork from child process 21694]
[Detaching after fork from child process 21697]
[Detaching after fork from child process 21700]

[Detaching after fork from child process 21820]
[Detaching after fork from child process 21823]
[Detaching after fork from child process 21826]
[Detaching after fork from child process 21829]
[Detaching after fork from child process 21832]
[Thread 0x7fffdeffd700 (LWP 21120) exited]
[Thread 0x7fffedb74700 (LWP 21057) exited]
[Detaching after fork from child process 21835]
[New Thread 0x7fffedb74700 (LWP 21838)]
[New Thread 0x7fffdeffd700 (LWP 21839)]
[Detaching after fork from child process 21840]
[Detaching after fork from child process 21855]
[Detaching after fork from child process 21858]
[Detaching after fork from child process 21867]
[Detaching after fork from child process 21870]
[Detaching after fork from child process 21871]
Nemo-Share-Message: 11:47:55.366: Called "net usershare info" but it failed: 'net usershare' returned error 255: net usershare: usershares are currently disabled

[Detaching after fork from child process 21875]
[Detaching after fork from child process 21878]
[Detaching after fork from child process 21881]
[Detaching after fork from child process 21885]
[Detaching after fork from child process 21909]
[Detaching after fork from child process 21912]
[Detaching after fork from child process 21915]
[Detaching after fork from child process 21924]
[Detaching after fork from child process 21961]
[Detaching after fork from child process 21988]
[Detaching after fork from child process 22027]
[Detaching after fork from child process 22030]
[Detaching after fork from child process 22033]
[Detaching after fork from child process 22036]
[Detaching after fork from child process 22039]
[Detaching after fork from child process 22042]
[Detaching after fork from child process 22045]
[Detaching after fork from child process 22048]
[Detaching after fork from child process 22051]
[Detaching after fork from child process 22058]
[Detaching after fork from child process 22061]
[Detaching after fork from child process 22084]
[Detaching after fork from child process 22087]
[Detaching after fork from child process 22091]
[Detaching after fork from child process 22094]
[Detaching after fork from child process 22097]
[Detaching after fork from child process 22100]
[Detaching after fork from child process 22103]
[Detaching after fork from child process 22107]
[Detaching after fork from child process 22111]
[Detaching after fork from child process 22114]
[Detaching after fork from child process 22117]
[Detaching after fork from child process 22199]
[Detaching after fork from child process 22206]
[Detaching after fork from child process 22209]
[Detaching after fork from child process 22212]
[Detaching after fork from child process 22215]
[Detaching after fork from child process 22218]
[Detaching after fork from child process 22221]
[Detaching after fork from child process 22224]
[Detaching after fork from child process 22227]
[Detaching after fork from child process 22230]
[Detaching after fork from child process 22233]
[Detaching after fork from child process 22236]
[Detaching after fork from child process 22239]
[Detaching after fork from child process 22242]

Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff733ed39 in g_type_check_instance () from /usr/lib/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff733ed39 in g_type_check_instance () at /usr/lib/libgobject-2.0.so.0
#1  0x00007ffff734fae4 in g_signal_connect_data () at /usr/lib/libgobject-2.0.so.0
#2  0x000055555564b22e in  ()
#3  0x000055555564fbcb in  ()
#4  0x0000555555655b2e in  ()
#5  0x00007ffff7bd7835 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff734ea47 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff734fa80 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7b831f5 in  () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff7ba46dc in gtk_window_propagate_key_event () at /usr/lib/libgtk-3.so.0
#10 0x0000555555605c48 in  ()
#11 0x00007ffff7bd773c in  () at /usr/lib/libgtk-3.so.0
#12 0x00007ffff735e3d5 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff734a99f in  () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff734e5ed in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff734fa80 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff7b831f5 in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff7a3b029 in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff7a3d15c in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff773aa06 in  () at /usr/lib/libgdk-3.so.0
#20 0x00007ffff776c755 in  () at /usr/lib/libgdk-3.so.0
#21 0x00007ffff72743cf in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff7275f89 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff7275fce in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff741d7ee in g_application_run () at /usr/lib/libgio-2.0.so.0
#25 0x0000555555581122 in  ()
#26 0x00007ffff6549223 in __libc_start_main () at /usr/lib/libc.so.6
#27 0x000055555558116e in  ()
(gdb) 
````

Coredump: 

````
Process 14559 (nemo) of user 1000 dumped core.
Stack trace of thread 14559:
#0  0x00007fa123a69d39 g_type_check_instance (libgobject-2.0.so.0)
#1  0x00007fa123a7aae4 g_signal_connect_data (libgobject-2.0.so.0)
#2  0x000055a1e92cc22e n/a (nemo)
#3  0x000055a1e92d0bcb n/a (nemo)
#4  0x000055a1e92d6b2e n/a (nemo)
#5  0x00007fa124302835 n/a (libgtk-3.so.0)
#6  0x00007fa123a79a47 g_signal_emit_valist (libgobject-2.0.so.0)
#7  0x00007fa123a7aa80 g_signal_emit (libgobject-2.0.so.0)
#8  0x00007fa1242ae1f5 n/a (libgtk-3.so.0)
#9  0x00007fa1242cf6dc gtk_window_propagate_key_event (libgtk-3.so.0)
#10 0x000055a1e9286c10 n/a (nemo)
#11 0x00007fa12430273c n/a (libgtk-3.so.0)
#12 0x00007fa123a893d5 g_closure_invoke (libgobject-2.0.so.0)
#13 0x00007fa123a7599f n/a (libgobject-2.0.so.0)
#14 0x00007fa123a795ed g_signal_emit_valist (libgobject-2.0.so.0)
#15 0x00007fa123a7aa80 g_signal_emit (libgobject-2.0.so.0)
#16 0x00007fa1242ae1f5 n/a (libgtk-3.so.0)
#17 0x00007fa124166029 n/a (libgtk-3.so.0)
#18 0x00007fa12416815c gtk_main_do_event (libgtk-3.so.0)
#19 0x00007fa123e65a06 n/a (libgdk-3.so.0)
#20 0x00007fa123e97755 n/a (libgdk-3.so.0)
#21 0x00007fa12399f3cf g_main_context_dispatch (libglib-2.0.so.0)
#22 0x00007fa1239a0f89 n/a (libglib-2.0.so.0)
#23 0x00007fa1239a0fce g_main_context_iteration (libglib-2.0.so.0)
#24 0x00007fa123b487ee g_application_run (libgio-2.0.so.0)
#25 0x000055a1e9202122 n/a (nemo)
#26 0x00007fa122c74223 __libc_start_main (libc.so.6)
#27 0x000055a1e920216e n/a (nemo)
Stack trace of thread 14691:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14877:
#0  0x00007fa122d464ed syscall (libc.so.6)
#1  0x00007fa12394ff61 g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fa1239cdcc3 n/a (libglib-2.0.so.0)
#3  0x00007fa123971d2b n/a (libglib-2.0.so.0)
#4  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#5  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#6  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14693:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14690:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14661:
#0  0x00007fa122d40c21 __poll (libc.so.6)
#1  0x00007fa1239a0ee0 n/a (libglib-2.0.so.0)
#2  0x00007fa1239a1f62 g_main_loop_run (libglib-2.0.so.0)
#3  0x00007fa123b09c28 n/a (libgio-2.0.so.0)
#4  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#5  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#6  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14709:
#0  0x00007fa122e25d42 waitpid (libpthread.so.0)
#1  0x00007fa1239577c0 g_spawn_sync (libglib-2.0.so.0)
#2  0x00007fa123957ad0 g_spawn_command_line_sync (libglib-2.0.so.0)
#3  0x00007fa124687b51 gnome_desktop_thumbnail_factory_generate_thumbnail (libcinnamon-desktop.so.4)
#4  0x000055a1e92e7885 n/a (nemo)
#5  0x00007fa123b6fcd6 n/a (libgio-2.0.so.0)
#6  0x00007fa123971bd6 n/a (libglib-2.0.so.0)
#7  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14660:
#0  0x00007fa122d40c21 __poll (libc.so.6)
#1  0x00007fa1239a0ee0 n/a (libglib-2.0.so.0)
#2  0x00007fa1239a0fce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fa1239a1022 n/a (libglib-2.0.so.0)
#4  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#5  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#6  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14686:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14670:
#0  0x00007fa12397a917 g_slist_prepend (libglib-2.0.so.0)
#1  0x00007fa12397f812 g_strsplit (libglib-2.0.so.0)
#2  0x00007fa123ba2e80 g_file_attribute_matcher_new (libgio-2.0.so.0)
#3  0x00007fa123afa504 n/a (libgio-2.0.so.0)
#4  0x00007fa123bb3e02 n/a (libgio-2.0.so.0)
#5  0x00007fa123b6fcd6 n/a (libgio-2.0.so.0)
#6  0x00007fa123971bd6 n/a (libglib-2.0.so.0)
#7  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14666:
#0  0x00007fa122d40c21 __poll (libc.so.6)
#1  0x00007fa1239a0ee0 n/a (libglib-2.0.so.0)
#2  0x00007fa1239a0fce g_main_context_iteration (libglib-2.0.so.0)
#3  0x00007fa1246c9bde n/a (libdconfsettings.so)
#4  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#5  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#6  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14689:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14692:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14687:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14688:
#0  0x00007fa122e21afc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
#1  0x00007fa101287a42 n/a (librsvg-2.so.2)
#2  0x00007fa1012818f4 n/a (librsvg-2.so.2)
#3  0x00007fa101282176 n/a (librsvg-2.so.2)
#4  0x00007fa10128405c n/a (librsvg-2.so.2)
#5  0x00007fa10138db1a n/a (librsvg-2.so.2)
#6  0x00007fa101283adb n/a (librsvg-2.so.2)
#7  0x00007fa101388ceb n/a (librsvg-2.so.2)
#8  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#9  0x00007fa122d4bb23 __clone (libc.so.6)
Stack trace of thread 14878:
#0  0x00007fa122d464ed syscall (libc.so.6)
#1  0x00007fa12394ff61 g_cond_wait_until (libglib-2.0.so.0)
#2  0x00007fa1239cdcc3 n/a (libglib-2.0.so.0)
#3  0x00007fa123971d2b n/a (libglib-2.0.so.0)
#4  0x00007fa12396a3eb n/a (libglib-2.0.so.0)
#5  0x00007fa122e1ba9d start_thread (libpthread.so.0)
#6  0x00007fa122d4bb23 __clone (libc.so.6)
-- Subject: Process 14559 (nemo) dumped core
````

**Comment by leigh123linux** [comment]
Feel free to reopen once you have provided usable backtrace with required debugging symbols installed.
