### ISSUE TITLE
Cannot install latest Nemo version on Ubuntu

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#2007]
```
 * Nemo version 3.9.0
 * Windowed Nemo (GNOME 3.30.1)
 * Distribution - Ubuntu 18.10 
 * 00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	Subsystem: Hewlett-Packard Company HD Graphics 5500
	Kernel driver in use: i915
	Kernel modules: i915
 * 64 bit
 ```

**Issue**
Cannot install the latest Nemo version (Tag 4.0.6) or it's dependency Cinnamon-Desktop (Tag 4.0.1) using Meson and Ninja

**Steps to reproduce**
```
roey@hpx360-13:~$ meson nemo ~/github/nemo
The Meson build system
Version: 0.47.2
Source dir: /home/roey/github/nemo
Build dir: /home/roey/nemo
Build type: native build
Project name: nemo
Project version: 4.0.6
Native C compiler: cc (gcc 8.2.0 "cc (Ubuntu 8.2.0-7ubuntu1) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Has header "malloc.h": YES
Has header "sys/mount.h": YES
Has header "sys/param.h": YES
Has header "sys/vfs.h": YES
Has header "X11/XF86keysym.h": YES
Checking for function "mallopt" : YES
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gtk+-3.0 found: YES 3.24.1
Native dependency gio-2.0 found: YES 2.58.1
Native dependency gio-unix-2.0 found: YES 2.58.1
Native dependency glib-2.0 found: YES 2.58.1
Native dependency gmodule-no-export-2.0 found: YES 2.58.1
Native dependency gobject-2.0 found: YES 2.58.1
Native dependency gobject-introspection-1.0 found: YES 1.58.0
Native dependency libnotify found: YES 0.7.7

meson.build:80:0: ERROR:  Native dependency 'cinnamon-desktop' not found
A full log can be found at /home/roey/nemo/meson-logs/meson-log.txt

roey@hpx360-13:~$ meson cinnamon-desktop ~/github/cinnamon-desktop/
The Meson build system
Version: 0.47.2
Source dir: /home/roey/github/cinnamon-desktop
Build dir: /home/roey/cinnamon-desktop
Build type: native build
Project name: cinnamon-desktop
Project version: 4.0.1
Native C compiler: cc (gcc 8.2.0 "cc (Ubuntu 8.2.0-7ubuntu1) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gdk-pixbuf-2.0 found: YES 2.38.0
Native dependency gio-2.0 found: YES 2.58.1
Native dependency glib-2.0 found: YES 2.58.1
Native dependency gtk+-3.0 found: YES 3.24.1
Native dependency x11 found: YES 1.6.7
Native dependency xext found: YES 1.3.3
Native dependency xkeyboard-config found: YES 2.23.1
Native dependency xkbfile found: YES 1.0.9
Native dependency xrandr found: YES 1.5.1
Native dependency gobject-2.0 found: YES 2.58.1
Native dependency libpulse found: YES 12.2
Native dependency libpulse-mainloop-glib found: YES 12.2
Checking for function "bind_textdomain_codeset" : YES
Has header "libintl.h": YES
Configuring config.h using configuration
Program meson_install_schemas.py found: YES (/usr/bin/python3 /home/roey/github/cinnamon-desktop/install-scripts/meson_install_schemas.py)
WARNING: Project targetting '>=0.37.0' but tried to use feature introduced in '0.41.0': variables arg in pkgconfig.generate
WARNING: Project targetting '>=0.37.0' but tried to use feature introduced in '0.41.0': custom pkgconfig variables
Native dependency gobject-introspection-1.0 found: YES 1.58.0
Configuring org.cinnamon.desktop.a11y.applications.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.a11y.keyboard.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.a11y.magnifier.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.a11y.mouse.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.background.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.default-applications.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.input-sources.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.interface.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.keybindings.media-keys.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.keybindings.wm.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.keybindings.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.lockdown.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.media-handling.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.notifications.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.privacy.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.screensaver.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.session.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.sound.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.thumbnail-cache.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.thumbnailers.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Configuring org.cinnamon.desktop.wm.preferences.gschema.xml.in using configuration
DEPRECATION: build_always is deprecated. Combine build_by_default and build_always_stale instead.
Message: 
        prefix:                       /usr/local
        exec_prefix:                  /usr/local
        libdir:                       lib/x86_64-linux-gnu
        bindir:                       bin
        sbindir:                      sbin
        sysconfdir:                   etc
        localstatedir:                /var/local
        datadir:                      share
        source code location:         /home/roey/github/cinnamon-desktop
        compiler:                     gcc
        debugging support:            debug
        Use *_DISABLE_DEPRECATED:     false
        Use PNP files:                internal: /usr/local/share/libcinnamon-desktop
        Use ALSA:                     false

Build targets in project: 33
WARNING: Project specifies a minimum meson_version '>=0.37.0' but uses features which were added in newer versions:
 * 0.41.0: {'variables arg in pkgconfig.generate', 'custom pkgconfig variables'}
Found ninja-1.8.2 at /usr/bin/ninja

roey@hpx360-13:~$ ninja cinnamon-desktop-gmo 
[0/1] Running external command cinnamon-desktop-gmo.
msgfmt: error while opening "/home/roey/po/af.gmo" for writing: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/meson", line 29, in <module>
    sys.exit(mesonmain.main())
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 379, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 316, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 232, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/gettext.py", line 109, in run
    return gen_gmo(src_sub, bld_sub, langs)
  File "/usr/lib/python3/dist-packages/mesonbuild/scripts/gettext.py", line 66, in gen_gmo
    '-o', os.path.join(bld_sub, l + '.gmo')])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['msgfmt', '/home/roey/github/cinnamon-desktop/po/af.po', '-o', '/home/roey/po/af.gmo']' returned non-zero exit status 1.
FAILED: meson-cinnamon-desktop-gmo 
/usr/bin/python3 /usr/bin/meson --internal commandrunner /home/roey/github/cinnamon-desktop /home/roey po /usr/bin/python3 /usr/bin/meson /usr/bin/python3 /usr/bin/meson --internal gettext gen_gmo
ninja: build stopped: subcommand failed.
```

**Expected behavior**
I want to install the latest version of Nemo file browser (with an option to add it's plugins) instead of Ubuntu's  Nautilus (i.e Nemo over GNOME) without the whole Cinnamon-Desktop environment (i.e linuxmint) if it's possible

**Other information**
I'm currently running Nemo v3.9.0 I've got as APT from this [PPA](https://launchpad.net/~gwendal-lebihan-dev/+ppa-packages) (which is now outdated) 

TNX

**Comment by mtwebster** [comment]
If you're on Ubuntu, just use dpkg-buildpackage:

The cinnamon-desktop package is not the full-blown cinnamon, it's just some various support libraries and settings schemas.  You'll also need the latest xapps library.

For each of the packages, first run:
```
sudo apt-get source cinnamon-desktop xapps nemo
```
You may need to add source repos to your apt sources.list.

From inside each git source of cinnamon-desktop and xapps:
```
dpkg-buildpackage
```
back up one directory, run `dpkg -i *.deb`

then go into nemo's source, same thing:
```
dpkg-buildpackage
```
again, back a folder and install the debs (you can re-install the others that are already there without harm)

I'm not entirely certain, but you may also need to build cinnamon-translations as well - it will tell you if so.

I'm surprised there isn't a ppa with the latest packages you can get (you could use our nightly ppa, but you'll eventually move to unstable there).

**Comment by leigh123linux** [comment]
Your using the wrong command to build cinnamon-desktop

https://github.com/linuxmint/cinnamon-desktop/blob/master/README
