### ISSUE TITLE
Segfault in List View

### ISSUE THREAD

**Issue by okaestne** [linuxmint/nemo#2018]
```
nemo 4.0.6
windowed nemo
Mint 19.1 Cinnamon
NVIDIA GTX 970, NVIDIA 415.25 (nouveau on live USB)
64bit
 ```

**Issue**

Nemo segfaults when I switch to list view in a certain folder (my Documents folder). Icon view and compact view work fine.

I was testing nemo a lot as I'm working on the folder-color-switcher plugin (will create PR if this isn't the cause).

As it saves the setting I have to issue the following commands to be able to open the folder again.
```
nemo -q
gio set --type=unset Documents metadata::nemo-default-view
```

Same issue when booted via live USB (same folder!).
Downgrading by manually installing the Mint tara package (nemo 3.8.6) -> no problem.

**Steps to reproduce**

Open folder, change to list view (Ctrl+2 or via menu, doesn't matter)

**Other information**

Folder contains just 4 folders right now. The backtrace below has something to do with dates. The icon view does render the dates correctly...

```
Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff56f445c in g_date_time_to_timezone ()
   from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff56f445c in g_date_time_to_timezone ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x000055555563c554 in nemo_file_get_date_as_string (file=<optimized out>, date_type=date_type@entry=NEMO_DATE_TYPE_CREATED, date_format=date_format@entry=NEMO_DATE_FORMAT_REGULAR) at ../../libnemo-private/nemo-file.c:4811
#2  0x00005555556408a2 in nemo_file_get_string_attribute_q (file=0x5555562c2fa0, attribute_q=2348) at ../../libnemo-private/nemo-file.c:6461
#3  0x0000555555640e20 in nemo_file_get_string_attribute_with_default_q (file=file@entry=0x5555562c2fa0, attribute_q=2348)
    at ../../libnemo-private/nemo-file.c:6573
#4  0x00005555555b5732 in nemo_list_model_get_value (tree_model=<optimized out>, iter=0x7fffc000aac0, column=16, value=0x7fffffffb330)
    at ../../src/nemo-list-model.c:416
#5  0x00007ffff71bd1f0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff56f9110 in g_hash_table_foreach ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff71bd0cb in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff71c2949 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff72be15f in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007ffff59e4346 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff59ff9ff in g_signal_emit_valist ()
    at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff5a0012f in g_signal_emit ()
---Type <return> to continue, or q <return> to quit---
   ct-2.0.so.0
#13 0x00007ffff71bec3a in gtk_cell_area_apply_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff73eda17 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff73ef03d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff73129e0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007ffff73da950 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff734038b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#23 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff733e681 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#29 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#30 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#31 0x00007ffff71a4a34 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#32 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#33 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#34 0x00007ffff71a7341 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#36 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#37 0x00007ffff72f21d0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#38 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#39 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff72f1fe1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#44 0x00007ffff71a4a34 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#45 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#46 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#47 0x00007ffff71a7341 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#49 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007ffff72e3112 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#51 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#52 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#53 0x00007ffff71a8b0c in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#54 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff72e58fc in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#56 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#57 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#58 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#59 0x00007ffff71a4a34 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#60 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#61 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#62 0x00007ffff71a7341 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#63 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#64 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#65 0x00007ffff72f21d0 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#66 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
---Type <return> to continue, or q <return> to quit---
#67 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#68 0x00007ffff72f1fe1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#69 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#70 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#71 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#72 0x00007ffff71a4a34 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#73 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#74 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#75 0x00007ffff71a7341 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#76 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#77 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#78 0x00007ffff72f2140 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#79 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#80 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#81 0x00007ffff72f1fe1 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#82 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#83 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#84 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#85 0x00007ffff72739f4 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#86 0x00007ffff71f5f2d in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#87 0x00007ffff71fab83 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#88 0x00007ffff7274a61 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#89 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#90 0x00007ffff71f0eea in gtk_container_propagate_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#91 0x00007ffff71f0fd2 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#92 0x00007ffff7417c8f in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#93 0x00007ffff7409eab in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#94 0x00007ffff7412f58 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#95 0x00007ffff72b71b9 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#96 0x00007ffff6dc8765 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#97 0x00007ffff6dd87e5 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#98 0x00007ffff6dd99e6 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#99 0x00007ffff6dd9be0 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#100 0x00007ffff59e410d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#101 0x00007ffff59f705e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#102 0x00007ffff59ff715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#103 0x00007ffff5a0012f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#104 0x00007ffff6dd1ac9 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#105 0x00007ffff6dbd080 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#106 0x00007ffff570ac73 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#107 0x00007ffff570a1f5 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#108 0x00007ffff570a5c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#109 0x00007ffff570a64c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#110 0x00007ffff5ccae3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#111 0x0000555555588bb2 in main (argc=1, argv=0x7fffffffde88) at ../../src/nemo-main.c:104
```

**Comment by okaestne** [comment]
closed as discussion takes place in #2019
