### ISSUE TITLE
nemo - treeview sidepanel gets stuck on 'loading' and eventually segfaults if main pane has a fully expanded list view

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo#2288]
```
 * Nemo version 4.4.2)
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution - Mint 19.3
 * Graphics hardware *and* driver used
Graphics:  Device-1: Intel driver: i915 v: kernel 
           Display: x11 server: X.Org 1.20.4 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel UHD Graphics (Whiskey Lake 3x8 GT2) v: 4.5 Mesa 19.0.8 

 * 64 bit
 ```

**Issue**
The treeview side panel can get stuck on 'loading' on certain circumstances and nemo eventually segfaults.

**Steps to reproduce**

Open nemo in list view and with the side pane in treeview mode. In the main pain go up one level to /home

Highlight a user name in the main pane and then press the * key multiple times until all sub directories are expanded. Then try and expand the Home entry in the sidebar - note it gets stuck on loading and after 15 to 30 seconds nemo will segfault.

![screenshot-window-2019-12-28-054704](https://user-images.githubusercontent.com/29017677/71539580-4cb31900-2936-11ea-8856-61261bb1b38f.png)

**Expected behaviour**
No crash

**Other information**

Terminal output - 

```
steve@steve-Inspiron-5580:~$ nemo --debug
(nemo:30822): Gtk-DEBUG: 05:46:28.199: Connecting to session manager
(nemo:30822): Gtk-DEBUG: 05:46:28.200: Registering client 'org.Nemo' ''
(nemo:30822): Gtk-DEBUG: 05:46:28.201: Registered client at '/org/gnome/SessionManager/Client34'

** (nemo:30822): WARNING **: 05:46:28.210: Current gtk theme is not known to have nemo support (Cinnamox-Rhino) - checking...
Initializing nemo-image-converter extension
** (nemo:30822): DEBUG: 05:46:28.845: Open called on the GApplication instance; 1 files

** (nemo:30822): CRITICAL **: 05:47:31.456: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed
sys:1: Warning: g_value_transform: assertion 'G_IS_VALUE (src_value)' failed
sys:1: Warning: unable to set property 'surface' of type 'CairoSurface' from value of type '(null)'

** (nemo:30822): CRITICAL **: 05:47:31.456: nemo_list_model_get_value: assertion 'model->details->stamp == iter->stamp' failed
sys:1: Warning: ../../../../gobject/gtype.c:4265: type id '0' is invalid
sys:1: Warning: can't peek value table for type '<invalid>' which is not currently referenced
Segmentation fault (core dumped)
```
Stack trace https://termbin.com/udeh

**Comment by leigh123linux** [comment]
The stack trace is nearly useless due to missing gtk and glib symbols.

**Comment by okaestne** [comment]
I can reproduce this as well. Does this stacktrace help a bit more?

```
Thread 1 (Thread 0x7ffff7fa0ac0 (LWP 25546)):
#0  0x00007ffff73c354d in gtk_tree_model_get_valist (tree_model=tree_model@entry=0x555555afab40, iter=iter@entry=0x55555879d820, var_args=var_args@entry=0x7fffffffd450) at ../../../../gtk/gtktreemodel.c:1800
#1  0x00007ffff73c383d in gtk_tree_model_get (tree_model=tree_model@entry=0x555555afab40, iter=iter@entry=0x55555879d820) at ../../../../gtk/gtktreemodel.c:1762
#2  0x00005555555b81c5 in filename_cell_data_func (column=<optimized out>, renderer=0x555556158d20, model=0x555555afab40, iter=0x55555879d820, view=0x555556489650) at ../../src/nemo-list-view.c:2132
#3  0x00007ffff71b9683 in apply_cell_attributes (renderer=0x555556158d20, info=0x7fffd0041290, data=0x7fffffffd640) at ../../../../gtk/gtkcellarea.c:1257
#4  0x00007ffff56f41a0 in g_hash_table_foreach () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff71b951b in gtk_cell_area_real_apply_attributes (area=<optimized out>, tree_model=0x555555afab40, iter=0x55555879d820, is_expander=<optimized out>, is_expanded=<optimized out>) at ../../../../gtk/gtkcellarea.c:1286
#6  0x00007ffff71bed99 in gtk_cell_area_box_apply_attributes (area=<optimized out>, tree_model=tree_model@entry=0x555555afab40, iter=iter@entry=0x55555879d820, is_expander=<optimized out>, is_expanded=<optimized out>)
    at ../../../../gtk/gtkcellareabox.c:1310
#7  0x00007ffff72ba7ff in _gtk_marshal_VOID__OBJECT_BOXED_BOOLEAN_BOOLEANv (closure=0x55555616aec0, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55555616a870) at ../../../../gtk/gtkmarshalers.c:4982
#8  0x00007ffff59e0346 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff59fb9ff in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff59fc12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff71bb08a in gtk_cell_area_apply_attributes (area=0x555556409c10, tree_model=0x555555afab40, iter=0x7fffffffdb60, is_expander=0, is_expanded=0) at ../../../../gtk/gtkcellarea.c:2373
#12 0x00007ffff73db43b in validate_row (tree_view=tree_view@entry=0x5555561667c0, tree=tree@entry=0x555558d4f530, node=node@entry=0x555558d4e6a0, iter=iter@entry=0x7fffffffdb60, path=path@entry=0x7fffbc005c50)
    at ../../../../gtk/gtktreeview.c:6402
#13 0x00007ffff73e315a in do_validate_rows (tree_view=0x5555561667c0, queue_resize=1) at ../../../../gtk/gtktreeview.c:6970
#14 0x00007ffff73e35fe in validate_rows (tree_view=0x5555561667c0) at ../../../../gtk/gtktreeview.c:7131
#15 0x00007ffff6db9080 in gdk_threads_dispatch (data=0x5555568f3b20) at ../../../../gdk/gdk.c:743
#16 0x00007ffff5705285 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff5705650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff57056dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff5cc6e3d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#20 0x000055555558a242 in main (argc=2, argv=0x7fffffffde78) at ../../src/nemo-main.c:104
```

**Comment by smurphos** [comment]
> The stack trace is nearly useless due to missing gtk and glib symbols.
Oops - forgot this was a fresh install...

This one is from trying to expand the Filesystem in the side bar with /usr/ fully expanded in the main pane.

https://termbin.com/uos4

I can also invoke a crash by highlighting my username whilst browsing /home/ in list view and holding the * key to expand the entire treeview. 

https://termbin.com/pk6o
