### ISSUE TITLE
Copy dialog stalls indefinitely when copying small files

### ISSUE THREAD

**Issue by zsugabubus** [linuxmint/nemo#2344]
```
 * Nemo version (nemo --version) nemo 4.4.2
 * Is issue with desktop or windowed nemo? Yes
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Arch Linux
 * 64 bit
 ```

**Issue**
File copy dialog stalls indefinitely when copying 1–4095-length files.

**Steps to reproduce**
1. I have a cifs mount at `/path/to/mount`.
2. Create a 1–4095-length file, e.g. `truncate -s4095 /path/to/mount/test`.
3. Copy it with Nemo.
4. You should see file copied completely, but file dialog stalls and cannot stop it/close the window.

Killing `nemo` and repeating command with `truncate -s4096 /path/to/mount/test` finishes instantly. Just like `cp` did in both cases.

**Expected behaviour**
Copy dialog closes.

**Other information**
I have another cifs mounted path to a different (possibly faster) device but I could not reproduce the issue with that.

**Comment by zsugabubus** [comment]
Some debug info:

```
Thread 16 (Thread 0x7fffd9ffb700 (LWP 4257)):
#0  0x00007ffff6c1071d in syscall () at /usr/lib/libc.so.6
#1  0x00007ffff72567ab in g_cond_wait_until () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff71de803 in  () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff71de994 in g_async_queue_timeout_pop () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff723acaa in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff7236511 in  () at /usr/lib/libglib-2.0.so.0
#6  0x00007ffff6ce6422 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007ffff6c15bf3 in clone () at /usr/lib/libc.so.6

Thread 15 (Thread 0x7fffdb7fe700 (LWP 4256)):
#0  0x00007ffff6c16163 in splice () at /usr/lib/libc.so.6
#1  0x00007ffff7390d82 in  () at /usr/lib/libgio-2.0.so.0
#2  0x00007ffff73920d7 in g_file_copy () at /usr/lib/libgio-2.0.so.0
#3  0x0000555555672388 in copy_move_file (copy_job=0x555555fbc4e0, src=0x5555559926a0, dest_dir=0x555555992640, same_fs=0, unique_names=0, dest_fs_type=0x7fffdb7fdb58, source_info=0x7fffdb7fdbf0, transfer_info=0x7fffdb7fdc10, debuting_files=Python Exception <class 'gdb.error'> There is no member named keys.: 
0x555555b77760, position=0x0, overwrite=0, skipped_file=0x7fffdb7fdb44, readonly_source_fs=0) at ../libnemo-private/nemo-file-operations.c:4458
        dest = 0x555555998f40
        new_dest = 0x7ffff71da58e
        error = 0x0
        flags = G_FILE_COPY_NOFOLLOW_SYMLINKS
        primary = 0x0
        secondary = 0x7fffb4001f00 "\b"
        details = 0x7ffff71ef423 <g_datalist_clear+67> "H\205\355tH\213E"
        response = 32767
        pdata = {job = 0x555555fbc4e0, last_size = 3, source_info = 0x7fffdb7fdbf0, transfer_info = 0x7fffdb7fdc10}
        would_recurse = 0
        is_merge = 0
        job = 0x555555fbc4e0
        res = 32767
        unique_name_nr = 1
        handled_invalid_filename = 0
        target_is_desktop = 1
        source_is_desktop = 0
        __func__ = "copy_move_file"
#4  0x00005555556730a8 in copy_files (job=0x555555fbc4e0, dest_fs_id=0x7fffd00013f0 "l2051", source_info=0x7fffdb7fdbf0, transfer_info=0x7fffdb7fdc10) at ../libnemo-private/nemo-file-operations.c:4795
        common = 0x555555fbc4e0
        l = 0x555555991100 = {0x5555559926a0}
        src = 0x5555559926a0
        same_fs = 0
        i = 0
        point = 0x0
        skipped_file = 0
        unique_names = 0
        dest = 0x555555992640
        source_dir = 0x555555974780
        dest_fs_type = 0x0
        inf = 0x7fffd00076d0
        readonly_source_fs = 0
#5  0x000055555567338f in copy_job (io_job=0x55555606b2c0, cancellable=0x555555d2eba0, user_data=0x555555fbc4e0) at ../libnemo-private/nemo-file-operations.c:4890
        job = 0x555555fbc4e0
        common = 0x555555fbc4e0
        source_info = {num_files = 1, num_bytes = 3, num_files_since_progress = 1, op = OP_KIND_COPY}
        transfer_info = {num_files = 0, num_bytes = 3, op = OP_KIND_COPY, last_report_time = 1522230520, last_reported_files_left = 1}
        dest_fs_id = 0x7fffd00013f0 "l2051"
        dest = 0x555555992640
#6  0x00007ffff73af8ee in  () at /usr/lib/libgio-2.0.so.0
#7  0x00007ffff73e1cb1 in  () at /usr/lib/libgio-2.0.so.0
#8  0x00007ffff723ac07 in  () at /usr/lib/libglib-2.0.so.0
#9  0x00007ffff7236511 in  () at /usr/lib/libglib-2.0.so.0
#10 0x00007ffff6ce6422 in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007ffff6c15bf3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff28c4700 (LWP 4243)):
#0  0x00007ffff6c0b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff725bf38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff720d221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff2902e5e in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007ffff7236511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff6ce6422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff6c15bf3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff3127700 (LWP 4242)):
#0  0x00007ffff6c0b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff725bf38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff720cc03 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff743f1a8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007ffff7236511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff6ce6422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff6c15bf3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff3928700 (LWP 4241)):
#0  0x00007ffff6c0b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff725bf38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff720d221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff720d272 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7236511 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007ffff6ce6422 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007ffff6c15bf3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff3fdfe00 (LWP 4240)):
#0  0x00007ffff6c0b05f in poll () at /usr/lib/libc.so.6
#1  0x00007ffff725bf38 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff720d221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff7409c9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#4  0x00005555556467f0 in main (argc=1, argv=0x7fffffffe978) at ../src/nemo-main.c:104
        retval = 32767
        application = 0x5555557b1130
```

Execution stalls at `splice()`. Can you guess what’s going on here or would you need more (debug) info?
