### ISSUE TITLE
Drag-n-drop tab to new window, while SFTP mount is loading, crashes nemo

### ISSUE THREAD

**Issue by gkatev** [linuxmint/nemo#2762]
```
 * Nemo version 5.0.1
 * Windowed nemo
 * Arch Linux
 ```

**Issue**
When drag-n-dropping a nemo tab to create a new window, while an SFTP mount is loading, all nemo windows crash.

**Steps to reproduce**
- Mount an SFTP host through nemo (preferably a slow one, which takes long to load; easier to reproduce)
- Open the mount, wait for it to load
- Create a new tab (Ctrl+T?). The new tab opens in the same location as the last one; the SFTP mount, and begins loading
- Before the new tab has finished loading, drag-n-drop it outside the window, so as to create a new nemo window
- All open nemo windows close (SIGABRT)

**Additional information**
- If instead, at step 4, the new tab has finished loading before dragging it out, the problem does not appear
- Also, I think it only happens when dragging the new tab, that's currently loading. Not when dragging the old tab, that's already loaded, while the new one still is.
- I've only tested an SFTP mount, but it's quite possible it also happens for other mount types.

**Comment by gkatev** [comment]
Well, since you brought it up, it's still happening in nemo 6.6.3.

Here's a backtrace:
```cpp
(gdb) bt
#0  0x00007f97e1a5d90c in ??? () at /usr/lib/libc.so.6
#1  0x00007f97e1a033a0 in raise () at /usr/lib/libc.so.6
#2  0x00007f97e19ea57a in abort () at /usr/lib/libc.so.6
#3  0x00007f97e2082111 in ??? () at /usr/lib/libglib-2.0.so.0
#4  0x00007f97e20f6f19 in g_assertion_message_expr () at /usr/lib/libglib-2.0.so.0
#5  0x0000559c894b7dc0 in nemo_window_slot_get_current_uri (slot=<optimized out>) at ../nemo/src/nemo-window-slot.c:828
#6  nemo_window_slot_get_current_uri (slot=<optimized out>) at ../nemo/src/nemo-window-slot.c:818
#7  nemo_places_sidebar_set_parent_window (sidebar=<optimized out>, window=<optimized out>) at ../nemo/src/nemo-places-sidebar.c:4547
#8  nemo_places_sidebar_new (window=<optimized out>) at ../nemo/src/nemo-places-sidebar.c:4609
#9  nemo_window_set_up_sidebar (window=0x7f9784011240) at ../nemo/src/nemo-window.c:446
#10 0x0000559c894ba7de in nemo_window_show_sidebar (window=0x7f9784011240) at ../nemo/src/nemo-window.c:499
#11 nemo_window_show_sidebar (window=0x7f9784011240) at ../nemo/src/nemo-window.c:487
#12 nemo_window_show (widget=0x7f9784011240) at ../nemo/src/nemo-window.c:1630
#13 0x00007f97e21cf97c in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#14 0x00007f97e21eebf3 in ??? () at /usr/lib/libgobject-2.0.so.0
#15 0x00007f97e21f0b0f in ??? () at /usr/lib/libgobject-2.0.so.0
#16 0x00007f97e21f0d89 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#17 0x00007f97e21f0e44 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007f97e2addde2 in gtk_widget_show (widget=0x7f9784011240) at ../gtk/gtk/gtkwidget.c:4859
#19 gtk_widget_show (widget=0x7f9784011240) at ../gtk/gtk/gtkwidget.c:4832
#20 0x00007f97e27f7a99 in _gtk_marshal_VOID__OBJECT_FLAGSv
    (closure=<optimized out>, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x559c8fcb9b20) at gtk/gtkmarshalers.c:5621
#21 0x00007f97e21f0c77 in ??? () at /usr/lib/libgobject-2.0.so.0
#22 0x00007f97e21f0d89 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#23 0x00007f97e21f0e44 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#24 0x00007f97e29a2cc4 in gtk_notebook_real_insert_page
    (notebook=0x7f9760005b40, child=0x559c932f5e90, tab_label=0x559c933e75d0, menu_label=0x0, position=<optimized out>)
    at ../gtk/gtk/gtknotebook.c:4877
#25 0x0000559c8946365c in nemo_notebook_insert_page
    (gnotebook=0x7f9760005b40, tab_widget=0x559c932f5e90, tab_label=0x559c933e75d0, menu_label=0x0, position=-1)
    at ../nemo/src/nemo-notebook.c:399
#26 0x00007f97e299da6f in do_detach_tab (from=from@entry=0x7f979c00de50, to=0x7f9760005b40, child=0x559c932f5e90, x=x@entry=0, y=y@entry=0)
    at ../gtk/gtk/gtknotebook.c:4011
#27 0x00007f97e299dc4b in gtk_notebook_drag_end (widget=0x7f979c00de50, context=0x7f97c001e2a0) at ../gtk/gtk/gtknotebook.c:3736
#28 0x00007f97e21ce50b in g_cclosure_marshal_VOID__OBJECTv () at /usr/lib/libgobject-2.0.so.0
#29 0x00007f97e21f0c77 in ??? () at /usr/lib/libgobject-2.0.so.0
#30 0x00007f97e21f105f in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#31 0x00007f97e2b25066 in gtk_drag_source_info_destroy (info=0x559c9388e230) at ../gtk/gtk/gtkdnd.c:2807
#32 0x00007f97e21f0c77 in ??? () at /usr/lib/libgobject-2.0.so.0
#33 0x00007f97e21f105f in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#34 0x00007f97e2d9503a in gdk_dnd_handle_drop_finished (event=<optimized out>, context=0x7f97c001e2a0) at ../gtk/gdk/x11/gdkdnd-x11.c:3132
#35 gdk_x11_drag_context_handle_event (context=0x7f97c001e2a0, event=<optimized out>) at ../gtk/gdk/x11/gdkdnd-x11.c:3162
#36 gdk_x11_drag_context_handle_event (context=0x7f97c001e2a0, event=<optimized out>) at ../gtk/gdk/x11/gdkdnd-x11.c:3138
#37 0x00007f97e2d3619e in gdk_drag_context_handle_source_event (event=0x559c93c05170) at ../gtk/gdk/gdkdnd.c:748
#38 _gdk_event_emit (event=0x559c93c05170) at ../gtk/gdk/gdkevents.c:69
#39 0x00007f97e2d95190 in gdk_event_source_dispatch.lto_priv () at ../gtk/gdk/x11/gdkeventsource.c:354
#40 0x00007f97e20c2f8d in ??? () at /usr/lib/libglib-2.0.so.0
#41 0x00007f97e20c4657 in ??? () at /usr/lib/libglib-2.0.so.0
#42 0x00007f97e20c4865 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#43 0x00007f97e23017d6 in g_application_run () at /usr/lib/libgio-2.0.so.0
#44 0x0000559c8942f7c1 in main (argc=1, argv=0x7ffecb53e878) at ../nemo/src/nemo-main.c:102
```
