### ISSUE TITLE
Nemo crash with segfault when open "Perferences"

### ISSUE THREAD

**Issue by maximusfox** [linuxmint/nemo#3035]
* Nemo version (nemo --version) **5.2.4**
 * Is issue with desktop or windowed nemo? **both**
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) **Linux Mint 20.3 x86_64**
 * Graphics hardware *and* driver used **NVIDIA GeForce GTX 1050 Ti (GP107)** with with proprietary driver **515.48.07-0ubuntu0.20.04.2**
 * 32 or 64 bit **64-bit**

**Issue**
Nemo crash with segfault when try to open "Perferences"

**Steps to reproduce**

1. Start nemo
2. Click "Edit"
3. Select "Perferences"

**Expected behaviour**
Opening the settings menu

**Other information**

`dmesg`
```
[776922.457283] nemo[1029428]: segfault at 7f52c3428b70 ip 00007f52c3428b70 sp 00007fffb4e43a48 error 15 in icon-theme.cache[7f52c33d1000+7b000]
[776922.457289] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[776922.490247] nemo-desktop[1021844]: segfault at 7f2da45c8b70 ip 00007f2da45c8b70 sp 00007ffe3ca92528 error 15 in icon-theme.cache[7f2da4571000+7b000]
[776922.490252] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777179.651341] nemo[1029927]: segfault at 7f5c731bbb70 ip 00007f5c731bbb70 sp 00007ffd441b2098 error 15 in icon-theme.cache[7f5c73164000+7b000]
[777179.651346] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777179.668324] nemo-desktop[1029481]: segfault at 7f3a77401b70 ip 00007f3a77401b70 sp 00007ffde74972b8 error 15 in icon-theme.cache (deleted)[7f3a773aa000+7b000]
[777179.668331] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777766.677405] nemo[1033708]: segfault at 7fbfe4c52b70 ip 00007fbfe4c52b70 sp 00007ffc1b398018 error 15 in icon-theme.cache[7fbfe4bfb000+7b000]
[777766.677411] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777766.690551] nemo-desktop[1032764]: segfault at 7f7114f8cb70 ip 00007f7114f8cb70 sp 00007ffd9eb5dab8 error 15 in icon-theme.cache[7f7114f35000+7b000]
[777766.690557] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777947.913863] nemo-desktop[1033756]: segfault at 7f5f4e8fcb70 ip 00007f5f4e8fcb70 sp 00007ffc60cffe98 error 15 in icon-theme.cache (deleted)[7f5f4e8a5000+7b000]
[777947.913868] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[777947.988050] nemo[1034503]: segfault at 7fce3095cb70 ip 00007fce3095cb70 sp 00007ffe54ca3018 error 15 in icon-theme.cache[7fce30905000+7b000]
[777947.988057] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[811717.723525] nemo[1074505]: segfault at 7f53d8d64b70 ip 00007f53d8d64b70 sp 00007ffc2b2dcce8 error 15 in icon-theme.cache[7f53d8d0d000+7b000]
[811717.723530] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
[811717.745077] nemo-desktop[1074442]: segfault at 7f0abb5b3b70 ip 00007f0abb5b3b70 sp 00007ffd086e1dd8 error 15 in icon-theme.cache[7f0abb55c000+7b000]
[811717.745082] Code: 00 04 00 00 00 00 00 17 00 04 00 00 00 00 00 16 00 04 00 00 00 00 00 15 00 04 00 00 00 00 00 14 00 04 00 00 00 00 00 13 00 04 <00> 00 00 00 00 05 7c 20 00 05 7b 80 00 05 7b 9c 75 6e 69 74 79 2d
```

System crash report ([link to pastebin](https://termbin.com/xnuu)) [crash.tar.gz](https://github.com/linuxmint/nemo/files/9173634/crash.tar.gz)

```
===================================================================
 Info                                                              
===================================================================
           PID: 1034503 (nemo)
           UID: 1000 (ded)
           GID: 1000 (ded)
        Signal: 11 (SEGV)
     Timestamp: Sat 2022-07-23 04:44:50 EEST (9h ago)
  Command Line: nemo
    Executable: /usr/bin/nemo
 Control Group: /user.slice/user-1000.slice/user@1000.service/vte-spawn-4b1ffd09-18dd-4d3e-95e0-1975b4f102d9.scope
          Unit: user@1000.service
     User Unit: vte-spawn-4b1ffd09-18dd-4d3e-95e0-1975b4f102d9.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ded)
       Boot ID: 85922a3c94d849a580a2e82119fa24e1
    Machine ID: dafd9a61376b4676aa8b190bc1ed4b43
      Hostname: kaminsky
       Storage: /var/lib/systemd/coredump/core.nemo.1000.85922a3c94d849a580a2e82119fa24e1.1034503.1658540690000000000000.lz4
       Message: Process 1034503 (nemo) of user 1000 dumped core.
                
                Stack trace of thread 1034503:
                #0  0x00007fce3095cb70 n/a (n/a + 0x0)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1034503]
[New LWP 1034504]
[New LWP 1034505]
[New LWP 1034525]
[New LWP 1034507]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nemo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fce3095cb70 in ?? ()
[Current thread is 1 (Thread 0x7fce34265a80 (LWP 1034503))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1034503]
[New LWP 1034504]
[New LWP 1034505]
[New LWP 1034525]
[New LWP 1034507]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nemo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fce3095cb70 in ?? ()
[Current thread is 1 (Thread 0x7fce34265a80 (LWP 1034503))]
#0  0x00007fce3095cb70 in  ()
#1  0x00007fce37966958 in _g_cclosure_marshal_VOID__OBJECT_OBJECT_ENUMv (closure=0x55c22656ae80, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55c2265563e0) at ../../../gio/gmarshal-internal.c:1380
#2  0x00007fce37895a56 in _g_closure_invoke_va (closure=0x55c22656ae80, return_value=0x0, instance=0x55c226872b80, args=0x7ffe54ca3290, n_params=3, param_types=0x55c2265563e0) at ../../../gobject/gclosure.c:873
#3  0x00007fce378b4b48 in g_signal_emit_valist (instance=0x55c226872b80, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe54ca3290) at ../../../gobject/gsignal.c:3408
#4  0x00007fce378b50f3 in g_signal_emit (instance=instance@entry=0x55c226872b80, signal_id=<optimized out>, detail=detail@entry=0) at ../../../gobject/gsignal.c:3555
#5  0x00007fce379579bb in g_file_monitor_emit_event (monitor=monitor@entry=0x55c226872b80 [GInotifyFileMonitor], child=<optimized out>, other_file=<optimized out>, event_type=<optimized out>) at ../../../gio/gfilemonitor.c:294
#6  0x00007fce37a1f153 in g_file_monitor_source_dispatch (source=0x55c226580460, callback=<optimized out>, user_data=<optimized out>) at ../../../gio/glocalfilemonitor.c:567
#7  0x00007fce377a817d in g_main_dispatch (context=0x55c2263ecdb0) at ../../../glib/gmain.c:3309
#8  g_main_context_dispatch (context=context@entry=0x55c2263ecdb0) at ../../../glib/gmain.c:3974
#9  0x00007fce377a8400 in g_main_context_iterate (context=context@entry=0x55c2263ecdb0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
#10 0x00007fce377a84a3 in g_main_context_iteration (context=context@entry=0x55c2263ecdb0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
#11 0x00007fce379c3fe5 in g_application_run (application=0x55c2263ea130 [NemoMainApplication], argc=<optimized out>, argv=<optimized out>) at ../../../gio/gapplication.c:2559
#12 0x000055c226011596 in main (argc=1, argv=0x7ffe54ca3668) at ../src/nemo-main.c:104

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1034503]
[New LWP 1034504]
[New LWP 1034505]
[New LWP 1034525]
[New LWP 1034507]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `nemo'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fce3095cb70 in ?? ()
[Current thread is 1 (Thread 0x7fce34265a80 (LWP 1034503))]

Thread 5 (Thread 0x7fce3283c700 (LWP 1034507)):
#0  0x00007fce3718399f in __GI___poll (fds=0x55c2264c8670, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fce377a836e in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x55c2264c8670, timeout=<optimized out>, context=0x55c2264f9380) at ../../../glib/gmain.c:4346
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7fce377b80d0 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = <optimized out>
        fds = 0x55c2264c8670
#2  g_main_context_iterate (context=context@entry=0x55c2264f9380, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 1
        allocated_nfds = <optimized out>
        fds = 0x55c2264c8670
#3  0x00007fce377a84a3 in g_main_context_iteration (context=0x55c2264f9380, may_block=1) at ../../../glib/gmain.c:4108
        retval = <optimized out>
#4  0x00007fce3289899d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#5  0x00007fce377d1ad1 in g_thread_proxy (data=0x7fce24007aa0) at ../../../glib/gthread.c:807
        thread = 0x7fce24007aa0
        __func__ = "g_thread_proxy"
#6  0x00007fce3726b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140523587487488, -1429565615082608749, 140730320955582, 140730320955583, 140730320955728, 140523587484800, 1420125519502075795, 1420120322929158035}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fce37190133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fce23fff700 (LWP 1034525)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fce377f5746 in g_cond_wait_until (cond=cond@entry=0x55c2263f7a98, mutex=mutex@entry=0x55c2263f7a90, end_time=end_time@entry=777954541212) at ../../../glib/gthread-posix.c:1588
        now = {tv_sec = 777939, tv_nsec = 541212980}
        span = {tv_sec = 14, tv_nsec = 999999020}
        sampled = 1
        res = <optimized out>
        success = <optimized out>
#2  0x00007fce37778581 in g_async_queue_pop_intern_unlocked (queue=queue@entry=0x55c2263f7a90, wait=wait@entry=1, end_time=end_time@entry=777954541212) at ../../../glib/gasyncqueue.c:422
        retval = <optimized out>
        __func__ = "g_async_queue_pop_intern_unlocked"
#3  0x00007fce37778ba6 in g_async_queue_timeout_pop (queue=0x55c2263f7a90, timeout=timeout@entry=15000000) at ../../../glib/gasyncqueue.c:545
        end_time = 777954541212
        retval = <optimized out>
        __func__ = "g_async_queue_timeout_pop"
#4  0x00007fce377d2419 in g_thread_pool_wait_for_new_pool () at ../../../glib/gthreadpool.c:183
        pool = <optimized out>
        local_max_idle_time = 15000
        local_wakeup_thread_serial = <optimized out>
        last_wakeup_thread_serial = 0
        have_relayed_thread_marker = <optimized out>
        free_pool = <optimized out>
        task = <optimized out>
        pool = <optimized out>
#5  g_thread_pool_thread_proxy (data=<optimized out>) at ../../../glib/gthreadpool.c:411
        free_pool = <optimized out>
        task = <optimized out>
        pool = <optimized out>
#6  0x00007fce377d1ad1 in g_thread_proxy (data=0x55c226e7c980) at ../../../glib/gthread.c:807
        thread = 0x55c226e7c980
        __func__ = "g_thread_proxy"
#7  0x00007fce3726b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140523343968000, -1429565615082608749, 140730320957710, 140730320957711, 140730320957856, 140523343965312, 1420162592049162131, 1420120322929158035}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#8  0x00007fce37190133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fce33116700 (LWP 1034505)):
#0  0x00007fce3718399f in __GI___poll (fds=0x7fce1800dc80, nfds=4, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fce377a836e in g_main_context_poll (priority=<optimized out>, n_fds=4, fds=0x7fce1800dc80, timeout=<optimized out>, context=0x55c22644b250) at ../../../glib/gmain.c:4346
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7fce377b80d0 <g_poll>
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 4
        allocated_nfds = <optimized out>
        fds = 0x7fce1800dc80
#2  g_main_context_iterate (context=0x55c22644b250, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
        max_priority = 2147483647
        timeout = -1
        some_ready = <optimized out>
        nfds = 4
        allocated_nfds = <optimized out>
        fds = 0x7fce1800dc80
#3  0x00007fce377a86f3 in g_main_loop_run (loop=0x55c22644b340) at ../../../glib/gmain.c:4241
        __func__ = "g_main_loop_run"
#4  0x00007fce379fff8a in gdbus_shared_thread_func (user_data=0x55c22644b220) at ../../../gio/gdbusprivate.c:279
        data = 0x55c22644b220
#5  0x00007fce377d1ad1 in g_thread_proxy (data=0x55c2264436a0) at ../../../glib/gthread.c:807
        thread = 0x55c2264436a0
        __func__ = "g_thread_proxy"
#6  0x00007fce3726b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140523596769024, -1429565615082608749, 140730320953230, 140730320953231, 140730320953376, 140523596766336, 1420128698851616659, 1420120322929158035}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fce37190133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fce33940700 (LWP 1034504)):
#0  0x00007fce3718399f in __GI___poll (fds=0x55c226438e60, nfds=2, timeout=403) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
#1  0x00007fce377a836e in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x55c226438e60, timeout=<optimized out>, context=0x55c22643a790) at ../../../glib/gmain.c:4346
        ret = <optimized out>
        errsv = <optimized out>
        poll_func = 0x7fce377b80d0 <g_poll>
        max_priority = 2147483647
        timeout = 403
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x55c226438e60
#2  g_main_context_iterate (context=context@entry=0x55c22643a790, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4042
        max_priority = 2147483647
        timeout = 403
        some_ready = <optimized out>
        nfds = 2
        allocated_nfds = <optimized out>
        fds = 0x55c226438e60
#3  0x00007fce377a84a3 in g_main_context_iteration (context=0x55c22643a790, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
        retval = <optimized out>
#4  0x00007fce377a84f1 in glib_worker_main (data=<optimized out>) at ../../../glib/gmain.c:5996
#5  0x00007fce377d1ad1 in g_thread_proxy (data=0x55c226430360) at ../../../glib/gthread.c:807
        thread = 0x55c226430360
        __func__ = "g_thread_proxy"
#6  0x00007fce3726b609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140523605329664, -1429565615082608749, 140730320952798, 140730320952799, 140730320952944, 140523605326976, 1420127578938894227, 1420120322929158035}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#7  0x00007fce37190133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fce34265a80 (LWP 1034503)):
#0  0x00007fce3095cb70 in  ()
#1  0x00007fce37966958 in _g_cclosure_marshal_VOID__OBJECT_OBJECT_ENUMv (closure=0x55c22656ae80, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55c2265563e0) at ../../../gio/gmarshal-internal.c:1380
        cc = 0x55c22656ae80
        data1 = 0x55c226872b80
        data2 = <optimized out>
        callback = 0x7fce3095cb70
        arg0 = 0x55c2265b0440
        arg1 = 0x0
        arg2 = 2
        args_copy = {{gp_offset = 48, fp_offset = 48, overflow_arg_area = 0x7ffe54ca3370, reg_save_area = 0x7ffe54ca32b0}}
#2  0x00007fce37895a56 in _g_closure_invoke_va (closure=0x55c22656ae80, return_value=0x0, instance=0x55c226872b80, args=0x7ffe54ca3290, n_params=3, param_types=0x55c2265563e0) at ../../../gobject/gclosure.c:873
        marshal = 0x7fce37966880 <_g_cclosure_marshal_VOID__OBJECT_OBJECT_ENUMv>
        marshal_data = 0x0
        in_marshal = 0
        real_closure = 0x55c22656ae60
        __func__ = "_g_closure_invoke_va"
#3  0x00007fce378b4b48 in g_signal_emit_valist (instance=0x55c226872b80, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe54ca3290) at ../../../gobject/gsignal.c:3408
        return_accu = <optimized out>
        accu = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        accumulator = 0x0
        emission = {next = 0x0, instance = 0x55c226872b80, ihint = {signal_id = 219, detail = 0, run_type = G_SIGNAL_RUN_FIRST}, state = EMISSION_RUN, chain_type = 0x55c2263e9220 [GInotifyFileMonitor/GLocalFileMonitor/GFileMonitor]}
        signal_id = 219
        instance_type = <optimized out>
        emission_return = {g_type = 0x0, data = {{v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}, {v_int = 0, v_uint = 0, v_long = 0, v_ulong = 0, v_int64 = 0, v_uint64 = 0, v_float = 0, v_double = 0, v_pointer = 0x0}}}
        rtype = 0x4 [void]
        static_scope = 0
        fastpath_handler = <optimized out>
        closure = <optimized out>
        run_type = <optimized out>
        hlist = <optimized out>
        l = <optimized out>
        fastpath = 1
        instance_and_params = <optimized out>
        signal_return_type = <optimized out>
        param_values = <optimized out>
        node = <optimized out>
        i = <optimized out>
        n_params = <optimized out>
        __func__ = "g_signal_emit_valist"
#4  0x00007fce378b50f3 in g_signal_emit (instance=instance@entry=0x55c226872b80, signal_id=<optimized out>, detail=detail@entry=0) at ../../../gobject/gsignal.c:3555
        var_args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe54ca3370, reg_save_area = 0x7ffe54ca32b0}}
#5  0x00007fce379579bb in g_file_monitor_emit_event (monitor=monitor@entry=0x55c226872b80 [GInotifyFileMonitor], child=<optimized out>, other_file=<optimized out>, event_type=<optimized out>) at ../../../gio/gfilemonitor.c:294
        __func__ = "g_file_monitor_emit_event"
#6  0x00007fce37a1f153 in g_file_monitor_source_dispatch (source=0x55c226580460, callback=<optimized out>, user_data=<optimized out>) at ../../../gio/glocalfilemonitor.c:567
        event = 0x55c2265b0340
        event_queue = {head = 0x55c2265b17a0 = {0x55c2265b0ac0, 0x55c2265b0ec0}, tail = 0x55c2265b1540 = {0x55c2265b0ec0}, length = 2}
        now = <optimized out>
        instance = 0x55c226872b80 [GInotifyFileMonitor]
#7  0x00007fce377a817d in g_main_dispatch (context=0x55c2263ecdb0) at ../../../glib/gmain.c:3309
        dispatch = 0x7fce37a1efe0 <g_file_monitor_source_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0x55c226580460
        current = 0x55c22644bd30
        i = 2
        __func__ = "g_main_dispatch"
#8  g_main_context_dispatch (context=context@entry=0x55c2263ecdb0) at ../../../glib/gmain.c:3974
#9  0x00007fce377a8400 in g_main_context_iterate (context=context@entry=0x55c2263ecdb0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x55c2263f23e0
#10 0x00007fce377a84a3 in g_main_context_iteration (context=context@entry=0x55c2263ecdb0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
        retval = <optimized out>
#11 0x00007fce379c3fe5 in g_application_run (application=0x55c2263ea130 [NemoMainApplication], argc=<optimized out>, argv=<optimized out>) at ../../../gio/gapplication.c:2559
        arguments = 0x55c2263e9720
        status = 0
        context = 0x55c2263ecdb0
        acquired_context = 1
        __func__ = "g_application_run"
#12 0x000055c226011596 in main (argc=1, argv=0x7ffe54ca3668) at ../src/nemo-main.c:104
        retval = <optimized out>
        application = 0x55c2263ea130 [NemoMainApplication]
#0  0x00007fce3095cb70 in  ()
#1  0x00007fce37966958 in _g_cclosure_marshal_VOID__OBJECT_OBJECT_ENUMv (closure=0x55c22656ae80, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x55c2265563e0) at ../../../gio/gmarshal-internal.c:1380
#2  0x00007fce37895a56 in _g_closure_invoke_va (closure=0x55c22656ae80, return_value=0x0, instance=0x55c226872b80, args=0x7ffe54ca3290, n_params=3, param_types=0x55c2265563e0) at ../../../gobject/gclosure.c:873
#3  0x00007fce378b4b48 in g_signal_emit_valist (instance=0x55c226872b80, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffe54ca3290) at ../../../gobject/gsignal.c:3408
#4  0x00007fce378b50f3 in g_signal_emit (instance=instance@entry=0x55c226872b80, signal_id=<optimized out>, detail=detail@entry=0) at ../../../gobject/gsignal.c:3555
#5  0x00007fce379579bb in g_file_monitor_emit_event (monitor=monitor@entry=0x55c226872b80 [GInotifyFileMonitor], child=<optimized out>, other_file=<optimized out>, event_type=<optimized out>) at ../../../gio/gfilemonitor.c:294
#6  0x00007fce37a1f153 in g_file_monitor_source_dispatch (source=0x55c226580460, callback=<optimized out>, user_data=<optimized out>) at ../../../gio/glocalfilemonitor.c:567
#7  0x00007fce377a817d in g_main_dispatch (context=0x55c2263ecdb0) at ../../../glib/gmain.c:3309
#8  g_main_context_dispatch (context=context@entry=0x55c2263ecdb0) at ../../../glib/gmain.c:3974
#9  0x00007fce377a8400 in g_main_context_iterate (context=context@entry=0x55c2263ecdb0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4047
#10 0x00007fce377a84a3 in g_main_context_iteration (context=context@entry=0x55c2263ecdb0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4108
#11 0x00007fce379c3fe5 in g_application_run (application=0x55c2263ea130 [NemoMainApplication], argc=<optimized out>, argv=<optimized out>) at ../../../gio/gapplication.c:2559
#12 0x000055c226011596 in main (argc=1, argv=0x7ffe54ca3668) at ../src/nemo-main.c:104
```

**Comment by maximusfox** [comment]
After remove nemo cache and config, and remove all nemo plugins this issue is fixed.
As i understend nemo-extension-fma is a problem plugin.

**Comment by mtwebster** [comment]
You could use nemo's action system also (in case you didn't know about it)
