### ISSUE TITLE
nemo crashes when entering a folder with large SVG files

### ISSUE THREAD

**Issue by ad-on-is** [linuxmint/nemo#3149]
```
nemo 5.6.1


OS: EndeavourOS Linux x86_64 
Kernel: 6.1.1-arch1-1 
Uptime: 17 hours, 4 mins 
Packages: 2391 (pacman), 24 (flatpak) 
Shell: zsh 5.9 
Resolution: 3440x1440, 3440x1440, 1080x1920, 1080x1920 
WM: awesome 
Theme: Adwaita-dark [GTK2], adw-gtk3-dark [GTK3] 
Icons: Adwaita [GTK2/3] 
Terminal: kitty 
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz 
GPU: AMD ATI Radeon RX 6700/6700 XT/6750 XT / 6800M 
Memory: 5505MiB / 32009MiB 
 ```

**Issue**
When entering a folder that contains large SVG files, nemo just crashes. Entering folders containing smaller svg files works as expected.

These are the files within the folder:

```
drwxr-xr-x 1 adonis adonis    1482  1. Jän 12:06 .
drwxr-xr-x 1 adonis adonis      54  1. Jän 12:06 ..
-rw-r--r-- 1 adonis adonis 3102355  1. Jän 12:06 fp-info-cache
drwxr-xr-x 1 adonis adonis    1664  1. Jän 12:06 LPKeyboard-backups
-rw-r--r-- 1 adonis adonis 1288394  1. Jän 12:06 LPKeyboard-B_Cu.gbl
-rw-r--r-- 1 adonis adonis 1302655  1. Jän 12:06 LPKeyboard-B_Cu.gbr
-rw-r--r-- 1 adonis adonis   16681  1. Jän 12:06 LPKeyboard-B_Mask.gbr
-rw-r--r-- 1 adonis adonis   14705  1. Jän 12:06 LPKeyboard-B_Mask.gbs
-rw-r--r-- 1 adonis adonis    7788  1. Jän 12:06 LPKeyboard-B_Paste.gbp
-rw-r--r-- 1 adonis adonis    9020  1. Jän 12:06 LPKeyboard-B_Paste.gbr
-rw-r--r-- 1 adonis adonis   98357  1. Jän 12:06 LPKeyboard-B_Silkscreen.gbo
-rw-r--r-- 1 adonis adonis   85832  1. Jän 12:06 LPKeyboard-B_Silkscreen.gbr
-rw-r--r-- 1 adonis adonis    9067  1. Jän 12:06 LPKeyboard-Edge_Cuts.gbr
-rw-r--r-- 1 adonis adonis    8704  1. Jän 12:06 LPKeyboard-Edge_Cuts.gm1
-rw-r--r-- 1 adonis adonis  940462  1. Jän 12:06 LPKeyboard-F_Cu.gbr
-rw-r--r-- 1 adonis adonis  925524  1. Jän 12:06 LPKeyboard-F_Cu.gtl
-rw-r--r-- 1 adonis adonis   16791  1. Jän 12:06 LPKeyboard-F_Mask.gbr
-rw-r--r-- 1 adonis adonis   14815  1. Jän 12:06 LPKeyboard-F_Mask.gts
-rw-r--r-- 1 adonis adonis    9010  1. Jän 12:06 LPKeyboard-F_Paste.gbr
-rw-r--r-- 1 adonis adonis    7778  1. Jän 12:06 LPKeyboard-F_Paste.gtp
-rw-r--r-- 1 adonis adonis  136782  1. Jän 12:06 LPKeyboard-F_Silkscreen.gbr
-rw-r--r-- 1 adonis adonis  148501  1. Jän 12:06 LPKeyboard-F_Silkscreen.gto
-rw-r--r-- 1 adonis adonis    2590  1. Jän 12:06 LPKeyboard-job.gbrjob
-rw-r--r-- 1 adonis adonis 3713373  1. Jän 12:06 LPKeyboard.kicad_pcb
-rw-r--r-- 1 adonis adonis    1145  1. Jän 12:06 LPKeyboard.kicad_prl
-rw-r--r-- 1 adonis adonis    9116  1. Jän 12:06 LPKeyboard.kicad_pro
-rw-r--r-- 1 adonis adonis  196563  1. Jän 12:06 LPKeyboard.kicad_sch
-rw-r--r-- 1 adonis adonis  268168  1. Jän 12:06 LPKeyboard.kicad_sch-bak
-rw-r--r-- 1 adonis adonis    2186  1. Jän 12:06 LPKeyboard-NPTH.drl
-rw-r--r-- 1 adonis adonis   42056  1. Jän 12:06 LPKeyboard-NPTH-drl_map.gbr
-rw-r--r-- 1 adonis adonis   44711  1. Jän 12:06 LPKeyboard-NPTH-drl_map.ps
-rw-r--r-- 1 adonis adonis    6774  1. Jän 12:06 LPKeyboard-PTH.drl
-rw-r--r-- 1 adonis adonis   82556  1. Jän 12:06 LPKeyboard-PTH-drl_map.gbr
-rw-r--r-- 1 adonis adonis   96327  1. Jän 12:06 LPKeyboard-PTH-drl_map.ps
-rw-r--r-- 1 adonis adonis     627  1. Jän 12:06 place_footprints.log
-rw-r--r-- 1 adonis adonis     627  1. Jän 12:06 replicate_layout.log
```

**Steps to reproduce**
In my case, the problematic folder is this one: `/home/adonis/Downloads/penguin-master/kicad`

- Navigate to Downloads - fine
- Navigate into penguin-master - fine
- Navigate into kicad - crash

**Expected behaviour**
Nemo should not crash.

**Other information**

```
RUST_BACKTRACE=full nemo

(nemo:16934): Gtk-WARNING **: 11:59:36.393: Theme parsing error: gtk.css:119:106: '' is not a valid color name
Gtk-Message: 11:59:36.415: Failed to load module "colorreload-gtk-module"

** (nemo:16934): WARNING **: 11:59:36.423: Current gtk theme is not known to have nemo support (adw-gtk3-dark) - checking...
GSConnect: No translation file found for domain
Nemo-Share-Message: 11:59:36.649: Called "net usershare info" but it failed: 'net usershare' returned error 255: Can't load /etc/samba/smb.conf - run testparm to debug it
net usershare: usershares are currently disabled

(gdk-pixbuf-thumbnailer:17401): Pango-WARNING **: 11:59:44.220: failed to create cairo scaled font, expect ugly output. the offending font is 'Liberation Serif 1733333'

(gdk-pixbuf-thumbnailer:17401): Pango-WARNING **: 11:59:44.220: font_face status is: error occurred in libfreetype

(gdk-pixbuf-thumbnailer:17401): Pango-WARNING **: 11:59:44.220: scaled_font status is: error occurred in libfreetype
thread '<unnamed>' panicked at 'assertion failed: h >= 0.0', src/text.rs:364:9
stack backtrace:
   0:     0x7f1a6b111f7d - <unknown>
   1:     0x7f1a6b177a6c - <unknown>
   2:     0x7f1a6b1033f1 - <unknown>
   3:     0x7f1a6b114ca5 - <unknown>
   4:     0x7f1a6b1149c1 - <unknown>
   5:     0x7f1a6b1152c6 - <unknown>
   6:     0x7f1a6b115179 - <unknown>
   7:     0x7f1a6b112474 - <unknown>
   8:     0x7f1a6b114ee9 - <unknown>
   9:     0x7f1a6acf40c3 - <unknown>
  10:     0x7f1a6acf3f8d - <unknown>
  11:     0x7f1a6addf88e - <unknown>
  12:     0x7f1a6ad5dcf9 - <unknown>
  13:     0x7f1a6addacf5 - <unknown>
  14:     0x7f1a6ad7607d - <unknown>
  15:     0x7f1a6ad3a423 - <unknown>
  16:     0x7f1a6ad665d7 - <unknown>
  17:     0x7f1a6ad3a591 - <unknown>
  18:     0x7f1a6add4b9f - <unknown>
  19:     0x7f1a6ad5da77 - <unknown>
  20:     0x7f1a6adcf987 - <unknown>
  21:     0x7f1a6ad75f0d - <unknown>
  22:     0x7f1a6ad3a423 - <unknown>
  23:     0x7f1a6ad665d7 - <unknown>
  24:     0x7f1a6ad3a591 - <unknown>
  25:     0x7f1a6add0ded - <unknown>
  26:     0x7f1a6ad5da77 - <unknown>
  27:     0x7f1a6add0492 - <unknown>
  28:     0x7f1a6ad76038 - <unknown>
  29:     0x7f1a6ad3a423 - <unknown>
  30:     0x7f1a6ad665d7 - <unknown>
  31:     0x7f1a6ad5af73 - <unknown>
  32:     0x7f1a6ada9691 - <unknown>
  33:     0x7f1a6ad43032 - <unknown>
  34:     0x7f1a6ad42e04 - <unknown>
  35:     0x7f1a6ad45f5c - rsvg_handle_get_pixbuf
  36:     0x7f1a6d35a338 - <unknown>
  37:     0x7f1a6d31737b - gdk_pixbuf_loader_close
  38:     0x7f1a6d317b4d - gdk_pixbuf_new_from_file_at_scale
  39:     0x558b7c264187 - <unknown>
  40:     0x7f1a6cceb290 - <unknown>
  41:     0x7f1a6cceb34a - __libc_start_main
  42:     0x558b7c264515 - <unknown>
  43:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5

(nemo:16934): Pango-WARNING **: 11:59:44.381: failed to create cairo scaled font, expect ugly output. the offending font is 'Liberation Serif 1733333'

(nemo:16934): Pango-WARNING **: 11:59:44.381: font_face status is: error occurred in libfreetype

(nemo:16934): Pango-WARNING **: 11:59:44.381: scaled_font status is: error occurred in libfreetype
thread '<unnamed>' panicked at 'assertion failed: h >= 0.0', src/text.rs:364:9
stack backtrace:
   0:     0x7f85e2b11f7d - <unknown>
   1:     0x7f85e2b77a6c - <unknown>
   2:     0x7f85e2b033f1 - <unknown>
   3:     0x7f85e2b14ca5 - <unknown>
   4:     0x7f85e2b149c1 - <unknown>
   5:     0x7f85e2b152c6 - <unknown>
   6:     0x7f85e2b15179 - <unknown>
   7:     0x7f85e2b12474 - <unknown>
   8:     0x7f85e2b14ee9 - <unknown>
   9:     0x7f85e26f40c3 - <unknown>
  10:     0x7f85e26f3f8d - <unknown>
  11:     0x7f85e27df88e - <unknown>
  12:     0x7f85e275dcf9 - <unknown>
  13:     0x7f85e27dacf5 - <unknown>
  14:     0x7f85e277607d - <unknown>
  15:     0x7f85e273a423 - <unknown>
  16:     0x7f85e27665d7 - <unknown>
  17:     0x7f85e273a591 - <unknown>
  18:     0x7f85e27d4b9f - <unknown>
  19:     0x7f85e275da77 - <unknown>
  20:     0x7f85e27cf987 - <unknown>
  21:     0x7f85e2775f0d - <unknown>
  22:     0x7f85e273a423 - <unknown>
  23:     0x7f85e27665d7 - <unknown>
  24:     0x7f85e273a591 - <unknown>
  25:     0x7f85e27d0ded - <unknown>
  26:     0x7f85e275da77 - <unknown>
  27:     0x7f85e27d0492 - <unknown>
  28:     0x7f85e2776038 - <unknown>
  29:     0x7f85e273a423 - <unknown>
  30:     0x7f85e27665d7 - <unknown>
  31:     0x7f85e275af73 - <unknown>
  32:     0x7f85e27a9691 - <unknown>
  33:     0x7f85e2743032 - <unknown>
  34:     0x7f85e2742e04 - <unknown>
  35:     0x7f85e2745f5c - rsvg_handle_get_pixbuf
  36:     0x7f85fe145338 - <unknown>
  37:     0x7f8612aa837b - gdk_pixbuf_loader_close
  38:     0x7f86135d5fd1 - <unknown>
  39:     0x7f86135c7c13 - gnome_desktop_thumbnail_factory_generate_thumbnail
  40:     0x55f0a31967c7 - <unknown>
  41:     0x7f8612971c4c - <unknown>
  42:     0x7f86127b0673 - <unknown>
  43:     0x7f86127aae05 - <unknown>
  44:     0x7f86121898fd - <unknown>
  45:     0x7f861220ba60 - <unknown>
  46:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=full nemo
```

**Comment by masla84** [comment]
Issue still exists in nemo 5.8.5, biggest .svg file in the specific folder is 1.8MB

**Comment by leigh123linux** [comment]
You can reopen this once you provide a full backtrace with all the required debug sysmbols.

**Comment by ad-on-is** [comment]
But I provided a full backtrace, or did I miss something?

**Comment by leigh123linux** [comment]
That is just a stacktrace which isn't useful.

**Comment by leigh123linux** [comment]
None of these svg cause nemo to crash.

https://freetestdata.com/image-files/svg/

eom or eog viewers can't open them or generate thumbnail image, maybe gdk-pixbuf2 can't handle large svg files

**Comment by masla84** [comment]
I just checked my svg file, causing the crash. It's just 102kB so I think it's not related to file size. But all affected svg are generated by KiCAD. I tried to attach the file but even firefox crashes trying to open the file. Chromium/Inkscape don't crash but don't show the file correctly.

**Comment by ad-on-is** [comment]
Oh, it didn't even occur to me to test further in Firefox. Maybe this issue is indeed something kicad should handle.

**Comment by masla84** [comment]
Indeed, KiCAD should improve their svg output. Regardless it seems correct svg format, except warning of missing character encoding.
But Firefox and Nemo or related svg tools could also improved to not just crashing.

Related to providing a backtrace: For this debug symbols for gdb are needed? Where to get it? A separate nemo-dbg package is not available in debian.

**Comment by ad-on-is** [comment]
I couldn't either find anything regarding the full backtrace.

**Comment by ad-on-is** [comment]
FYI: My issue is since January, and in the meantime I switched from Arch to Fedora. Right now, I have nemo 5.8.5 installed. I just downloaded your zip, extracted it, and neither nemo nor Firefox crash upon opening it.

**Comment by masla84** [comment]
Ok thank you, I also have nemo 5.8.5 but with debian testing. Since this issue seems not related to nemo directly, I'm fine with issue closed.
