### ISSUE TITLE
Nemo desktop high memory usage

### ISSUE THREAD

**Issue by blueray453** [linuxmint/nemo#3306]
### Distribution

Debian Bookworm 

### Package version

nemo-desktop 5.6.4

### Frequency

Always

### Bug description

This is related to https://github.com/linuxmint/nemo/issues/2313 and https://github.com/linuxmint/nemo/issues/2873

Using nemo-desktop 5.6.4 in debian bookworm (gnome).

Here are few screenshots from System Monitor.

Initial stage: nemo-desktop is using 37.7 mb.

![initial](https://github.com/linuxmint/nemo/assets/855297/00882d05-d301-4e73-bcce-6487724b40b2)

after few minutes: nemo-desktop is using 143.5 mb.

![after-few-minutes](https://github.com/linuxmint/nemo/assets/855297/2407fed0-13ea-46ff-83f5-1a541610345b)

When memory usages increases the system becomes very slow. For example, right click context menu takes 5-7 seconds to open.

In System Monitor, I have to right click `nemo-desktop` and kill to get things back to normal. Again after few hours I have to do the same and repeat.

Given enough time, it normally reach 1GB - 3GB or even 5GB. However, when it reaches that level, the desktop is almost non-responsive.

### Steps to reproduce

I always find this issue. Just to be clear, I keep some files in desktop and also download files in desktop.

### Expected behavior

The system should always be snappy without killing nemo-desktop after certain interval.

**Comment by blueray453** [comment]
Another screenshot after an hour. Now it is 314mb.

![2nd](https://github.com/linuxmint/nemo/assets/855297/9ceb7a32-cf5b-400d-98ce-d7ca06914b30)

**Comment by mtwebster** [comment]
Is there any output if you run it from a terminal?
```
nemo-desktop --quit
nemo-desktop --quit
nemo-desktop
```

Does it occur with an empty desktop (or you can try with a new user). If you have images/videos on the desktop, try temporarily moving them elsewhere (restart nemo-desktop again if you do this). Same with mounts, try disabling all 'virtual' icons from cinnamon settings -> Desktop.

**Comment by blueray453** [comment]
Here is the output:

```
> nemo-desktop --quit
  nemo-desktop --quit
  nemo-desktop
Killing nemo-desktop, as requested
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-media-columns.py", line 26, in <module>
    import stopit
ModuleNotFoundError: No module named 'stopit'
Killing nemo-desktop, as requested
Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/nemo-media-columns.py", line 26, in <module>
    import stopit
ModuleNotFoundError: No module named 'stopit'
** Message: 11:45:18.675: nemo-desktop: session is not cinnamon (checked XDG_SESSION_DESKTOP,DESKTOP_SESSION environment variables.) Applying default behavior
```
> Does it occur with an empty desktop (or you can try with a new user). If you have images/videos on the desktop, try temporarily moving them elsewhere (restart nemo-desktop again if you do this). 

I am working on it.

> Same with mounts, try disabling all 'virtual' icons from cinnamon settings -> Desktop.

I do not use Linux Mint. I am using Debian 12.

**Comment by blueray453** [comment]
There is no more icons in the desktop. I have disabled everything including mounted drives (using dconf). Let me check what happens.

**Comment by leigh123linux** [comment]
> No module named 'stopit'

Install python-stopit and post again.

**Comment by blueray453** [comment]
Installed `stopit`.

Now it looks like:

```
> nemo-desktop --quit
    nemo-desktop --quit
    nemo-desktop
Killing nemo-desktop, as requested
Killing nemo-desktop, as requested
** Message: 19:59:22.557: nemo-desktop: session is not cinnamon (checked XDG_SESSION_DESKTOP,DESKTOP_SESSION environment variables.) Applying default behavior
```
Without files downloading in desktop or desktop icons or mounted drives, the usage seems normal.

As I have not installed stopit, please let me check with desktop downloads and mounted drives again.

**Comment by blueray453** [comment]
So I am currently using the following service to restart nemo-destop when memory usage is more than 300M.

```
tee ~/.local/share/systemd/user/nemo-desktop-bug-workaround.service << END
[Unit]
Description=Nemo Desktop Bug Workaround
Wants=graphical-session.target gnome-session.target
After=graphical-session.target gnome-session.target
# PartOf=graphical-session.target
# BindsTo=graphical-session.target

[Service]
Type=simple
StartLimitIntervalSec=3
ExecStart=/usr/bin/nemo-desktop
ExecStop=/usr/bin/nemo-desktop --quit
MemoryAccounting=true
MemoryMax=300M
Restart=always
KillMode=process
KillSignal=SIGKILL

[Install]
WantedBy=graphical-session.target gnome-session.target
END

systemctl --user daemon-reload
systemctl --user start nemo-desktop-bug-workaround.service
systemctl --user enable nemo-desktop-bug-workaround.service
```

**Comment by blueray453** [comment]
I just needed to mention that `Exec=timeout -k 9 30m nemo-desktop` also has issues. Sometimes it close other opened windows. That is why now I use the old `.desktop` file. And restart `nemo-desktop` when my system become unusable.
