### ISSUE TITLE
nemo and nemo-desktop uses a ridiculous amount of memory

### ISSUE THREAD

**Issue by MilczekZimowy** [linuxmint/nemo#3376]
### Distribution

LMDE 6

### Package version

nemo 6.0.2

### Frequency

Quite often

### Bug description

Open Nemo windows use a ridiculous amount of memory and it increases over time.
After an hour it can reach 2.5 GB and after two hours even 3.8 GB
This has only been happening for a few days.
Previously, 5-6 days ago, there was no such memory consumption

### Steps to reproduce

I simply open the Nemo window and leave it open. Nothing more.

### Expected behavior

I think 2.5 GB and above is a bit too much for just an open Nemo window.

### Additional information

```text
System:
  Kernel: 6.1.0-17-amd64 arch: x86_64 bits: 64 compiler: gcc v: 12.2.0 Desktop: Cinnamon v: 6.0.4
    tk: GTK v: 3.24.38 info: plank wm: muffin vt: 7 dm: LightDM v: 1.26.0 Distro: LMDE 6 Faye
    base: Debian 12.1 bookworm
Machine:
  Type: Desktop Mobo: MSI model: B150M PRO-VDH D3 (MS-7982) v: 2.0 serial: <superuser required>
    UEFI: American Megatrends v: B.D0 date: 06/28/2018
CPU:
  Info: quad core model: Intel Core i5-6400 bits: 64 type: MCP smt: <unsupported> arch: Skylake-S
    rev: 3 cache: L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 3186 high: 3219 min/max: 800/3300 cores: 1: 3203 2: 3140 3: 3184 4: 3219
    bogomips: 21599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GM206 [GeForce GTX 950] vendor: ASUSTeK driver: nvidia v: 525.147.05
    arch: Maxwell pcie: speed: 8 GT/s lanes: 16 bus-ID: 01:00.0 chip-ID: 10de:1402 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.7 with: Xwayland v: 22.1.9 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa alternate: nv gpu: nvidia display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 92 s-size: 530x301mm (20.87x11.85") s-diag: 610mm (24")
  Monitor-1: HDMI-0 res: 1920x1080 hz: 60 dpi: 92 size: 531x298mm (20.91x11.73")
    diag: 609mm (23.97") modes: N/A
  API: OpenGL v: 4.6.0 NVIDIA 525.147.05 renderer: NVIDIA GeForce GTX 950/PCIe/SSE2
    direct-render: Yes
Audio:
  Device-1: Intel 100 Series/C230 Series Family HD Audio vendor: Micro-Star MSI
    driver: snd_hda_intel v: kernel bus-ID: 00:1f.3 chip-ID: 8086:a170 class-ID: 0403
  Device-2: NVIDIA GM206 High Definition Audio vendor: ASUSTeK driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 01:00.1 chip-ID: 10de:0fba class-ID: 0403
  API: ALSA v: k6.1.0-17-amd64 status: kernel-api
  Server-1: PipeWire v: 0.3.65 status: active with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: d000 bus-ID: 02:00.0
    chip-ID: 10ec:8168 class-ID: 0200
  IF: enp2s0 state: down mac: <filter>
  Device-2: Ralink MT7601U Wireless Adapter type: USB driver: mt7601u bus-ID: 1-6:2
    chip-ID: 148f:7601 class-ID: 0000 serial: <filter>
  IF: wlx76012dc3f20e state: up mac: <filter>
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) type: USB driver: btusb v: 0.8
    bus-ID: 1-7:3 chip-ID: 0a12:0001 class-ID: fe01
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 1.2 lmp-v: 2.1
    sub-v: 420e hci-v: 2.1 rev: 5000
Drives:
  Local Storage: total: 1.83 TiB used: 509.55 GiB (27.2%)
  ID-1: /dev/sda vendor: SanDisk model: SSDPR-CX400-512-G2 size: 476.94 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 61.5 scheme: GPT
  ID-2: /dev/sdb vendor: Seagate model: ST1000DM003-1SB102 size: 931.51 GiB speed: 6.0 Gb/s
    type: HDD rpm: 7200 serial: <filter> rev: CC43 scheme: GPT
  ID-3: /dev/sdc vendor: Western Digital model: WD5000AAKX-00ERMA0 size: 465.76 GiB
    speed: 6.0 Gb/s type: N/A serial: <filter> rev: 1H15 scheme: GPT
Partition:
  ID-1: / size: 460.13 GiB used: 57.14 GiB (12.4%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 285.4 MiB used: 5.8 MiB (2.0%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 8.1 GiB used: 41.9 MiB (0.5%) priority: -2 dev: /dev/sda2
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Ralink MT7601U Wireless Adapter type: Network driver: mt7601u
    interfaces: 1 rev: 2.0 speed: 480 Mb/s power: 160mA chip-ID: 148f:7601 class-ID: 0000
    serial: <filter>
  Device-2: 1-7:3 info: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) type: Bluetooth
    driver: btusb interfaces: 4 rev: 2.0 speed: 12 Mb/s chip-ID: 0a12:0001 class-ID: fe01
  Device-3: 1-9:4 info: Logitech Mouse type: Mouse driver: hid-generic,usbhid interfaces: 1
    rev: 2.0 speed: 1.5 Mb/s power: 100mA chip-ID: 046d:c077 class-ID: 0301
  Device-4: 1-10:5 info: Dell Keyboard SK-8115 type: Keyboard driver: hid-generic,usbhid
    interfaces: 1 rev: 1.1 speed: 1.5 Mb/s power: 70mA chip-ID: 413c:2003 class-ID: 0301
  Hub-2: 2-0:1 info: Super-speed hub ports: 6 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 48.0 C pch: 54.0 C mobo: N/A gpu: nvidia temp: 63 C
  Fan Speeds (RPM): N/A gpu: nvidia fan: 25%
Repos:
  Packages: 3116 pm: dpkg pkgs: 3115 pm: flatpak pkgs: 1
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/brave-browser-release.list
    1: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https: //brave-browser-apt-release.s3.brave.com/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/google-earth-pro.list
    1: deb [arch=amd64] http: //dl.google.com/linux/earth/deb/ stable main
  No active apt repos in: /etc/apt/sources.list.d/home:ungoogled_chromium.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //ftp.icm.edu.pl/pub/Linux/dist/linuxmint/packages faye main upstream import backport
    2: deb http: //ftp.pl.debian.org/debian bookworm main contrib non-free non-free-firmware
    3: deb http: //ftp.pl.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
    4: deb http: //security.debian.org/ bookworm-security main contrib non-free non-free-firmware
    5: deb http: //ftp.pl.debian.org/debian bookworm-backports main contrib non-free non-free-firmware
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
Info:
  Processes: 242 Uptime: 1d 14m wakeups: 3 Memory: 7.7 GiB used: 4.75 GiB (61.7%) Init: systemd
  v: 252 target: graphical (5) default: graphical Compilers: gcc: 12.2.0 alt: 12 Client: Unknown
  python3.11 client inxi: 3.3.26
```

**Comment by rcalixte** [comment]
> ### Steps to reproduce
> I simply open the Nemo window and leave it open. Nothing more.
> 
> ### Expected behavior
> I think 2.5 GB and above is a bit too much for just an open Nemo window.

I haven't been able to replicate this on my end. I have around 70 MB total for nemo and nemo-desktop. Can you share more information about your configuration? Do you have any plugins enabled? Did anything else change on your system?



> This has only been happening for a few days.
> Previously, 5-6 days ago, there was no such memory consumption

Was something recently installed or updated?

**Comment by mtwebster** [comment]
Try wiping your thumbnail cache:
```
rm -rf ~/.cache/thumbnails
```
Then restart nemo/nemo-desktop.

If that doesn't help, try:
```
GIO_USE_VFS=local GSETTINGS_BACKEND=memory nemo
```
You'll get lots of warnings and nemo won't look right, but I'm curious if the memory issue still happens.

Check any bookmarks to mounts (maybe some broken ones?), unmount any removable drives

**Comment by MilczekZimowy** [comment]
Thank you very much.

I will do what you recommended and see if it helped.

**Comment by MilczekZimowy** [comment]
I applied the clear cache command and it seems to have worked.
Today I did not observe any excessive memory usage by Nemo throughout the day.

I also used this second command.
The terminal printed out a whole lot of information that I don't understand, but I'm submitting it. Maybe they'll come in handy.

```
GIO_USE_VFS=local GSETTINGS_BACKEND=memory nemo

(nemo:391889): Gtk-WARNING **: 18:44:43.011: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
nemo-media-columns: using a timeout of 0.20 second(s) for file processing
I:SyncthingPlugin:Initializing...
I:SyncthingPlugin:Initialized.
V:Daemon:Set refresh interval to 20
sys:1: Warning: invalid cast from 'GtkApplicationImplX11' to 'GApplication'

(nemo:391889): GLib-GIO-CRITICAL **: 18:44:43.445: g_application_quit: assertion 'G_IS_APPLICATION (application)' failed
E:HTTP:g-io-error-quark: Nie można połączyć z 127.0.0.1: Połączenie odrzucone (39)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/http.py", line 48, in _connected
    self._connection = self.connect_to_service_finish(results)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Nie można połączyć z 127.0.0.1: Połączenie odrzucone (39)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 311, in get_background_items
    path = self._get_path(item).rstrip("/")
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
ERROR SET META:15 Ustawianie atrybutu metadata::nemo-icon-view-auto-layout nie jest obsługiwane
Nemo-Share-Message: 18:44:43.659: Called "net usershare info" but it failed: "net usershare" zwrócił błąd 255: net usershare: cannot open usershare directory /var/lib/samba/usershares. Error Nie ma takiego pliku ani katalogu
Please ask your system administrator to enable user sharing.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
CinnamonDesktop-Message: 18:44:43.778: Ignoring thumbnailer with missing binary: 'freecad-thumbnailer'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 246, in update_file_info
    path = self._get_path(file)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/syncthing_gtk/nautilusplugin.py", line 124, in _get_path
    return file.get_location().get_path().decode('utf-8')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?
sys:1: Warning: g_object_weak_unref: couldn't find weak ref 0x7fd728509d30(0x55cff6f4f120)
```
Thank you very much for help.
I hope my English is understandable
Actually, not mine but Google Translate
