### ISSUE TITLE
action-layout-editor not launch.

### ISSUE THREAD

**Issue by hitobashira** [linuxmint/nemo#3456]
### Distribution

Linux MInt latest(upgrade) and Manjaro Cinnamon.

### Package version

nemo 6.2.8  Cinnamon 6.2.9

### Frequency

Always

### Bug description

action-layout-editor. I can not launch. 

### Steps to reproduce

```
$ cinnamon-settings 
Using pam module (python3-pampy)
Loading Actions module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 753, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 178, in side_view_nav
    self.go_to_sidepage(sidePage, user_action=True)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 187, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 212, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_actions.py", line 24, in on_module_selected
    self.sidePage.load(self.window)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_actions.py", line 43, in load
    self.spices = Spice_Harvester(self.collection_type, self.window)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 191, in __init__
    self._load_metadata()
  File "/usr/share/cinnamon/cinnamon-settings/bin/Spices.py", line 468, in _load_metadata
    name = keyfile.get_locale_string('Nemo Action', 'Name')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### Expected behavior

*

### Additional information

I had get advise in manjaro forum.

Possibly an upstream issue - perhaps triggered by your chosen locale.

my locale 
$ locale
LANG=ja_JP.UTF-8
LC_CTYPE="ja_JP.UTF-8"
LC_NUMERIC="ja_JP.UTF-8"
LC_TIME="ja_JP.UTF-8"
LC_COLLATE="ja_JP.UTF-8"
LC_MONETARY="ja_JP.UTF-8"
LC_MESSAGES="ja_JP.UTF-8"
LC_PAPER="ja_JP.UTF-8"
LC_NAME="ja_JP.UTF-8"
LC_ADDRESS="ja_JP.UTF-8"
LC_TELEPHONE="ja_JP.UTF-8"
LC_MEASUREMENT="ja_JP.UTF-8"
LC_IDENTIFICATION="ja_JP.UTF-8"
LC_ALL=ja_JP.UTF-8

**Comment by mtwebster** [comment]
Do all of your actions have a Name field?

**Comment by mtwebster** [comment]
ref: https://github.com/linuxmint/cinnamon/commit/f32fbb04456aab1de7403e7954bf5a379a315bbb

**Comment by hitobashira** [comment]
There are about 60 of them. I checked them individually in the editor, and I think they are included.

However, I use emojis a lot.

```
fd -e nemo_action -x grep -P '\AName=' | cat -n

     3	Name=nemo いつもの設定ディレクトリ📂📂
     5	Name=💡💡czkawka "%N" しゃっくり
     6	Name=📘mcomix %N
     7	Name=ゴミ掃除 (空📂のみ削除)➡%N
    12	Name=✡✡✡自炊 タイトル自炊Naked  %N
    19	Name=🎨左右削除: %N
    20	Name=📗自炊重複検査と削除 "%N"
    21	Name=自炊⚡ ⚡ ⚡ ⚡ ⚡注意RCFLAT⚡ %N
    27	Name=⚡自炊7zaまとめる移動3 %N
    28	Name=⚡自炊7zz削除まとめる %N
    30	Name=🐔CWD lin s/^/%p/
    31	Name=🐔タイトルNaked汎用-%p
    32	Name=broot in wezterm 🐰
    33	Name=🐫🐫🐫リネームアニメ %p
    35	Name=　　　　　メディア情報 ➤ %N
    36	Name=ファイルシステムP FSTYPE SIZE 😺 %N
    37	Name=▣いつものカレントディレクトリ📁📁
    40	Name=🐔CWD2 (dir) s/^/%p/
    41	Name=🐫🐫リネームダウン🐫 %p
    42	Name=ゼロ圧縮ブック化【%N.cb7】
    48	Name=💯 Gip グローバルIP
    49	Name=💾💾TIMESHIFT_ST15.sh💾💾
```


I don't know if this will be helpful, but I am also seeing the following phenomenon.
I have been having problems with nemo_action even before the layout editor.
In manjaro, when upgrading cinnamon, some nemo_action menus no longer appear.
This will start from January 2024. Probably around January 20th.

**Comment by mtwebster** [comment]
If you disable all of yours do system actions show up again?

For nemo itself, try running:
```
NEMO_DEBUG=Actions nemo --debug
```
This will spit out info on actions. I'd suggest disabling all but one to reduce the amount of logging.

**Comment by hitobashira** [comment]
thanks.
I had clear all action file. then I can see layout editor. 

`
ls -l ~/.local/share/nemo/ 
drwxr-xr-x 1    0 2024-09-13 16:03 actions
`
