### ISSUE TITLE
Nemo 1.8.3 segfaults on trying to move a file (Ctrl+X, Ctrl+V)

### ISSUE THREAD

**Issue by coert** [linuxmint/nemo#402]
```
(nemo:4254): GLib-GObject-WARNING **: invalid cast from `GtkAction' to `GtkIMContext'

(nemo:4254): GLib-GObject-WARNING **: invalid cast from `GtkAction' to `MeegoIMContext'

(nemo:4254): GLib-GObject-WARNING **: invalid cast from `GtkAction' to `MeegoIMContext'

Program received signal SIGSEGV, Segmentation fault.
0x00007fffcc2785ec in dbus_g_proxy_call () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
```

Trace:

```
#0  0x00007fffcc2785ec in dbus_g_proxy_call () from /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
#1  0x00007fffe81de479 in meego_im_proxy_reset () from /usr/lib/libmaliit-glib.so.0
#2  0x00007fffe83eae91 in ?? () from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#3  0x00007fffe83eaf32 in ?? () from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#4  0x00007fffe83eb026 in ?? () from /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/libim-maliit.so
#5  0x00007ffff72584be in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007ffff72022ec in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff72705ac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff53cd81b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff53e62df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff53e6f92 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00000000004d7648 in ?? ()
#13 0x00007ffff72705ac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff53cd81b in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff53e62df in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff53e6f92 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007ffff73b97a3 in gtk_window_propagate_key_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007ffff73bc2eb in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007ffff727049c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff53cd620 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff53deaf8 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff53e6996 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007ffff53e6f92 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007ffff739f77e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#26 0x00007ffff726e555 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00007ffff7270185 in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#28 0x00007ffff6e9f5e2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#29 0x00007ffff5109f05 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff510a248 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#31 0x00007ffff510a304 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#32 0x00007ffff56aa52c in g_application_run () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#33 0x000000000042c199 in ?? ()
#34 0x00007ffff428fea5 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#35 0x000000000042c1e5 in ?? ()
```

**Comment by Vahan86** [comment]
@coert, is this still an issue for you with Nemo 3.0.6?

**Comment by coert** [comment]
No, I haven't run into this in quite a while. I guess it just disappeared somewhere between v1.8.3 and v3.0.6 :)
