### ISSUE TITLE
nemo segfault

### ISSUE THREAD

**Issue by geoffhill** [linuxmint/nemo#794]
Running nemo on Arch Linux, upon attempting to open a folder, nemo crashed. Pulled the coredump and it appears to be a segfault.

I can provide the coredump file if that would be of use (not sure about the best way to attach files with Github Issues).

```
> sd coredumpctl -o downloads/nemo-crash dump /usr/bin/nemo
> gdb /usr/bin/nemo downloads/nemo-crash
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004bc23d in ?? ()
(gdb) bt
#0  0x00000000004bc23d in ?? ()
#1  0x0000000000484fa1 in ?? ()
#2  0x00007f57d18220ed in ?? () from /usr/lib/libgtk-3.so.0
#3  0x00007f57cfdde255 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#4  0x00007f57cfdeff4c in ?? () from /usr/lib/libgobject-2.0.so.0
#5  0x00007f57cfdf8265 in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#6  0x00007f57cfdf89bf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#7  0x00007f57d1952aa4 in ?? () from /usr/lib/libgtk-3.so.0
#8  0x00007f57d181fb4e in ?? () from /usr/lib/libgtk-3.so.0
#9  0x00007f57d182170e in gtk_main_do_event () from /usr/lib/libgtk-3.so.0
#10 0x00007f57d13caae2 in ?? () from /usr/lib/libgdk-3.so.0
#11 0x00007f57cfb09a0d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#12 0x00007f57cfb09cf8 in ?? () from /usr/lib/libglib-2.0.so.0
#13 0x00007f57cfb09dac in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#14 0x00007f57d00c400c in g_application_run () from /usr/lib/libgio-2.0.so.0
#15 0x000000000042c7b9 in ?? ()
#16 0x00007f57cec9c040 in __libc_start_main () from /usr/lib/libc.so.6
#17 0x000000000042c803 in ?? ()
```

Software versions:

```
> pacman -Q linux cinnamon nemo glibc
linux 3.17.6-1
cinnamon 2.4.5-1
nemo 2.4.4-1
glibc 2.20-4
```

**Comment by geoffhill** [comment]
Debug symbols not available for the binary that caused this and unable to repro. Closing.
