### ISSUE TITLE
nemo crashes during create_properties_window on jpg image

### ISSUE THREAD

**Issue by sruggier** [linuxmint/nemo#871]
I'm running LMDE 2 'Betsy'.

I can reproduce this consistently. When I right click on a certain image file and click on "Properties" Nemo crashes instead of opening the properties window.

See below for the output of bt and bt full on a sample core file dumped as a result of this crash:

```
bt:

Thread 1 (Thread 0x7f00537909c0 (LWP 30705)):
#0  ImportTIFF_Date (tiff=..., dateInfo=..., xmp=xmp@entry=0x1f8ac38, xmpNS=xmpNS@entry=0x7f005016f475 "http://ns.adobe.com/exif/1.0/", xmpProp=xmpProp@entry=0x7f0050170f7a "DateTimeOriginal") at ReconcileTIFF.cpp:1258
#1  0x00007f005015f6f0 in PhotoDataUtils::Import2WayExif (exif=..., xmp=xmp@entry=0x1f8ac38, iptcDigestState=iptcDigestState@entry=1) at ReconcileTIFF.cpp:1862
#2  0x00007f005015b8df in ImportPhotoData (exif=..., iptc=..., psir=..., iptcDigestState=iptcDigestState@entry=1, xmp=xmp@entry=0x1f8ac38, options=options@entry=4) at ReconcileLegacy.cpp:77
#3  0x00007f0050116dfe in JPEG_MetaHandler::ProcessXMP (this=<optimized out>) at JPEG_Handler.cpp:694
#4  0x00007f00501073ee in XMPFiles::GetXMP (this=this@entry=0x269d010, xmpObj=xmpObj@entry=0x7fffc7ea1540, xmpPacket=xmpPacket@entry=0x7fffc7ea1538, xmpPacketLen=xmpPacketLen@entry=0x7fffc7ea1534, packetInfo=packetInfo@entry=0x0) at XMPFiles.cpp:1370
#5  0x00007f0050105d0a in WXMPFiles_GetXMP_1 (xmpObjRef=0x269d010, xmpRef=0x1f8add0, clientPacket=0x0, packetInfo=0x0, SetClientString=0x7f00500bfa70 <TXMPFiles<std::string>::SetClientString(void*, char const*, unsigned int)>, wResult=0x7fffc7ea1590) at WXMPFiles.cpp:238
#6  0x00007f00500c23a8 in TXMPFiles<std::string>::GetXMP (this=this@entry=0x1f92050, xmpObj=xmpObj@entry=0x25c8140, xmpPacket=xmpPacket@entry=0x0, packetInfo=packetInfo@entry=0x0) at ../public/include/client-glue/TXMPFiles.incl_cpp:295
#7  0x00007f00500bdea8 in xmp_files_get_new_xmp (xf=0x1f92050) at exempi.cpp:322
#8  0x00000000004494dd in load_location (info=<optimized out>, page=<optimized out>) at nemo-image-properties-page.c:643
#9  get_property_pages (provider=0x1f8aef0, files=0x7fffc7ea11d0) at nemo-image-properties-page.c:764
#10 0x000000000046ccf1 in append_extension_pages (window=0x25263e0) at nemo-properties-window.c:4598
#11 0x0000000000477426 in create_properties_window (startup_data=<optimized out>) at nemo-properties-window.c:4914
#12 is_directory_ready_callback (file=0x1f8aef0, data=0x2578830) at nemo-properties-window.c:5052
#13 0x00000000004cb5d0 in ready_callback_call (callback=0x25786d0, directory=0x237e400) at nemo-directory-async.c:1275
#14 call_ready_callbacks_at_idle (callback_data=<optimized out>) at nemo-directory-async.c:1857
#15 0x00007f0050651b6d in g_main_dispatch (context=0x1568e70) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3111
#16 g_main_context_dispatch (context=context@entry=0x1568e70) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3710
#17 0x00007f0050651f48 in g_main_context_iterate (context=context@entry=0x1568e70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3781
#18 0x00007f0050651ffc in g_main_context_iteration (context=0x1568e70, context@entry=0x0, may_block=may_block@entry=1) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3842
#19 0x00007f0050c0e20c in g_application_run (application=0x1537110, argc=argc@entry=1, argv=argv@entry=0x7fffc7ea19d8) at /tmp/buildd/glib2.0-2.42.1/./gio/gapplication.c:2282
#20 0x000000000042c679 in main (argc=1, argv=0x7fffc7ea19d8) at nemo-main.c:101


bt full:

Thread 1 (Thread 0x7f00537909c0 (LWP 30705)):
#0  ImportTIFF_Date (tiff=..., dateInfo=..., xmp=xmp@entry=0x1f8ac38, xmpNS=xmpNS@entry=0x7f005016f475 "http://ns.adobe.com/exif/1.0/", xmpProp=xmpProp@entry=0x7f0050170f7a "DateTimeOriginal") at ReconcileTIFF.cpp:1258
        dateStr = 0x329b2a30 <error: Cannot access memory at address 0x329b2a30>
        binValue = {year = 33074368, month = 0, day = 1, hour = 0, minute = 33074928, second = 0, hasDate = 232 '\350', hasTime = 3 '\003', hasTimeZone = 12 '\f', tzSign = 80 'P', tzHour = 32512, tzMinute = 0, nanoSecond = 0}
        secInfo = {id = 44208, type = 504, count = 0, dataPtr = 0x7f00500eb0e5 <WXMPMeta_DoesPropertyExist_1(XMPMetaRef, XMP_StringPtr, XMP_StringPtr, WXMP_Result*)+85>, dataLen = 33074928}
        found = <optimized out>
        secID = 37521
#1  0x00007f005015f6f0 in PhotoDataUtils::Import2WayExif (exif=..., xmp=xmp@entry=0x1f8ac38, iptcDigestState=iptcDigestState@entry=1) at ReconcileTIFF.cpp:1862
        nativeEndian = false
        found = true
        foundFromXMP = <optimized out>
        tagInfo = {id = 36867, type = 2, count = 20, dataPtr = 0x329b2a30, dataLen = 20}
#2  0x00007f005015b8df in ImportPhotoData (exif=..., iptc=..., psir=..., iptcDigestState=iptcDigestState@entry=1, xmp=xmp@entry=0x1f8ac38, options=options@entry=4) at ReconcileLegacy.cpp:77
        haveXMP = false
        haveExif = true
        haveIPTC = false
        savedExif = warning: RTTI symbol not found for class 'TXMPMeta<std::string>'
{_vptr.TXMPMeta = 0x7f005039b890 <vtable for TXMPMeta<std::string>+16>, xmpRef = 0x25be400}
#3  0x00007f0050116dfe in JPEG_MetaHandler::ProcessXMP (this=<optimized out>) at JPEG_Handler.cpp:694
        haveIPTC = <optimized out>
        exif = @0x1f8aef0: {_vptr.TIFF_Manager = 0x7f005039d410 <vtable for TIFF_MemoryReader+16>, static kBigEndianPrefix = 1296891946, static kLittleEndianPrefix = 1229531648, static kEmptyTIFFLength = 8, static kEmptyIFDLength = 6, static kIFDEntryLength = 12, GetUns16 = 0x7f00501688a0 <GetUns16BE(void const*)>, GetUns32 = 0x7f00501688c0 <GetUns32BE(void const*)>, GetFloat = 0x7f00501688e0 <GetFloatBE(void const*)>, GetDouble = 0x7f0050168900 <GetDoubleBE(void const*)>, PutUns16 = 0x7f0050168930 <PutUns16BE(XMP_Uns16, void*)>, PutUns32 = 0x7f0050168950 <PutUns32BE(XMP_Uns32, void*)>, PutFloat = 0x7f0050168970 <PutFloatBE(float, void*)>, PutDouble = 0x7f0050168a70 <PutDoubleBE(double, void*)>, bigEndian = true, nativeEndian = false}
        psir = @0x1f8afb0: {_vptr.PSIR_Manager = 0x7f005039cd90 <vtable for PSIR_MemoryReader+16>}
        iptcInfo = {id = 0, dataLen = 0, dataPtr = 0x0, origOffset = 0}
        readOnly = <optimized out>
        iptc = @0x268bf20: {_vptr.IPTC_Manager = 0x7f005039c150 <vtable for IPTC_Reader+16>, dataSets = std::multimap with 0 elements, iptcContent = 0x0, iptcLength = 0, offset190 = 0, length190 = 0, offset2xx = 0, length2xx = 0, changed = false, ownedContent = false, utf8Encoding = false}
        haveExif = <optimized out>
        havePSIR = <optimized out>
        iptcDigestState = 1
        options = <optimized out>
        haveXMP = <optimized out>
#4  0x00007f00501073ee in XMPFiles::GetXMP (this=this@entry=0x269d010, xmpObj=xmpObj@entry=0x7fffc7ea1540, xmpPacket=xmpPacket@entry=0x7fffc7ea1538, xmpPacketLen=xmpPacketLen@entry=0x7fffc7ea1534, packetInfo=packetInfo@entry=0x0) at XMPFiles.cpp:1370
        applyTemplateFlags = 9
#5  0x00007f0050105d0a in WXMPFiles_GetXMP_1 (xmpObjRef=0x269d010, xmpRef=0x1f8add0, clientPacket=0x0, packetInfo=0x0, SetClientString=0x7f00500bfa70 <TXMPFiles<std::string>::SetClientString(void*, char const*, unsigned int)>, wResult=0x7fffc7ea1590) at WXMPFiles.cpp:238
        xmpObj = warning: RTTI symbol not found for class 'TXMPMeta<std::string>'
{_vptr.TXMPMeta = 0x7f005039b890 <vtable for TXMPMeta<std::string>+16>, xmpRef = 0x1f8add0}
        hasXMP = false
        packetStr = 0x7f00535bd325 "I\211\303L\213L$0L\213D$(H\213|$ H\213t$\030H\213T$\020H\213L$\bH\213\004$H\203\304HA\377\343ffffff.\017\037\204"
        packetLen = 0
        thiz = 0x269d010
        objLock = {lock = 0x269d020}
#6  0x00007f00500c23a8 in TXMPFiles<std::string>::GetXMP (this=this@entry=0x1f92050, xmpObj=xmpObj@entry=0x25c8140, xmpPacket=xmpPacket@entry=0x0, packetInfo=packetInfo@entry=0x0) at ../public/include/client-glue/TXMPFiles.incl_cpp:295
        xmpRef = <optimized out>
        wResult = {errMessage = 0x0, ptrResult = 0x7f00535bd325, floatResult = 1.6341043372566727e-316, int64Result = 0, int32Result = 0}
        hasXMP = <optimized out>
#7  0x00007f00500bdea8 in xmp_files_get_new_xmp (xf=0x1f92050) at exempi.cpp:322
        xmp = 0x25c8140
        txf = 0x1f92050
        result = false
#8  0x00000000004494dd in load_location (info=<optimized out>, page=<optimized out>) at nemo-image-properties-page.c:643
        xf = 0x1f8ac38
        file = 0x25b6f40
        uri = 0x269d470 "file:///[redacted]/IMG_20150319_102526.jpg"
#9  get_property_pages (provider=0x1f8aef0, files=0x7fffc7ea11d0) at nemo-image-properties-page.c:764
        page = 0x269c960
        real_page = 0x329b2a30
        pages = 0x269c960
        file = 0x1dec8b0
        mime_type = 0x2634fc0 "image/jpeg"
#10 0x000000000046ccf1 in append_extension_pages (window=0x25263e0) at nemo-properties-window.c:4598
        provider = <optimized out>
        pages = <optimized out>
        l = <optimized out>
        providers = 0x25897a0
        p = 0x25897a0
#11 0x0000000000477426 in create_properties_window (startup_data=<optimized out>) at nemo-properties-window.c:4914
No locals.
#12 is_directory_ready_callback (file=0x1f8aef0, data=0x2578830) at nemo-properties-window.c:5052
        new_window = 0x25263e0
#13 0x00000000004cb5d0 in ready_callback_call (callback=0x25786d0, directory=0x237e400) at nemo-directory-async.c:1275
No locals.
#14 call_ready_callbacks_at_idle (callback_data=<optimized out>) at nemo-directory-async.c:1857
        directory = 0x237e400
        node = 0x24eeee0
        next = <optimized out>
        callback = 0x25786d0
#15 0x00007f0050651b6d in g_main_dispatch (context=0x1568e70) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3111
        dispatch = 0x7f005064e6c0 <g_idle_dispatch>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x237e400
        callback = 0x4cb490 <call_ready_callbacks_at_idle>
        cb_funcs = <optimized out>
        cb_data = 0x2573b00
        need_destroy = <optimized out>
        source = 0x1cd6690
        current = 0x159edb0
        i = 2
#16 g_main_context_dispatch (context=context@entry=0x1568e70) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3710
No locals.
#17 0x00007f0050651f48 in g_main_context_iterate (context=context@entry=0x1568e70, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3781
        max_priority = 200
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 3
        fds = 0x1523480
#18 0x00007f0050651ffc in g_main_context_iteration (context=0x1568e70, context@entry=0x0, may_block=may_block@entry=1) at /tmp/buildd/glib2.0-2.42.1/./glib/gmain.c:3842
        retval = <optimized out>
#19 0x00007f0050c0e20c in g_application_run (application=0x1537110, argc=argc@entry=1, argv=argv@entry=0x7fffc7ea19d8) at /tmp/buildd/glib2.0-2.42.1/./gio/gapplication.c:2282
        arguments = 0x1523480
        status = 0
        __FUNCTION__ = "g_application_run"
#20 0x000000000042c679 in main (argc=1, argv=0x7fffc7ea19d8) at nemo-main.c:101
        retval = <optimized out>
        application = 0x1537110
```

**Comment by Vahan86** [comment]
@sruggier, is this still an issue for you with Nemo 3.0.6?

**Comment by Vahan86** [comment]
@JosephMcc, can we close the issue?

**Comment by sruggier** [comment]
@Vahan86 @JosephMcc sorry I didn't respond in November! I just checked now, and this is still an issue with Nemo 3.2.2, sadly. Can one of you reopen this?

**Comment by JosephMcc** [comment]
Sure thing.

**Comment by leigh123linux** [comment]
@sruggier  Is it just one file that causes the crash?, can you provide some info about the file

```
$ file '/home/leigh/Pictures/Screenshot from 2016-12-18 04-28-27.png' 
/home/leigh/Pictures/Screenshot from 2016-12-18 04-28-27.png: PNG image data, 3840 x 2160, 8-bit/color RGB, non-interlaced
```

**Comment by sruggier** [comment]
```
$ file IMG_20150319_102526.jpg 
IMG_20150319_102526.jpg: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=11, software=KTU84Q_3_f600, GPS-Data, orientation=upper-left, datetime=2015:03:19 10:25:26, model=Xperia ZL, yresolution=190, resolutionunit=2, xresolution=198, manufacturer=Sony], baseline, precision 8, 4128x3096, frames 3
```

Based on sampling a few pictures I have lying around, it may be any pictures that were taken with this particular phone, or possibly any pictures taken with the particular version of CyanogenMod that I was running on it. Affected images are no longer affected if I strip off EXIF metadata.

**Comment by leigh123linux** [comment]
I doubt it will be possible to fix this issue within the nemo/cinnamon packages as the issue seems to be in exempi
